/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.ResourceLocation
 *  net.minecraftforge.event.RegistryEvent$Register
 *  net.minecraftforge.fml.common.Mod$EventBusSubscriber
 *  net.minecraftforge.fml.common.eventhandler.SubscribeEvent
 *  net.minecraftforge.fml.common.registry.EntityEntry
 *  net.minecraftforge.fml.common.registry.EntityEntryBuilder
 *  net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry
 *  net.minecraftforge.fml.common.registry.GameRegistry
 *  net.minecraftforge.registries.IForgeRegistryEntry
 */
package xol.lostinfinity.init;

import net.minecraft.world.entity.Entity;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.registry.EntityEntryBuilder;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.registries.IForgeRegistryEntry;
import xol.lostinfinity.block.tileentity.BlockEntityAlignmentDialGame;
import xol.lostinfinity.block.tileentity.BlockEntityAncientSymbolInterpreter;
import xol.lostinfinity.block.tileentity.BlockEntityChemistryTable;
import xol.lostinfinity.block.tileentity.BlockEntityChromaGame;
import xol.lostinfinity.block.tileentity.BlockEntityCircuitCalibrator;
import xol.lostinfinity.block.tileentity.BlockEntityCombustionEngine;
import xol.lostinfinity.block.tileentity.BlockEntityCompressionTable;
import xol.lostinfinity.block.tileentity.BlockEntityCthulhuSpawner;
import xol.lostinfinity.block.tileentity.BlockEntityDrillConsole;
import xol.lostinfinity.block.tileentity.BlockEntityEternalBeacon;
import xol.lostinfinity.block.tileentity.BlockEntityFusionTable;
import xol.lostinfinity.block.tileentity.BlockEntityGearbox;
import xol.lostinfinity.block.tileentity.BlockEntityGenerator;
import xol.lostinfinity.block.tileentity.BlockEntityGrinder;
import xol.lostinfinity.block.tileentity.BlockEntityKillerVine;
import xol.lostinfinity.block.tileentity.BlockEntityLightEmitter;
import xol.lostinfinity.block.tileentity.BlockEntityMelodicSequencer;
import xol.lostinfinity.block.tileentity.BlockEntityNavigationDevice;
import xol.lostinfinity.block.tileentity.BlockEntityNebulousBeacon;
import xol.lostinfinity.block.tileentity.BlockEntityNicroniumInfuser;
import xol.lostinfinity.block.tileentity.BlockEntityPolymerizationDevice;
import xol.lostinfinity.block.tileentity.BlockEntityPortalNexus;
import xol.lostinfinity.block.tileentity.BlockEntityPortalNode;
import xol.lostinfinity.block.tileentity.BlockEntityPowerCollider;
import xol.lostinfinity.block.tileentity.BlockEntityPowerConduit;
import xol.lostinfinity.block.tileentity.BlockEntityRainfallGenerator;
import xol.lostinfinity.block.tileentity.BlockEntityRemoteControl;
import xol.lostinfinity.block.tileentity.BlockEntitySapEvaporator;
import xol.lostinfinity.block.tileentity.BlockEntityShipmentFiller;
import xol.lostinfinity.block.tileentity.BlockEntityTeslaTower;
import xol.lostinfinity.block.tileentity.BlockEntityVoidVacuum;
import xol.lostinfinity.block.tileentity.BlockEntityWeldingChamber;
import xol.lostinfinity.mob.entity.base.EntityParticleTrojan;
import xol.lostinfinity.mob.entity.boss.EntityAlestria;
import xol.lostinfinity.mob.entity.boss.EntityArash;
import xol.lostinfinity.mob.entity.boss.EntityArenaEvent;
import xol.lostinfinity.mob.entity.boss.EntityAtlasCrystal;
import xol.lostinfinity.mob.entity.boss.EntityAtlasSpire;
import xol.lostinfinity.mob.entity.boss.EntityBarul;
import xol.lostinfinity.mob.entity.boss.EntityCryonus;
import xol.lostinfinity.mob.entity.boss.EntityDarrio;
import xol.lostinfinity.mob.entity.boss.EntityDeviantCrystal;
import xol.lostinfinity.mob.entity.boss.EntityDeviantWither;
import xol.lostinfinity.mob.entity.boss.EntityDroidBoss;
import xol.lostinfinity.mob.entity.boss.EntityDuskerQueen;
import xol.lostinfinity.mob.entity.boss.EntityElara;
import xol.lostinfinity.mob.entity.boss.EntityNuxuro;
import xol.lostinfinity.mob.entity.boss.EntityOzor;
import xol.lostinfinity.mob.entity.boss.EntityOzorDecoy;
import xol.lostinfinity.mob.entity.boss.EntityPuzzleMaster;
import xol.lostinfinity.mob.entity.boss.EntityRestorationCrystal;
import xol.lostinfinity.mob.entity.boss.EntityRikarus;
import xol.lostinfinity.mob.entity.boss.EntitySentryCrystal;
import xol.lostinfinity.mob.entity.boss.EntityThundyron;
import xol.lostinfinity.mob.entity.boss.EntityUrogo;
import xol.lostinfinity.mob.entity.boss.EntityVelo;
import xol.lostinfinity.mob.entity.boss.EntityVycellia;
import xol.lostinfinity.mob.entity.boss.EntityWitherSkullling;
import xol.lostinfinity.mob.entity.contest.EntityBloodhunter;
import xol.lostinfinity.mob.entity.contest.EntityContestHologram;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerBattleSnakes;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerBombers;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerDuelArena;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerHolodeck;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerHunters;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerInkBattle;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerLaserTag;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerLightBridge;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerParkour;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerRedlight;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerTargets;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerTrampolineDodgeball;
import xol.lostinfinity.mob.entity.contest.controller.EntityControllerTreadmill;
import xol.lostinfinity.mob.entity.contest.misc.EntityTreadmillObstacle;
import xol.lostinfinity.mob.entity.contest.misc.EntityTreadmillObstacleJumpable;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorBattleSnakes;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorBombers;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorDuelArena;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorHolodeck;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorHunters;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorInkBattle;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorLaserTag;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorLightBridge;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorParkour;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorRedlight;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorTargets;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorTrampolineDodgeball;
import xol.lostinfinity.mob.entity.contest.operator.EntityOperatorTreadmill;
import xol.lostinfinity.mob.entity.contest.trader.EntityArcheologist;
import xol.lostinfinity.mob.entity.contest.trader.EntityChemist;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderBattleSnakes;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderBombers;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderHolodeck;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderHunters;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderInkBattle;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderLaserTag;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderLightbridge;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderMarket;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderParkour;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderRedlight;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderTargets;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderTrampolineDodgeball;
import xol.lostinfinity.mob.entity.contest.trader.EntityContraderTreadmill;
import xol.lostinfinity.mob.entity.cthulhu.EntityCelestialStatue;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhu;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuBlackHole;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuCloud;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuDeathFX;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuHealingOrb;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuRift;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuSpear;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuTentacle;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuTentaclePersist;
import xol.lostinfinity.mob.entity.cthulhu.EntityCthulhuTurret;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantAmalgam;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBat;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBear;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBlaze;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCaveSpider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantChicken;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCow;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCreeper;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantDimTrader;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEnderman;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEvoker;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEvokerVex;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGhast;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGolem;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGuardian;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantHorse;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantHusk;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantLlama;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantMagmacube;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantMooshroom;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantOcelote;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantPig;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantPiglin;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSheep;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantShulker;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSkeleton;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSkyworm;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSlime;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSlimeStrider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSnowman;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSpider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSquid;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantStray;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantVex;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWitch;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWitherSkeleton;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWolf;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantZombie;
import xol.lostinfinity.mob.entity.deviant.EntityLostDeviant;
import xol.lostinfinity.mob.entity.deviant.prime.EntityAzross;
import xol.lostinfinity.mob.entity.deviant.prime.EntityKalikos;
import xol.lostinfinity.mob.entity.deviant.prime.EntityLivorax;
import xol.lostinfinity.mob.entity.deviant.prime.EntityZenon;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanBlaze;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanCreeper;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanEnderman;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanLlama;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanMagmacube;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanPiglin;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanShulker;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanSkeleton;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanSpider;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanStray;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanVex;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanZombie;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTrialObserver;
import xol.lostinfinity.mob.entity.fungal.EntityFungfly;
import xol.lostinfinity.mob.entity.fungal.EntityMushmerra;
import xol.lostinfinity.mob.entity.fungal.EntityMushmerraClone;
import xol.lostinfinity.mob.entity.fungal.EntityShroomite;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyBeast;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyDragon;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyGladiator;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyGulper;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxySorcerer;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxySpire;
import xol.lostinfinity.mob.entity.galaxy.EntityLaserSpire;
import xol.lostinfinity.mob.entity.labyrinth.EntityAspect;
import xol.lostinfinity.mob.entity.labyrinth.EntityClinger;
import xol.lostinfinity.mob.entity.labyrinth.EntityCyclos;
import xol.lostinfinity.mob.entity.labyrinth.EntityGloop;
import xol.lostinfinity.mob.entity.labyrinth.EntityGloopMother;
import xol.lostinfinity.mob.entity.labyrinth.EntityLabWarrior;
import xol.lostinfinity.mob.entity.labyrinth.EntityLabWizard;
import xol.lostinfinity.mob.entity.labyrinth.EntityNat;
import xol.lostinfinity.mob.entity.labyrinth.EntitySentry;
import xol.lostinfinity.mob.entity.labyrinth.EntityStickler;
import xol.lostinfinity.mob.entity.labyrinth.EntityVectosect;
import xol.lostinfinity.mob.entity.minion.EntityAbyssalCrabulon;
import xol.lostinfinity.mob.entity.minion.EntityAuraOfAllegiance;
import xol.lostinfinity.mob.entity.minion.EntityBombDrone;
import xol.lostinfinity.mob.entity.minion.EntityLostBlade;
import xol.lostinfinity.mob.entity.minion.EntityLuminousGuardian;
import xol.lostinfinity.mob.entity.minion.andromeda.EntityAndromedaChaser;
import xol.lostinfinity.mob.entity.minion.andromeda.EntityAndromedaController;
import xol.lostinfinity.mob.entity.misc.EntityBomberBomb;
import xol.lostinfinity.mob.entity.misc.EntityCellGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityClusterCannon;
import xol.lostinfinity.mob.entity.misc.EntityConnectGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityCourseRing;
import xol.lostinfinity.mob.entity.misc.EntityDimensionalMerchant;
import xol.lostinfinity.mob.entity.misc.EntityDroid;
import xol.lostinfinity.mob.entity.misc.EntityEffigyEffect;
import xol.lostinfinity.mob.entity.misc.EntityEidolonMist;
import xol.lostinfinity.mob.entity.misc.EntityFeralMerchant;
import xol.lostinfinity.mob.entity.misc.EntityGhostCopy;
import xol.lostinfinity.mob.entity.misc.EntityIonExplosion;
import xol.lostinfinity.mob.entity.misc.EntityLightGame;
import xol.lostinfinity.mob.entity.misc.EntityMarkOfInfiniteDespair;
import xol.lostinfinity.mob.entity.misc.EntityMemPuzzleMerchant;
import xol.lostinfinity.mob.entity.misc.EntityMirrorZombie;
import xol.lostinfinity.mob.entity.misc.EntityMortarCannon;
import xol.lostinfinity.mob.entity.misc.EntityMultiverseGhost;
import xol.lostinfinity.mob.entity.misc.EntityNitroExplosion;
import xol.lostinfinity.mob.entity.misc.EntityNuclearExplosion;
import xol.lostinfinity.mob.entity.misc.EntityPickleMan;
import xol.lostinfinity.mob.entity.misc.EntityPipeGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityPlasmaBomb;
import xol.lostinfinity.mob.entity.misc.EntityPlasmaExplosion;
import xol.lostinfinity.mob.entity.misc.EntityPlasmaSlicer;
import xol.lostinfinity.mob.entity.misc.PlayerLimb;
import xol.lostinfinity.mob.entity.misc.EntityRhythmGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityRift;
import xol.lostinfinity.mob.entity.misc.EntityRisingPhantom;
import xol.lostinfinity.mob.entity.misc.EntityRocketStrappedExplosive;
import xol.lostinfinity.mob.entity.misc.EntitySandAttack;
import xol.lostinfinity.mob.entity.misc.EntitySkybooster;
import xol.lostinfinity.mob.entity.misc.EntitySkycrab;
import xol.lostinfinity.mob.entity.misc.EntitySlimeStrider;
import xol.lostinfinity.mob.entity.misc.EntitySpectre;
import xol.lostinfinity.mob.entity.misc.EntityStarfiend;
import xol.lostinfinity.mob.entity.misc.EntityStickyBomb;
import xol.lostinfinity.mob.entity.misc.EntityStormBomb;
import xol.lostinfinity.mob.entity.misc.EntitySupplyTrader;
import xol.lostinfinity.mob.entity.misc.EntityTNTZombie;
import xol.lostinfinity.mob.entity.misc.EntityTentacleTrap;
import xol.lostinfinity.mob.entity.misc.EntityThunderBomb;
import xol.lostinfinity.mob.entity.misc.EntityTornIndividual;
import xol.lostinfinity.mob.entity.misc.EntityTotemMoon;
import xol.lostinfinity.mob.entity.misc.EntityTotemPylon;
import xol.lostinfinity.mob.entity.misc.EntityTotemSplitter;
import xol.lostinfinity.mob.entity.misc.EntityUnstableMerchant;
import xol.lostinfinity.mob.entity.misc.EntityUnstableRift;
import xol.lostinfinity.mob.entity.misc.EntityWhackGameMerchant;
import xol.lostinfinity.mob.entity.misc.EntityWormholePortal;
import xol.lostinfinity.mob.entity.mount.EntityJetMount;
import xol.lostinfinity.mob.entity.mount.EntityXScreacher;
import xol.lostinfinity.mob.entity.murk.EntityCaveTerror;
import xol.lostinfinity.mob.entity.murk.EntityDoomsday;
import xol.lostinfinity.mob.entity.murk.EntityScorpwing;
import xol.lostinfinity.mob.entity.murk.EntityScreamer;
import xol.lostinfinity.mob.entity.murk.EntitySkyre;
import xol.lostinfinity.mob.entity.murk.EntityTorpedon;
import xol.lostinfinity.mob.entity.murk.EntityWhisper;
import xol.lostinfinity.mob.entity.nebula.EntityNebulaGiant;
import xol.lostinfinity.mob.entity.nebula.EntityNebulaGrunt;
import xol.lostinfinity.mob.entity.nebula.EntityNebulaWizard;
import xol.lostinfinity.mob.entity.sea.EntityCrabulon;
import xol.lostinfinity.mob.entity.sea.EntityDoublerang;
import xol.lostinfinity.mob.entity.sea.EntityEelShark;
import xol.lostinfinity.mob.entity.sea.EntityGlowfish;
import xol.lostinfinity.mob.entity.sea.EntityLongfin;
import xol.lostinfinity.mob.entity.sea.EntityOctobrella;
import xol.lostinfinity.mob.entity.sea.EntityPearlCollector;
import xol.lostinfinity.mob.entity.sea.EntityRayfish;
import xol.lostinfinity.mob.entity.sea.EntityRibshark;
import xol.lostinfinity.mob.entity.sea.EntityUnderfin;
import xol.lostinfinity.mob.entity.sea.leviathan.EntityLeviathanController;
import xol.lostinfinity.mob.entity.sea.seaserpent.EntitySeaSerpentController;
import xol.lostinfinity.mob.entity.starforge.EntityAcidback;
import xol.lostinfinity.mob.entity.starforge.EntityAugmenticon;
import xol.lostinfinity.mob.entity.starforge.EntityBlisterweed;
import xol.lostinfinity.mob.entity.starforge.EntityChomper;
import xol.lostinfinity.mob.entity.starforge.EntityClusterweed;
import xol.lostinfinity.mob.entity.starforge.EntityClyster;
import xol.lostinfinity.mob.entity.starforge.EntityCrawker;
import xol.lostinfinity.mob.entity.starforge.EntityCrusher;
import xol.lostinfinity.mob.entity.starforge.EntityDoomDog;
import xol.lostinfinity.mob.entity.starforge.EntityDoublejaw;
import xol.lostinfinity.mob.entity.starforge.EntityDrippler;
import xol.lostinfinity.mob.entity.starforge.EntityDusker;
import xol.lostinfinity.mob.entity.starforge.EntityEssenceDweller;
import xol.lostinfinity.mob.entity.starforge.EntityEssenceIdol;
import xol.lostinfinity.mob.entity.starforge.EntityExplosect;
import xol.lostinfinity.mob.entity.starforge.EntityEyeSlug;
import xol.lostinfinity.mob.entity.starforge.EntityFlapper;
import xol.lostinfinity.mob.entity.starforge.EntityFlashfly;
import xol.lostinfinity.mob.entity.starforge.EntityFlurky;
import xol.lostinfinity.mob.entity.starforge.EntityFlutterbee;
import xol.lostinfinity.mob.entity.starforge.EntityFlutterfyre;
import xol.lostinfinity.mob.entity.starforge.EntityFyreweed;
import xol.lostinfinity.mob.entity.starforge.EntityGalacticTerror;
import xol.lostinfinity.mob.entity.starforge.EntityGiantFlapper;
import xol.lostinfinity.mob.entity.starforge.EntityGiantFyreweed;
import xol.lostinfinity.mob.entity.starforge.EntityGiantRockslug;
import xol.lostinfinity.mob.entity.starforge.EntityGlangler;
import xol.lostinfinity.mob.entity.starforge.EntityGloboon;
import xol.lostinfinity.mob.entity.starforge.EntityGlobro;
import xol.lostinfinity.mob.entity.starforge.EntityGlochipper;
import xol.lostinfinity.mob.entity.starforge.EntityGlomite;
import xol.lostinfinity.mob.entity.starforge.EntityGnawer;
import xol.lostinfinity.mob.entity.starforge.EntityGorger;
import xol.lostinfinity.mob.entity.starforge.EntityGrappler;
import xol.lostinfinity.mob.entity.starforge.EntityGravhead;
import xol.lostinfinity.mob.entity.starforge.EntityGrubber;
import xol.lostinfinity.mob.entity.starforge.EntityHanger;
import xol.lostinfinity.mob.entity.starforge.EntityHurler;
import xol.lostinfinity.mob.entity.starforge.EntityHypnosaur;
import xol.lostinfinity.mob.entity.starforge.EntityLeer;
import xol.lostinfinity.mob.entity.starforge.EntityLurcher;
import xol.lostinfinity.mob.entity.starforge.EntityMinimite;
import xol.lostinfinity.mob.entity.starforge.EntityNightshyre;
import xol.lostinfinity.mob.entity.starforge.EntityOrbiter;
import xol.lostinfinity.mob.entity.starforge.EntityPhaser;
import xol.lostinfinity.mob.entity.starforge.EntityRavager;
import xol.lostinfinity.mob.entity.starforge.EntityReflectal;
import xol.lostinfinity.mob.entity.starforge.EntityRibrex;
import xol.lostinfinity.mob.entity.starforge.EntityRockpest;
import xol.lostinfinity.mob.entity.starforge.EntityRockslug;
import xol.lostinfinity.mob.entity.starforge.EntityRockworm;
import xol.lostinfinity.mob.entity.starforge.EntityScreacher;
import xol.lostinfinity.mob.entity.starforge.EntityShimmer;
import xol.lostinfinity.mob.entity.starforge.EntitySightwalker;
import xol.lostinfinity.mob.entity.starforge.EntitySnapper;
import xol.lostinfinity.mob.entity.starforge.EntitySpinovern;
import xol.lostinfinity.mob.entity.starforge.EntitySpyker;
import xol.lostinfinity.mob.entity.starforge.EntityTentaclon;
import xol.lostinfinity.mob.entity.starforge.EntityTerrorFly;
import xol.lostinfinity.mob.entity.starforge.EntityTetherbug;
import xol.lostinfinity.mob.entity.starforge.EntityTitanopod;
import xol.lostinfinity.mob.entity.starforge.EntityVilebulb;
import xol.lostinfinity.mob.entity.starforge.EntityWeaver;
import xol.lostinfinity.mob.entity.starforge.EntityWisp;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuBeam;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuMeteor;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuMissile;
import xol.lostinfinity.projectile.cthulhu.EntityCthulhuTurretBullet;
import xol.lostinfinity.projectile.entity.EntityAcidRainDrop;
import xol.lostinfinity.projectile.entity.EntityAcidicConcoction;
import xol.lostinfinity.projectile.entity.EntityArcBlast;
import xol.lostinfinity.projectile.entity.EntityAsteroid;
import xol.lostinfinity.projectile.entity.EntityAstralShot;
import xol.lostinfinity.projectile.entity.EntityAtlasAttack;
import xol.lostinfinity.projectile.entity.EntityAvenger;
import xol.lostinfinity.projectile.entity.EntityAvengerLightning;
import xol.lostinfinity.projectile.entity.EntityBallOfContainedGluons;
import xol.lostinfinity.projectile.entity.EntityBallOfContainedQuarks;
import xol.lostinfinity.projectile.entity.EntityBarulChain;
import xol.lostinfinity.projectile.entity.EntityBeeAttack;
import xol.lostinfinity.projectile.entity.EntityBlightBomb;
import xol.lostinfinity.projectile.entity.EntityBlightPellet;
import xol.lostinfinity.projectile.entity.EntityBlightedComet;
import xol.lostinfinity.projectile.entity.EntityBloodhunterBlast;
import xol.lostinfinity.projectile.entity.EntityBossPortalEffect;
import xol.lostinfinity.projectile.entity.EntityCarrierProjectile;
import xol.lostinfinity.projectile.entity.EntityCelestialFire;
import xol.lostinfinity.projectile.entity.EntityCellularRock;
import xol.lostinfinity.projectile.entity.EntityChainOfVenomsAttack;
import xol.lostinfinity.projectile.entity.EntityChampionDodgeball;
import xol.lostinfinity.projectile.entity.EntityClusterBlast;
import xol.lostinfinity.projectile.entity.EntityComet;
import xol.lostinfinity.projectile.entity.EntityCrabulonProjectile;
import xol.lostinfinity.projectile.entity.EntityCreepingVineArrow;
import xol.lostinfinity.projectile.entity.EntityCreepingVinePod;
import xol.lostinfinity.projectile.entity.EntityCryoBeamEffect;
import xol.lostinfinity.projectile.entity.EntityCryoBolt;
import xol.lostinfinity.projectile.entity.EntityCrystalGellball;
import xol.lostinfinity.projectile.entity.EntityCrystalShard;
import xol.lostinfinity.projectile.entity.EntityDarkSpell;
import xol.lostinfinity.projectile.entity.EntityDeathShot;
import xol.lostinfinity.projectile.entity.EntityDebtCollectorEffect;
import xol.lostinfinity.projectile.entity.EntityDestabilizer;
import xol.lostinfinity.projectile.entity.EntityDeviantDeployer;
import xol.lostinfinity.projectile.entity.EntityDeviantEvokerBomb;
import xol.lostinfinity.projectile.entity.EntityDeviantEvokerFangs;
import xol.lostinfinity.projectile.entity.EntityDeviantEvokerShot;
import xol.lostinfinity.projectile.entity.EntityDeviantShulkerBullet;
import xol.lostinfinity.projectile.entity.EntityDeviantSnowball;
import xol.lostinfinity.projectile.entity.EntityDeviantSpit;
import xol.lostinfinity.projectile.entity.EntityDeviantSucker;
import xol.lostinfinity.projectile.entity.EntityDoomBlast;
import xol.lostinfinity.projectile.entity.EntityDoomShot;
import xol.lostinfinity.projectile.entity.EntityDroidBall;
import xol.lostinfinity.projectile.entity.EntityDroidLaser;
import xol.lostinfinity.projectile.entity.EntityDroidSucker;
import xol.lostinfinity.projectile.entity.EntityDroidZapper;
import xol.lostinfinity.projectile.entity.EntityDryadsGripAttack;
import xol.lostinfinity.projectile.entity.EntityDuskerQueenWeb;
import xol.lostinfinity.projectile.entity.EntityEchoBlast;
import xol.lostinfinity.projectile.entity.EntityEchoOfGravity;
import xol.lostinfinity.projectile.entity.EntityEffigyShot;
import xol.lostinfinity.projectile.entity.EntityElaraShot;
import xol.lostinfinity.projectile.entity.EntityElementiumAir;
import xol.lostinfinity.projectile.entity.EntityElementiumBlight;
import xol.lostinfinity.projectile.entity.EntityElementiumEarth;
import xol.lostinfinity.projectile.entity.EntityElementiumFire;
import xol.lostinfinity.projectile.entity.EntityElementiumPlague;
import xol.lostinfinity.projectile.entity.EntityElementiumPrime;
import xol.lostinfinity.projectile.entity.EntityElementiumShadow;
import xol.lostinfinity.projectile.entity.EntityElementiumWater;
import xol.lostinfinity.projectile.entity.EntityEmberShot;
import xol.lostinfinity.projectile.entity.EntityEnergyBurst;
import xol.lostinfinity.projectile.entity.EntityExothermite;
import xol.lostinfinity.projectile.entity.EntityExplosiveGoo;
import xol.lostinfinity.projectile.entity.EntityFallingStar;
import xol.lostinfinity.projectile.entity.EntityFearBomb;
import xol.lostinfinity.projectile.entity.EntityFirePellet;
import xol.lostinfinity.projectile.entity.EntityFluxBall;
import xol.lostinfinity.projectile.entity.EntityForbiddenBrand;
import xol.lostinfinity.projectile.entity.EntityFountainPellet;
import xol.lostinfinity.projectile.entity.EntityFractureBomb;
import xol.lostinfinity.projectile.entity.EntityGalaxyBlast;
import xol.lostinfinity.projectile.entity.EntityGalaxyBomb;
import xol.lostinfinity.projectile.entity.EntityGalaxyDragonFireball;
import xol.lostinfinity.projectile.entity.EntityGalaxyKnife;
import xol.lostinfinity.projectile.entity.EntityGalaxyLaser;
import xol.lostinfinity.projectile.entity.EntityGalaxySpell;
import xol.lostinfinity.projectile.entity.EntityGenericBomb;
import xol.lostinfinity.projectile.entity.EntityGloomSpell;
import xol.lostinfinity.projectile.entity.EntityGravityWarper;
import xol.lostinfinity.projectile.entity.EntityHomingBlight;
import xol.lostinfinity.projectile.entity.EntityInfinityTrident;
import xol.lostinfinity.projectile.entity.EntityInfinityTridentMK2;
import xol.lostinfinity.projectile.entity.EntityInkBomb;
import xol.lostinfinity.projectile.entity.EntityInkShot;
import xol.lostinfinity.projectile.entity.EntityIonicChakram;
import xol.lostinfinity.projectile.entity.EntityLaserBlast;
import xol.lostinfinity.projectile.entity.EntityLaserGunBeam;
import xol.lostinfinity.projectile.entity.EntityLaunchedKnife;
import xol.lostinfinity.projectile.entity.EntityLeviathanBreath;
import xol.lostinfinity.projectile.entity.EntityLeviathanTeslaOrb;
import xol.lostinfinity.projectile.entity.EntityLeviathanTracer;
import xol.lostinfinity.projectile.entity.EntityLivoraxBullet;
import xol.lostinfinity.projectile.entity.EntityLuminousGuardianLaser;
import xol.lostinfinity.projectile.entity.EntityMeteor;
import xol.lostinfinity.projectile.entity.EntityMicroRocket;
import xol.lostinfinity.projectile.entity.EntityMiniChakram;
import xol.lostinfinity.projectile.entity.MonsterComet;
import xol.lostinfinity.projectile.entity.EntityMortarShot;
import xol.lostinfinity.projectile.entity.EntityNebulaSpell;
import xol.lostinfinity.projectile.entity.EntityPicklePortal;
import xol.lostinfinity.projectile.entity.EntityPiercingShot;
import xol.lostinfinity.projectile.entity.EntityPlagueBlast;
import xol.lostinfinity.projectile.entity.EntityPoisonousBubble;
import xol.lostinfinity.projectile.entity.EntityPortalEffect;
import xol.lostinfinity.projectile.entity.EntityPowerPulse;
import xol.lostinfinity.projectile.entity.EntityProjectileKiller;
import xol.lostinfinity.projectile.entity.EntityPuzzleMasterArrow;
import xol.lostinfinity.projectile.entity.EntityRainDrop;
import xol.lostinfinity.projectile.entity.EntityRecursor;
import xol.lostinfinity.projectile.entity.EntityRockshot;
import xol.lostinfinity.projectile.entity.EntityScreamerBlast;
import xol.lostinfinity.projectile.entity.EntityScreamerPortalEffect;
import xol.lostinfinity.projectile.entity.EntitySelectionLaser;
import xol.lostinfinity.projectile.entity.EntitySelectorAttack;
import xol.lostinfinity.projectile.entity.EntitySkullShot;
import xol.lostinfinity.projectile.entity.EntitySkyStrike;
import xol.lostinfinity.projectile.entity.EntitySkycrabAttack;
import xol.lostinfinity.projectile.entity.EntitySonicAttack;
import xol.lostinfinity.projectile.entity.EntitySoundwaveBullet;
import xol.lostinfinity.projectile.entity.EntitySpiderBlast;
import xol.lostinfinity.projectile.entity.EntitySpikeBall;
import xol.lostinfinity.projectile.entity.EntityStarBlast;
import xol.lostinfinity.projectile.entity.EntityStickyProjectile;
import xol.lostinfinity.projectile.entity.EntityStrappedFirework;
import xol.lostinfinity.projectile.entity.EntityStunAttack;
import xol.lostinfinity.projectile.entity.EntitySunstoneRock;
import xol.lostinfinity.projectile.entity.EntityTNTStrapper;
import xol.lostinfinity.projectile.entity.EntityTekBullet;
import xol.lostinfinity.projectile.entity.EntityTentacleSeed;
import xol.lostinfinity.projectile.entity.EntityTetherBall;
import xol.lostinfinity.projectile.entity.EntityTitanRing;
import xol.lostinfinity.projectile.entity.EntityTormentorChain;
import xol.lostinfinity.projectile.entity.EntityUltraCrystalGel;
import xol.lostinfinity.projectile.entity.EntityUnstableBalloon;
import xol.lostinfinity.projectile.entity.EntityVeloMagic;
import xol.lostinfinity.projectile.entity.EntityVenomBlast;
import xol.lostinfinity.projectile.entity.EntityVoidLaser;
import xol.lostinfinity.projectile.entity.EntityVoltaicIonizerAttack;
import xol.lostinfinity.projectile.entity.EntityWandAttack;
import xol.lostinfinity.projectile.entity.EntityWhirlpool;
import xol.lostinfinity.projectile.entity.EntityWitchMagic;
import xol.lostinfinity.projectile.entity.EntityWitherBomb;
import xol.lostinfinity.projectile.entity.EntityWizardBlast;
import xol.lostinfinity.projectile.entity.EntityWormholeShot;
import xol.lostinfinity.projectile.entity.EntityXSonicAttack;
import xol.lostinfinity.projectile.entity.EntityZenonShot;
import xol.lostinfinity.stone.EntityInfinityStone;

@Mod.EventBusSubscriber(modid="lostinfinity")
public class EntityInit {
    private static int entityId = 0;

    @SubscribeEvent
    public static void registerEnities(RegistryEvent.Register<EntityEntry> event) {
        event.getRegistry().registerAll((IForgeRegistryEntry[])EntityInit.mobEntries());
        event.getRegistry().registerAll((IForgeRegistryEntry[])EntityInit.projectileEntries());
    }

    public static <E extends Entity> EntityEntry customEntityEntry(Class entityClass, String name, int primary, int secondary) {
        return EntityInit.doEntityEntry(entityClass, name, primary, secondary, true, 120);
    }

    public static <E extends Entity> EntityEntry egglessEntry(Class entityClass, String name, int primary, int secondary) {
        return EntityInit.doEntityEntry(entityClass, name, primary, secondary, false, 120);
    }

    public static <E extends Entity> EntityEntry doEntityEntry(Class entityClass, String name, int primary, int secondary, boolean egg, int track) {
        ++entityId;
        EntityEntryBuilder builder = EntityEntryBuilder.create();
        builder.entity(entityClass);
        builder.tracker(track, 1, true);
        if (egg) {
            builder.egg(primary, secondary);
        }
        EntityEntryBuilder.BuiltEntityEntry entry = (EntityEntryBuilder.BuiltEntityEntry)builder.id(new ResourceLocation("lostinfinity", name), entityId).name("lostinfinity." + name).build();
        entry.addedToRegistry();
        return entry;
    }

    public static EntityEntry customProjectileEntry(Class entityClass, String entityID) {
        return EntityEntryBuilder.create().entity(entityClass).id(new ResourceLocation("lostinfinity", entityID), ++entityId).name("lostinfinity." + entityID).tracker(120, 20, true).build();
    }

    public static EntityEntry customProjectileEntry(Class entityClass, String entityID, int interval) {
        return EntityEntryBuilder.create().entity(entityClass).id(new ResourceLocation("lostinfinity", entityID), ++entityId).name("lostinfinity." + entityID).tracker(120, interval, true).build();
    }

    public static EntityEntry[] mobEntries() {
        return new EntityEntry[]{EntityInit.customEntityEntry(EntityDimensionalMerchant.class, "dimensionalmerchant", 7614683, 443842), EntityInit.customEntityEntry(EntityDeviantBear.class, "deviantbear", 0x808AA8, 3104159), EntityInit.customEntityEntry(EntityTreadmillObstacle.class, "treadmillobstacle", 0x808AA8, 3104159), EntityInit.customEntityEntry(EntityTreadmillObstacleJumpable.class, "treadmillobstaclejumpable", 0x808AA8, 3104159), EntityInit.customEntityEntry(EntityDeviantGhast.class, "deviantghast", 0x444444, 0xB00900), EntityInit.customEntityEntry(EntityDeviantCow.class, "deviantcow", 2766650, 43263), EntityInit.customEntityEntry(EntityDeviantSheep.class, "deviantsheep", 2766650, 43263), EntityInit.customEntityEntry(EntityDeviantHorse.class, "devianthorse", 2766650, 43263), EntityInit.customEntityEntry(EntityDeviantPig.class, "deviantpig", 2766650, 43263), EntityInit.customEntityEntry(EntityDeviantEvoker.class, "deviantevoker", 2766650, 43263), EntityInit.customEntityEntry(EntityDeviantEvokerVex.class, "deviantevokervex", 2766650, 43263), EntityInit.customEntityEntry(EntityDeviantEnderman.class, "deviantenderman", 0, 9579469), EntityInit.customEntityEntry(EntityDeviantChicken.class, "deviantchicken", 0x888888, 5964804), EntityInit.customEntityEntry(EntityDeviantShulker.class, "deviantshulker", 4216413, 12247777), EntityInit.customEntityEntry(EntityDeviantSkyworm.class, "deviantskyworm", 1585203, 7783599), EntityInit.customEntityEntry(EntityElara.class, "elara", 11072475, 1780577), EntityInit.customEntityEntry(EntityInfinityStone.class, "infinitystone", 0, 0), EntityInit.customEntityEntry(EntityDeviantCreeper.class, "deviantcreeper", 4874085, 25830), EntityInit.customEntityEntry(EntityDeviantSkeleton.class, "deviantskeleton", 3623000, 0xF2F2F3), EntityInit.customEntityEntry(EntityUrogo.class, "urogo", 6488834, 12538624), EntityInit.customEntityEntry(EntityDroid.class, "droid", 0x737373, 12779777), EntityInit.customEntityEntry(EntityDroidBoss.class, "droidboss", 3624277, 12779777), EntityInit.customEntityEntry(EntityLostDeviant.class, "lostdeviant", 2571854, 474615), EntityInit.customEntityEntry(EntityArenaEvent.class, "arenaevent", 7857, 13303812), EntityInit.customEntityEntry(EntityLabWarrior.class, "labwarrior", 5139306, 9448480), EntityInit.customEntityEntry(EntityLabWizard.class, "labwizard", 419797, 9448480), EntityInit.customEntityEntry(EntityDeviantSpider.class, "deviantspider", 2306367, 46518), EntityInit.customEntityEntry(EntityAspect.class, "aspect", 0xA00100, 14471093), EntityInit.customEntityEntry(EntitySlimeStrider.class, "slimestrider", 6072961, 6983758), EntityInit.customEntityEntry(EntityVelo.class, "velo", 1192507, 1055801), EntityInit.customEntityEntry(EntityGalaxyBeast.class, "galaxybeast", 921102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGalaxySorcerer.class, "galaxysorcerer", 921102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGalaxyGladiator.class, "galaxygladiator", 921102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGalaxySpire.class, "galaxyspire", 921102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantAmalgam.class, "deviantamalgam", 921102, 0x4B4B4B), EntityInit.customEntityEntry(EntityStarfiend.class, "starfiend", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityBloodhunter.class, "bloodhunter", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFungfly.class, "fungfly", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRikarus.class, "rikarus", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRestorationCrystal.class, "restorationcrystal", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantWitch.class, "deviantwitch", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMirrorZombie.class, "mirrorzombie", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantSlimeStrider.class, "deviantslimestrider", 6072961, 6983758), EntityInit.customEntityEntry(EntityChemist.class, "chemist", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySandAttack.class, "sandattack", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantBlaze.class, "deviantblaze", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanBlaze.class, "titanblaze", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanShulker.class, "titanshulker", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanSpider.class, "titanspider", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanSkeleton.class, "titanskeleton", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTrialObserver.class, "trialobserver", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityReflectal.class, "reflectal", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLuminousGuardian.class, "luminousguardian", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityHanger.class, "hanger", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAcidback.class, "acidback", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGravhead.class, "gravhead", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRockpest.class, "rockpest", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySpinovern.class, "spinovern", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityHypnosaur.class, "hypnosaur", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityChomper.class, "chomper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRibrex.class, "ribrex", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGnawer.class, "gnawer", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityScreacher.class, "screacher", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityEyeSlug.class, "eyeslug", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFlutterfyre.class, "flutterfyre", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantSnowman.class, "deviantsnowman", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNuxuro.class, "nuxuro", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityClyster.class, "clyster", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCrawker.class, "crawker", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDusker.class, "dusker", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityExplosect.class, "explosect", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFlapper.class, "flapper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFlurky.class, "flurky", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFyreweed.class, "fyreweed", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGrappler.class, "grappler", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityHurler.class, "hurler", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityPhaser.class, "phaser", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityShimmer.class, "shimmer", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySpyker.class, "spyker", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantMooshroom.class, "deviantmooshroom", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantZombie.class, "deviantzombie", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantSlime.class, "deviantslime", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityArash.class, "arash", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAlestria.class, "alestria", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAtlasSpire.class, "atlasspire", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDarrio.class, "darrio", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityBarul.class, "barul", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySentryCrystal.class, "sentrycrystal", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAtlasCrystal.class, "atlascrystal", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantCrystal.class, "deviantcrystal", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantLlama.class, "deviantllama", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantMagmacube.class, "deviantmagmacube", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantVex.class, "deviantvex", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantStray.class, "deviantstray", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantPiglin.class, "deviantpiglin", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanCreeper.class, "titancreeper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanEnderman.class, "titanenderman", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanLlama.class, "titanllama", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanMagmacube.class, "titanmagmacube", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanPiglin.class, "titanpiglin", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanStray.class, "titanstray", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCourseRing.class, "coursering", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanVex.class, "titanvex", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanZombie.class, "titanzombie", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGloop.class, "gloop", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGloopMother.class, "gloopmother", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCyclos.class, "cyclos", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityClinger.class, "clinger", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantDimTrader.class, "deviantdimtrader", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMemPuzzleMerchant.class, "mempuzzlemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySkybooster.class, "skybooster", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRocketStrappedExplosive.class, "rocket_strapped_explosive", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMarkOfInfiniteDespair.class, "mark_of_despair", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySpectre.class, "spectre", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContestHologram.class, "contest_hologram", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderMarket.class, "contrader_market", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderHolodeck.class, "contrader_holodeck", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderHunters.class, "contrader_hunters", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderLightbridge.class, "contrader_lightbridge", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderTargets.class, "contrader_targets", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderParkour.class, "contrader_parkour", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderTrampolineDodgeball.class, "contrader_trampoline_dodgeball", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorHolodeck.class, "operator_holodeck", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorHunters.class, "operator_hunters", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorLightBridge.class, "operator_lightbridge", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorDuelArena.class, "operator_duelarena", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorTargets.class, "operator_targets", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorParkour.class, "operator_parkour", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorTrampolineDodgeball.class, "operator_trampoline_dodgeball", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerHolodeck.class, "controller_holodeck", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerHunters.class, "controller_hunters", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerTargets.class, "controller_targets", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerLightBridge.class, "controller_lightbridge", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerDuelArena.class, "controller_duel_arena", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerParkour.class, "controller_parkour", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerTrampolineDodgeball.class, "controller_trampoline_dodgeball", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityParticleTrojan.class, "particletrojan", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityPlasmaExplosion.class, "plasmaexplosion", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAzross.class, "azross", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDuskerQueen.class, "duskerqueen", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderRedlight.class, "contrader_redlight", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorRedlight.class, "operator_redlight", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerRedlight.class, "controller_redlight", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantWither.class, "deviant_wither", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityWitherSkullling.class, "wither_skullling", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGlangler.class, "glangler", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGlochipper.class, "glochipper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGloboon.class, "globoon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityEssenceDweller.class, "essencedweller", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityEssenceIdol.class, "essenceidol", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGlobro.class, "globro", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAugmenticon.class, "augmenticon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGalaxyGulper.class, "galaxygulper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLaserSpire.class, "laserspire", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGiantFlapper.class, "giantflapper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityIonExplosion.class, "ionexplosion", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNitroExplosion.class, "nitroexplosion", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantGolem.class, "deviantgolem", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityStickyBomb.class, "stickybomb", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityVectosect.class, "vectosect", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityStickler.class, "stickler", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityUnstableMerchant.class, "unstablemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFeralMerchant.class, "feralmerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantCaveSpider.class, "deviantcavespider", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTornIndividual.class, "tornindividual", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRavager.class, "ravager", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityVycellia.class, "vycellia", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityPuzzleMaster.class, "puzzlemaster", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNightshyre.class, "nightshyre", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGiantFyreweed.class, "giantfyreweed", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityBomberBomb.class, "bomberbomb", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySkycrab.class, "skycrab", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGlomite.class, "glomite", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTNTZombie.class, "tntzombie", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantBat.class, "deviantbat", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorBombers.class, "operator_bombers", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerBombers.class, "controller_bombers", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderBombers.class, "contrader_bombers", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorBattleSnakes.class, "operator_battle_snakes", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerBattleSnakes.class, "controller_battle_snakes", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderBattleSnakes.class, "contrader_battle_snakes", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorLaserTag.class, "operator_laser_tag", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerLaserTag.class, "controller_laser_tag", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderLaserTag.class, "contrader_laser_tag", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorInkBattle.class, "operator_ink_battle", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerInkBattle.class, "controller_ink_battle", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderInkBattle.class, "contrader_ink_battle", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOperatorTreadmill.class, "operator_treadmill", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityControllerTreadmill.class, "controller_treadmill", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityContraderTreadmill.class, "contrader_treadmill", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLightGame.class, "lightpuzzlemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRockslug.class, "rockslug", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGiantRockslug.class, "giant_rockslug", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityWhackGameMerchant.class, "whackgamemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFlutterbee.class, "flutterbee", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityConnectGameMerchant.class, "connectgamemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRhythmGameMerchant.class, "rhythmgamemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityPearlCollector.class, "pearlcollector", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOzor.class, "ozor", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOzorDecoy.class, "ozordecoy", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTotemMoon.class, "totemmoon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTotemPylon.class, "totempylon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityThundyron.class, "thundyron", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCryonus.class, "cryonus", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityThunderBomb.class, "thunderbomb", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityStormBomb.class, "stormbomb", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityPipeGameMerchant.class, "pipegamemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityZenon.class, "zenon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCrusher.class, "crusher", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDrippler.class, "drippler", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGorger.class, "gorger", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDoublejaw.class, "doublejaw", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMinimite.class, "minimite", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityClusterweed.class, "clusterweed", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityWisp.class, "wisp", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTetherbug.class, "tetherbug", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCellGameMerchant.class, "cellgamemerchant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityVilebulb.class, "vilebulb", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySightwalker.class, "sightwalker", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityWeaver.class, "weaver", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDoomDog.class, "doomdog", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityBlisterweed.class, "blisterweed", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGrubber.class, "grubber", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTitanopod.class, "titanopod", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySnapper.class, "snapper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityFlashfly.class, "flashfly", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantWitherSkeleton.class, "deviantwitherskeleton", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTerrorFly.class, "terrorfly", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTentaclon.class, "tentaclon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGalacticTerror.class, "galacticterror", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantGuardian.class, "deviantguardian", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityForbiddenBrand.class, "forbiddenbrand", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityPickleMan.class, "pickleman", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMortarCannon.class, "mortarcannon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityClusterCannon.class, "clustercannon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantOcelote.class, "deviantocelote", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLivorax.class, "livorax", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLurcher.class, "lurcher", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNat.class, "nat", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySentry.class, "sentry", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCaveTerror.class, "caveterror", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityWhisper.class, "whisper", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTorpedon.class, "torpedon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRift.class, "rift", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOrbiter.class, "orbiter", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTotemSplitter.class, "totemsplitter", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityTentacleTrap.class, "tentacletrap", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityScorpwing.class, "scorpwing", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDoomsday.class, "doomsday", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySkyre.class, "skyre", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRockworm.class, "rockworm", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityKalikos.class, "kalikos", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGhostCopy.class, "ghostcopy", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLeer.class, "leer", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDoublerang.class, "doublerang", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLongfin.class, "longfin", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityOctobrella.class, "octobrella", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRayfish.class, "rayfish", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGlowfish.class, "glowfish", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantSquid.class, "deviantsquid", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityUnderfin.class, "underfin", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityEelShark.class, "eelshark", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCrabulon.class, "crabulon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRibshark.class, "ribshark", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityScreamer.class, "screamer", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNebulaGrunt.class, "nebula_grunt", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNebulaWizard.class, "nebula_wizard", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNebulaGiant.class, "nebula_giant", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityArcheologist.class, "archeologist", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMultiverseGhost.class, "multiverseghost", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityRisingPhantom.class, "risingphantom", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAbyssalCrabulon.class, "tentaclelantern", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLeviathanController.class, "leviathan", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySeaSerpentController.class, "sea_serpent", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityGalaxyDragon.class, "galaxy_dragon", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityXScreacher.class, "x_screacher", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityLostBlade.class, "lost_blade", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityNuclearExplosion.class, "nuclear_explosion", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMushmerra.class, "mushmerra", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityMushmerraClone.class, "mushmerra_clone", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityShroomite.class, "shroomite", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityAuraOfAllegiance.class, "aura_of_allegiance", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntitySupplyTrader.class, "supply_trader", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityJetMount.class, "jet_mount", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantWolf.class, "deviant_wolf", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityDeviantHusk.class, "deviant_husk", 91102, 0x4B4B4B), EntityInit.doEntityEntry(EntityAndromedaController.class, "andromeda", 91102, 0x4B4B4B, true, 512), EntityInit.customEntityEntry(EntityBombDrone.class, "bomb_drone", 91102, 0x4B4B4B), EntityInit.customEntityEntry(PlayerLimb.class, "player_limb", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCthulhu.class, "cthulhu", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCthulhuTurret.class, "cthulhu_turret", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCthulhuCloud.class, "cthulhu_cloud", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCthulhuTentacle.class, "cthulhu_tentacle", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCthulhuTentaclePersist.class, "cthulhu_tentacle_persist", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCthulhuBeam.class, "cthulhu_beam", 91102, 0x4B4B4B), EntityInit.egglessEntry(EntityCthulhuBlackHole.class, "cthulhu_black_hole", 91102, 0x4B4B4B), EntityInit.egglessEntry(EntityCthulhuRift.class, "cthulhu_rift", 91102, 0x4B4B4B), EntityInit.egglessEntry(EntityCthulhuHealingOrb.class, "cthulhu_healing_orb", 91102, 0x4B4B4B), EntityInit.customEntityEntry(EntityCelestialStatue.class, "celestial_statue", 91102, 0x4B4B4B), EntityInit.egglessEntry(EntityCthulhuDeathFX.class, "cthulhu_death_fx", 91102, 0x4B4B4B)};
    }

    public static EntityEntry[] projectileEntries() {
        return new EntityEntry[]{EntityInit.customProjectileEntry(EntityElaraShot.class, "elarashot"), EntityInit.customProjectileEntry(EntitySkullShot.class, "skullshot"), EntityInit.customProjectileEntry(EntityDoomShot.class, "doomshot"), EntityInit.customProjectileEntry(EntityRainDrop.class, "raindrop"), EntityInit.customProjectileEntry(EntityAcidRainDrop.class, "acidraindrop"), EntityInit.customProjectileEntry(EntityDroidBall.class, "droidball"), EntityInit.customProjectileEntry(EntityDroidZapper.class, "droidzapper"), EntityInit.customProjectileEntry(EntityDroidSucker.class, "droidsucker"), EntityInit.customProjectileEntry(EntityDeviantShulkerBullet.class, "deviantshulkerbullet"), EntityInit.customProjectileEntry(EntityLivoraxBullet.class, "livoraxbullet"), EntityInit.customProjectileEntry(EntityWizardBlast.class, "wizardblast"), EntityInit.customProjectileEntry(EntityVeloMagic.class, "velomagic"), EntityInit.customProjectileEntry(EntityFluxBall.class, "fluxball"), EntityInit.customProjectileEntry(EntityGalaxyBlast.class, "galaxyblast"), EntityInit.customProjectileEntry(EntityGalaxySpell.class, "galaxyspell"), EntityInit.customProjectileEntry(EntityGalaxyBomb.class, "galaxybomb"), EntityInit.customProjectileEntry(EntityGalaxyKnife.class, "galaxyknife"), EntityInit.customProjectileEntry(EntityDeviantSucker.class, "deviantsucker"), EntityInit.customProjectileEntry(EntityDeviantDeployer.class, "deviantdeployer"), EntityInit.customProjectileEntry(EntityWitchMagic.class, "witchmagic"), EntityInit.customProjectileEntry(EntityCrystalGellball.class, "crystalgellball"), EntityInit.customProjectileEntry(EntityCarrierProjectile.class, "carrierprojectile"), EntityInit.customProjectileEntry(EntityFallingStar.class, "fallingstar"), EntityInit.customProjectileEntry(EntityWandAttack.class, "wandattack"), EntityInit.customProjectileEntry(EntityRockshot.class, "rockshot"), EntityInit.customProjectileEntry(EntitySonicAttack.class, "sonicattack"), EntityInit.customProjectileEntry(EntityXSonicAttack.class, "x_sonicattack"), EntityInit.customProjectileEntry(EntityDeviantSnowball.class, "deviantsnowball"), EntityInit.customProjectileEntry(EntityCelestialFire.class, "celestialfire"), EntityInit.customProjectileEntry(EntityZenonShot.class, "zenonshot"), EntityInit.customProjectileEntry(EntityLaserGunBeam.class, "lasergunbeam"), EntityInit.customProjectileEntry(EntityLuminousGuardianLaser.class, "luminousguardianlaser"), EntityInit.customProjectileEntry(EntityStunAttack.class, "stunattack"), EntityInit.customProjectileEntry(EntityDarkSpell.class, "darkspell"), EntityInit.customProjectileEntry(EntityCrystalShard.class, "crystalshard"), EntityInit.customProjectileEntry(EntityExplosiveGoo.class, "explosivegoo"), EntityInit.customProjectileEntry(EntityDestabilizer.class, "destabilizer"), EntityInit.customProjectileEntry(EntityComet.class, "comet"), EntityInit.customProjectileEntry(MonsterComet.class, "mobcomet"), EntityInit.customProjectileEntry(EntityBlightedComet.class, "blightedcomet"), EntityInit.customProjectileEntry(EntityTentacleSeed.class, "tentacleseed"), EntityInit.customProjectileEntry(EntityHomingBlight.class, "homingblight"), EntityInit.customProjectileEntry(EntityAtlasAttack.class, "atlasattack"), EntityInit.customProjectileEntry(EntityDeviantSpit.class, "deviantspit"), EntityInit.customProjectileEntry(EntityVoidLaser.class, "voidlaser"), EntityInit.customProjectileEntry(EntitySkyStrike.class, "skystrike"), EntityInit.customProjectileEntry(EntityVenomBlast.class, "venomblast"), EntityInit.customProjectileEntry(EntityProjectileKiller.class, "projectilekiller"), EntityInit.customProjectileEntry(EntityBloodhunterBlast.class, "bloodhunterblast"), EntityInit.customProjectileEntry(EntityPowerPulse.class, "powerpulse"), EntityInit.customProjectileEntry(EntityGravityWarper.class, "gravitywarp"), EntityInit.customProjectileEntry(EntityWitherBomb.class, "witherbomb"), EntityInit.customProjectileEntry(EntityDeviantEvokerFangs.class, "deviantfang"), EntityInit.customProjectileEntry(EntityDeviantEvokerShot.class, "deviantevokershot"), EntityInit.customProjectileEntry(EntityDeviantEvokerBomb.class, "deviantevokerbomb"), EntityInit.customProjectileEntry(EntityElementiumWater.class, "elementiumwater"), EntityInit.customProjectileEntry(EntityElementiumAir.class, "elementiumair"), EntityInit.customProjectileEntry(EntityElementiumFire.class, "elementiumfire"), EntityInit.customProjectileEntry(EntityElementiumEarth.class, "elementiumearth"), EntityInit.customProjectileEntry(EntityDroidLaser.class, "droidlaser"), EntityInit.customProjectileEntry(EntityGalaxyLaser.class, "galaxylaser"), EntityInit.customProjectileEntry(EntityDuskerQueenWeb.class, "duskerqueenweb"), EntityInit.customProjectileEntry(EntityPlagueBlast.class, "plagueblast"), EntityInit.customProjectileEntry(EntityGenericBomb.class, "genericbomb"), EntityInit.customProjectileEntry(EntityStickyProjectile.class, "stickyprojectile"), EntityInit.customProjectileEntry(EntityFractureBomb.class, "fracturebomb"), EntityInit.customProjectileEntry(EntityUltraCrystalGel.class, "ultracrystalgel"), EntityInit.customProjectileEntry(EntityRecursor.class, "recursor"), EntityInit.customProjectileEntry(EntityInkBomb.class, "ink_bomb"), EntityInit.customProjectileEntry(EntityInkShot.class, "ink_shot"), EntityInit.customProjectileEntry(EntityEidolonMist.class, "eidolonmist"), EntityInit.customProjectileEntry(EntityWormholeShot.class, "wormholeshot"), EntityInit.customProjectileEntry(EntityWormholePortal.class, "wormholeportal"), EntityInit.customProjectileEntry(EntityIonicChakram.class, "ionicchakram"), EntityInit.customProjectileEntry(EntityMiniChakram.class, "minichakram"), EntityInit.customProjectileEntry(EntityInfinityTrident.class, "trident"), EntityInit.customProjectileEntry(EntityInfinityTridentMK2.class, "tridentmk2"), EntityInit.customProjectileEntry(EntityTitanRing.class, "titanring"), EntityInit.customProjectileEntry(EntityChampionDodgeball.class, "dodgeball"), EntityInit.customProjectileEntry(EntityAstralShot.class, "astralshot"), EntityInit.customProjectileEntry(EntitySpiderBlast.class, "spiderblast"), EntityInit.customProjectileEntry(EntityBarulChain.class, "barulchain"), EntityInit.customProjectileEntry(EntityTormentorChain.class, "tormentorchain"), EntityInit.customProjectileEntry(EntityGloomSpell.class, "gloomspell"), EntityInit.customProjectileEntry(EntityEchoBlast.class, "echoblast"), EntityInit.customProjectileEntry(EntityTNTStrapper.class, "tntstrapper"), EntityInit.customProjectileEntry(EntityElementiumShadow.class, "elementiumshadow"), EntityInit.customProjectileEntry(EntityElementiumBlight.class, "elementiumblight"), EntityInit.customProjectileEntry(EntityElementiumPlague.class, "elementiumplague"), EntityInit.customProjectileEntry(EntityUnstableBalloon.class, "unstableballoon"), EntityInit.customProjectileEntry(EntitySkycrabAttack.class, "skycrabattack"), EntityInit.customProjectileEntry(EntityCellularRock.class, "cellularrock"), EntityInit.customProjectileEntry(EntitySunstoneRock.class, "sunstonerock"), EntityInit.customProjectileEntry(EntityBeeAttack.class, "beeattack"), EntityInit.customProjectileEntry(EntityPiercingShot.class, "piercingshot"), EntityInit.customProjectileEntry(EntityMortarShot.class, "mortarshot"), EntityInit.customProjectileEntry(EntitySpikeBall.class, "spikeball"), EntityInit.customProjectileEntry(EntityExothermite.class, "exothermite"), EntityInit.customProjectileEntry(EntityBallOfContainedQuarks.class, "ballofquarks"), EntityInit.customProjectileEntry(EntityBallOfContainedGluons.class, "ballofgluons"), EntityInit.customProjectileEntry(EntityAcidicConcoction.class, "acidicconcoction"), EntityInit.customProjectileEntry(EntityPoisonousBubble.class, "poisonousbubble"), EntityInit.customProjectileEntry(EntityLaserBlast.class, "laserblast"), EntityInit.customProjectileEntry(EntitySelectionLaser.class, "selectionlaser"), EntityInit.customProjectileEntry(EntityDryadsGripAttack.class, "dryadsgrip"), EntityInit.customProjectileEntry(EntityFirePellet.class, "firepellet"), EntityInit.customProjectileEntry(EntityFountainPellet.class, "fountainpellet"), EntityInit.customProjectileEntry(EntityTetherBall.class, "tetherball"), EntityInit.customProjectileEntry(EntityClusterBlast.class, "clusterblast"), EntityInit.customProjectileEntry(EntityChainOfVenomsAttack.class, "venomchain"), EntityInit.customProjectileEntry(EntityPlasmaSlicer.class, "plasmaslicer"), EntityInit.customProjectileEntry(EntityAvengerLightning.class, "avengerlightning"), EntityInit.customProjectileEntry(EntityVoltaicIonizerAttack.class, "voltaicionizer"), EntityInit.customProjectileEntry(EntitySelectorAttack.class, "selector"), EntityInit.customProjectileEntry(EntityDebtCollectorEffect.class, "debtcollector"), EntityInit.customProjectileEntry(EntityPortalEffect.class, "portaleffect"), EntityInit.customProjectileEntry(EntityScreamerPortalEffect.class, "screamerportaleffect"), EntityInit.customProjectileEntry(EntityBossPortalEffect.class, "bossportaleffect"), EntityInit.customProjectileEntry(EntityPicklePortal.class, "pickleportal"), EntityInit.customProjectileEntry(EntityEffigyShot.class, "effigyshot"), EntityInit.customProjectileEntry(EntityEffigyEffect.class, "effigyeffect"), EntityInit.customProjectileEntry(EntityCryoBeamEffect.class, "cryobeam"), EntityInit.customProjectileEntry(EntityCryoBolt.class, "cryobolt"), EntityInit.customProjectileEntry(EntityFearBomb.class, "fearbomb"), EntityInit.customProjectileEntry(EntityBlightPellet.class, "blightpellet"), EntityInit.customProjectileEntry(EntityEchoOfGravity.class, "gravityecho"), EntityInit.customProjectileEntry(EntityArcBlast.class, "arcblast"), EntityInit.customProjectileEntry(EntityTekBullet.class, "tekbullet"), EntityInit.customProjectileEntry(EntityLaunchedKnife.class, "launchedknife"), EntityInit.customProjectileEntry(EntityElementiumPrime.class, "elementiumprime"), EntityInit.customProjectileEntry(EntityStrappedFirework.class, "strappedfirework"), EntityInit.customProjectileEntry(EntityPlasmaBomb.class, "plasma_bomb"), EntityInit.customProjectileEntry(EntityDoomBlast.class, "doomblast"), EntityInit.customProjectileEntry(EntityUnstableRift.class, "unstablerift"), EntityInit.customProjectileEntry(EntityEnergyBurst.class, "energyburst"), EntityInit.customProjectileEntry(EntityBlightBomb.class, "blightbomb"), EntityInit.customProjectileEntry(EntityScreamerBlast.class, "screamerblast"), EntityInit.customProjectileEntry(EntityAsteroid.class, "asteroid"), EntityInit.customProjectileEntry(EntityNebulaSpell.class, "nebulaspell"), EntityInit.customProjectileEntry(EntityMeteor.class, "meteor"), EntityInit.customProjectileEntry(EntityStarBlast.class, "starblast"), EntityInit.customProjectileEntry(EntityMicroRocket.class, "micro_rocket"), EntityInit.customProjectileEntry(EntityAvenger.class, "avenger"), EntityInit.customProjectileEntry(EntitySoundwaveBullet.class, "soundwave_bullet"), EntityInit.customProjectileEntry(EntityPuzzleMasterArrow.class, "puzzle_arrow"), EntityInit.customProjectileEntry(EntityLeviathanTracer.class, "leviathan_tracer"), EntityInit.customProjectileEntry(EntityLeviathanTeslaOrb.class, "leviathan_tesla_orb"), EntityInit.customProjectileEntry(EntityLeviathanBreath.class, "leviathan_breath"), EntityInit.customProjectileEntry(EntityGalaxyDragonFireball.class, "cosmic_fireball"), EntityInit.customProjectileEntry(EntityWhirlpool.class, "whirlpool"), EntityInit.customProjectileEntry(EntityCrabulonProjectile.class, "crabulon_projectile"), EntityInit.customProjectileEntry(EntityDeathShot.class, "death_shot"), EntityInit.customProjectileEntry(EntityEmberShot.class, "ember_shot"), EntityInit.customProjectileEntry(EntityCreepingVineArrow.class, "creeping_vine_arrow"), EntityInit.customProjectileEntry(EntityCreepingVinePod.class, "creeping_vine_pod"), EntityInit.customProjectileEntry(EntityAndromedaChaser.class, "andromeda_chaser"), EntityInit.customProjectileEntry(EntityCthulhuTurretBullet.class, "cthulhu_turret_bullet"), EntityInit.customProjectileEntry(EntityCthulhuMissile.class, "cthulhu_missile"), EntityInit.customProjectileEntry(EntityCthulhuMeteor.class, "cthulhu_meteor"), EntityInit.customProjectileEntry(EntityCthulhuSpear.class, "cthulhu_spear")};
    }

    public static void tileEntityRegister() {
        GameRegistry.registerBlockEntity(BlockEntityGenerator.class, (ResourceLocation)new ResourceLocation("lostinfinity", "shockwavegen"));
        GameRegistry.registerBlockEntity(BlockEntityCompressionTable.class, (ResourceLocation)new ResourceLocation("lostinfinity", "compression_table"));
        GameRegistry.registerBlockEntity(BlockEntitySapEvaporator.class, (ResourceLocation)new ResourceLocation("lostinfinity", "sap_evaporator"));
        GameRegistry.registerBlockEntity(BlockEntityNicroniumInfuser.class, (ResourceLocation)new ResourceLocation("lostinfinity", "nicronium_infuser"));
        GameRegistry.registerBlockEntity(BlockEntityLightEmitter.class, (ResourceLocation)new ResourceLocation("lostinfinity", "light_emitter"));
        GameRegistry.registerBlockEntity(BlockEntityPortalNode.class, (ResourceLocation)new ResourceLocation("lostinfinity", "portal_node"));
        GameRegistry.registerBlockEntity(BlockEntityPortalNexus.class, (ResourceLocation)new ResourceLocation("lostinfinity", "portal_nexus"));
        GameRegistry.registerBlockEntity(BlockEntityChromaGame.class, (ResourceLocation)new ResourceLocation("lostinfinity", "chroma_game"));
        GameRegistry.registerBlockEntity(BlockEntityAlignmentDialGame.class, (ResourceLocation)new ResourceLocation("lostinfinity", "alignment_dial_game"));
        GameRegistry.registerBlockEntity(BlockEntityVoidVacuum.class, (ResourceLocation)new ResourceLocation("lostinfinity", "void_vacuum"));
        GameRegistry.registerBlockEntity(BlockEntityRemoteControl.class, (ResourceLocation)new ResourceLocation("lostinfinity", "remote_control"));
        GameRegistry.registerBlockEntity(BlockEntityAncientSymbolInterpreter.class, (ResourceLocation)new ResourceLocation("lostinfinity", "symbol_interpreter"));
        GameRegistry.registerBlockEntity(BlockEntityPowerConduit.class, (ResourceLocation)new ResourceLocation("lostinfinity", "crossing_game"));
        GameRegistry.registerBlockEntity(BlockEntityPowerCollider.class, (ResourceLocation)new ResourceLocation("lostinfinity", "power_collider"));
        GameRegistry.registerBlockEntity(BlockEntityRainfallGenerator.class, (ResourceLocation)new ResourceLocation("lostinfinity", "rain_generator"));
        GameRegistry.registerBlockEntity(BlockEntityWeldingChamber.class, (ResourceLocation)new ResourceLocation("lostinfinity", "welding_chamber"));
        GameRegistry.registerBlockEntity(BlockEntityFusionTable.class, (ResourceLocation)new ResourceLocation("lostinfinity", "fusion_table"));
        GameRegistry.registerBlockEntity(BlockEntityPolymerizationDevice.class, (ResourceLocation)new ResourceLocation("lostinfinity", "polymerization"));
        GameRegistry.registerBlockEntity(BlockEntityNebulousBeacon.class, (ResourceLocation)new ResourceLocation("lostinfinity", "nebulous_beacon"));
        GameRegistry.registerBlockEntity(BlockEntityMelodicSequencer.class, (ResourceLocation)new ResourceLocation("lostinfinity", "melodicsequencer"));
        GameRegistry.registerBlockEntity(BlockEntityCircuitCalibrator.class, (ResourceLocation)new ResourceLocation("lostinfinity", "circuitcalibrator"));
        GameRegistry.registerBlockEntity(BlockEntityNavigationDevice.class, (ResourceLocation)new ResourceLocation("lostinfinity", "navigationdevice"));
        GameRegistry.registerBlockEntity(BlockEntityChemistryTable.class, (ResourceLocation)new ResourceLocation("lostinfinity", "chemistry_table"));
        GameRegistry.registerBlockEntity(BlockEntityTeslaTower.class, (ResourceLocation)new ResourceLocation("lostinfinity", "tesla_tower"));
        GameRegistry.registerBlockEntity(BlockEntityEternalBeacon.class, (ResourceLocation)new ResourceLocation("lostinfinity", "eternal_beacon"));
        GameRegistry.registerBlockEntity(BlockEntityShipmentFiller.class, (ResourceLocation)new ResourceLocation("lostinfinity", "shipment_filler"));
        GameRegistry.registerBlockEntity(BlockEntityDrillConsole.class, (ResourceLocation)new ResourceLocation("lostinfinity", "drill_console"));
        GameRegistry.registerBlockEntity(BlockEntityCthulhuSpawner.class, (ResourceLocation)new ResourceLocation("lostinfinity", "cthulhu_spawner"));
        GameRegistry.registerBlockEntity(BlockEntityGearbox.class, (ResourceLocation)new ResourceLocation("lostinfinity", "gearbox"));
        GameRegistry.registerBlockEntity(BlockEntityCombustionEngine.class, (ResourceLocation)new ResourceLocation("lostinfinity", "combustion_engine"));
        GameRegistry.registerBlockEntity(BlockEntityGrinder.class, (ResourceLocation)new ResourceLocation("lostinfinity", "grinder"));
        GameRegistry.registerBlockEntity(BlockEntityKillerVine.class, (ResourceLocation)new ResourceLocation("lostinfinity", "killer_vine"));
    }
}

