/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.Minecraft
 *  net.minecraft.client.particle.IParticleFactory
 *  net.minecraft.client.renderer.texture.TextureAtlasSprite
 *  net.minecraft.util.EnumParticleTypes
 *  net.minecraft.util.ResourceLocation
 *  net.minecraftforge.client.event.TextureStitchEvent$Pre
 *  net.minecraftforge.common.util.EnumHelper
 *  net.minecraftforge.fml.common.eventhandler.SubscribeEvent
 *  net.minecraftforge.fml.relauncher.Side
 *  net.minecraftforge.fml.relauncher.SideOnly
 */
package xol.lostinfinity.init;

import net.minecraft.client.Minecraft;
import net.minecraft.client.particle.IParticleFactory;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.util.EnumParticleTypes;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.client.event.TextureStitchEvent;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import xol.lostinfinity.client.fx.ParticleAcid;
import xol.lostinfinity.client.fx.ParticleAcidYellow;
import xol.lostinfinity.client.fx.ParticleAncientSpell;
import xol.lostinfinity.client.fx.ParticleAttractField;
import xol.lostinfinity.client.fx.ParticleBadMagic;
import xol.lostinfinity.client.fx.ParticleBasicStarType1;
import xol.lostinfinity.client.fx.ParticleBasicStarType2;
import xol.lostinfinity.client.fx.ParticleBasicStarType3;
import xol.lostinfinity.client.fx.ParticleBasicStarType4;
import xol.lostinfinity.client.fx.ParticleBlightSpellGreen;
import xol.lostinfinity.client.fx.ParticleBlightSpellPink;
import xol.lostinfinity.client.fx.ParticleBloodDrop;
import xol.lostinfinity.client.fx.ParticleBlueSkull;
import xol.lostinfinity.client.fx.ParticleBomberExplosion;
import xol.lostinfinity.client.fx.ParticleClawMarks;
import xol.lostinfinity.client.fx.ParticleClayBlock;
import xol.lostinfinity.client.fx.ParticleClayBubble;
import xol.lostinfinity.client.fx.ParticleCloudGreen;
import xol.lostinfinity.client.fx.ParticleCloudPurple;
import xol.lostinfinity.client.fx.ParticleCometBlue;
import xol.lostinfinity.client.fx.ParticleCometWhite;
import xol.lostinfinity.client.fx.ParticleCorruptionMagic;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType1;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType2;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType3;
import xol.lostinfinity.client.fx.ParticleCosmicExplosionType4;
import xol.lostinfinity.client.fx.ParticleCrescentMoon;
import xol.lostinfinity.client.fx.ParticleCrystalMagic;
import xol.lostinfinity.client.fx.ParticleDarkFizzle;
import xol.lostinfinity.client.fx.ParticleDarkFlash;
import xol.lostinfinity.client.fx.ParticleDarkMagic;
import xol.lostinfinity.client.fx.ParticleDragonFire;
import xol.lostinfinity.client.fx.ParticleElectricExplosionBlue;
import xol.lostinfinity.client.fx.ParticleElectricExplosionYellow;
import xol.lostinfinity.client.fx.ParticleExplosion;
import xol.lostinfinity.client.fx.ParticleExplosionBlue;
import xol.lostinfinity.client.fx.ParticleExplosionFear;
import xol.lostinfinity.client.fx.ParticleExplosionLavender;
import xol.lostinfinity.client.fx.ParticleExplosionOrange;
import xol.lostinfinity.client.fx.ParticleExplosionRed;
import xol.lostinfinity.client.fx.ParticleExplosionRing;
import xol.lostinfinity.client.fx.ParticleExplosionRingDark;
import xol.lostinfinity.client.fx.ParticleExplosionTeal;
import xol.lostinfinity.client.fx.ParticleExplosionYellow;
import xol.lostinfinity.client.fx.ParticleFiregoo;
import xol.lostinfinity.client.fx.ParticleFlameLarge;
import xol.lostinfinity.client.fx.ParticleFlameMedium;
import xol.lostinfinity.client.fx.ParticleFlameSmall;
import xol.lostinfinity.client.fx.ParticleGalaxyBlue;
import xol.lostinfinity.client.fx.ParticleGalaxyGreen;
import xol.lostinfinity.client.fx.ParticleGalaxyPurple;
import xol.lostinfinity.client.fx.ParticleGalaxyYellow;
import xol.lostinfinity.client.fx.ParticleGenericDotAcid;
import xol.lostinfinity.client.fx.ParticleGenericDotAqua;
import xol.lostinfinity.client.fx.ParticleGenericDotBlack;
import xol.lostinfinity.client.fx.ParticleGenericDotBlue;
import xol.lostinfinity.client.fx.ParticleGenericDotGreen;
import xol.lostinfinity.client.fx.ParticleGenericDotOrange;
import xol.lostinfinity.client.fx.ParticleGenericDotPink;
import xol.lostinfinity.client.fx.ParticleGenericDotPurple;
import xol.lostinfinity.client.fx.ParticleGenericDotRed;
import xol.lostinfinity.client.fx.ParticleGenericDotTangerine;
import xol.lostinfinity.client.fx.ParticleGenericDotWhite;
import xol.lostinfinity.client.fx.ParticleGenericDotYellow;
import xol.lostinfinity.client.fx.ParticleGlomiteWarp;
import xol.lostinfinity.client.fx.ParticleGloomBurst;
import xol.lostinfinity.client.fx.ParticleGloomSpell;
import xol.lostinfinity.client.fx.ParticleGoldStar;
import xol.lostinfinity.client.fx.ParticleGoldenMagic;
import xol.lostinfinity.client.fx.ParticleGooRing;
import xol.lostinfinity.client.fx.ParticleGrasp;
import xol.lostinfinity.client.fx.ParticleGravityRing;
import xol.lostinfinity.client.fx.ParticleHoneyBubble;
import xol.lostinfinity.client.fx.ParticleIonBlast;
import xol.lostinfinity.client.fx.ParticleIonFuel;
import xol.lostinfinity.client.fx.ParticleLargeBubble;
import xol.lostinfinity.client.fx.ParticleLargeBubblePurple;
import xol.lostinfinity.client.fx.ParticleLaserFizzle;
import xol.lostinfinity.client.fx.ParticleLaserFizzleLarge;
import xol.lostinfinity.client.fx.ParticleLightFizzle;
import xol.lostinfinity.client.fx.ParticleLightFlash;
import xol.lostinfinity.client.fx.ParticleLightningIndicator;
import xol.lostinfinity.client.fx.ParticleMiasma;
import xol.lostinfinity.client.fx.ParticleMurk;
import xol.lostinfinity.client.fx.ParticleMurkyMist;
import xol.lostinfinity.client.fx.ParticleNatureDot;
import xol.lostinfinity.client.fx.ParticleNatureMagic;
import xol.lostinfinity.client.fx.ParticleNatureRing;
import xol.lostinfinity.client.fx.ParticleNightmareMagic;
import xol.lostinfinity.client.fx.ParticleNuclearBlast;
import xol.lostinfinity.client.fx.ParticlePlague;
import xol.lostinfinity.client.fx.ParticlePlasma;
import xol.lostinfinity.client.fx.ParticlePlasmaExplosion;
import xol.lostinfinity.client.fx.ParticlePlasmaRift;
import xol.lostinfinity.client.fx.ParticlePoisonBubble;
import xol.lostinfinity.client.fx.ParticlePoisonExplosion;
import xol.lostinfinity.client.fx.ParticlePoisonRings;
import xol.lostinfinity.client.fx.ParticlePowerField;
import xol.lostinfinity.client.fx.ParticlePowerLoss;
import xol.lostinfinity.client.fx.ParticlePowerPulse;
import xol.lostinfinity.client.fx.ParticlePrismaticExplosionType1;
import xol.lostinfinity.client.fx.ParticlePrismaticExplosionType2;
import xol.lostinfinity.client.fx.ParticlePrismaticExplosionType3;
import xol.lostinfinity.client.fx.ParticlePurpleSkull;
import xol.lostinfinity.client.fx.ParticleQuantumMark;
import xol.lostinfinity.client.fx.ParticleRedSkull;
import xol.lostinfinity.client.fx.ParticleRepelField;
import xol.lostinfinity.client.fx.ParticleShadowBlast;
import xol.lostinfinity.client.fx.ParticleSlam;
import xol.lostinfinity.client.fx.ParticleSmallSpark;
import xol.lostinfinity.client.fx.ParticleSnowBubble;
import xol.lostinfinity.client.fx.ParticleSpaceMagic;
import xol.lostinfinity.client.fx.ParticleSpectral;
import xol.lostinfinity.client.fx.ParticleStationaryBubble;
import xol.lostinfinity.client.fx.ParticleSupersonicBlue;
import xol.lostinfinity.client.fx.ParticleSupersonicRed;
import xol.lostinfinity.client.fx.ParticleTeslaRingBlue;
import xol.lostinfinity.client.fx.ParticleTeslaRingYellow;
import xol.lostinfinity.client.fx.ParticleVenom;
import xol.lostinfinity.client.fx.ParticleVenomChain;
import xol.lostinfinity.client.fx.ParticleVenomRing;
import xol.lostinfinity.client.fx.ParticleWarp;
import xol.lostinfinity.client.fx.ParticleWatchingEye;
import xol.lostinfinity.client.fx.ParticleWebMagic;
import xol.lostinfinity.client.fx.ParticleWitherRings;
import xol.lostinfinity.client.fx.ParticleZap;

public class ParticleInit {
    public static TextureAtlasSprite GALAXY_YELLOW_SPRITE;
    public static TextureAtlasSprite GALAXY_BLUE_SPRITE;
    public static TextureAtlasSprite GALAXY_GREEN_SPRITE;
    public static TextureAtlasSprite GALAXY_PURPLE_SPRITE;
    public static TextureAtlasSprite HONEY_BUBBLE_SPRITE;
    public static TextureAtlasSprite POWER_LOSS_SPRITE;
    public static TextureAtlasSprite ANCIENT_SPELL_SPRITE;
    public static TextureAtlasSprite CLAW_MARKS_SPRITE;
    public static TextureAtlasSprite ELECTRIC_EXPLOSION_YELLOW_SPRITE;
    public static TextureAtlasSprite ELECTRIC_EXPLOSION_BLUE_SPRITE;
    public static TextureAtlasSprite CORRUPTION_MAGIC_SPRITE;
    public static TextureAtlasSprite NATURE_RING_SPRITE;
    public static TextureAtlasSprite NATURE_MAGIC_SPRITE;
    public static TextureAtlasSprite CRYSTAL_MAGIC_SPRITE;
    public static TextureAtlasSprite SHADOW_BLAST_SPRITE;
    public static TextureAtlasSprite GOLD_STAR_SPRITE;
    public static TextureAtlasSprite DARK_FIZZLE_SPRITE;
    public static TextureAtlasSprite POISON_BUBBLE_SPRITE;
    public static TextureAtlasSprite PURPLE_SKULL_SPRITE;
    public static TextureAtlasSprite BLIGHT_SPELL_PINK_SPRITE;
    public static TextureAtlasSprite BLIGHT_SPELL_GREEN_SPRITE;
    public static TextureAtlasSprite SNOW_BUBBLE_SPRITE;
    public static TextureAtlasSprite BLUE_SKULL_SPRITE;
    public static TextureAtlasSprite MURK_SPRITE;
    public static TextureAtlasSprite NIGHTMARE_MAGIC_SPRITE;
    public static TextureAtlasSprite PLASMA_RIFT_SPRITE;
    public static TextureAtlasSprite PLASMA_SPRITE;
    public static TextureAtlasSprite SPECTRAL_SPRITE;
    public static TextureAtlasSprite PRISMATIC_EXPLOSION_TYPE1_SPRITE;
    public static TextureAtlasSprite PRISMATIC_EXPLOSION_TYPE2_SPRITE;
    public static TextureAtlasSprite PRISMATIC_EXPLOSION_TYPE3_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_YELLOW_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_ORANGE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_TANGERINE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_RED_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_PINK_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_PURPLE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_BLUE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_AQUA_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_GREEN_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_ACID_SPRITE;
    public static TextureAtlasSprite EXPLOSION_RING_DARK_SPRITE;
    public static TextureAtlasSprite EXPLOSION_BLUE_SPRITE;
    public static TextureAtlasSprite EXPLOSION_TEAL_SPRITE;
    public static TextureAtlasSprite EXPLOSION_LAVENDER_SPRITE;
    public static TextureAtlasSprite GOLDEN_MAGIC_SPRITE;
    public static TextureAtlasSprite BLOOD_DROP_SPRITE;
    public static TextureAtlasSprite NATURE_DOT_SPRITE;
    public static TextureAtlasSprite SMALL_SPARK_SPRITE;
    public static TextureAtlasSprite ACID_YELLOW_SPRITE;
    public static TextureAtlasSprite POISON_EXPLOSION_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE1_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE2_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE3_SPRITE;
    public static TextureAtlasSprite COSMIC_EXPLOSION_TYPE4_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE1_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE2_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE3_SPRITE;
    public static TextureAtlasSprite BASIC_STAR_TYPE4_SPRITE;
    public static TextureAtlasSprite LARGE_BUBBLE_SPRITE;
    public static TextureAtlasSprite LARGE_BUBBLE_PURPLE_SPRITE;
    public static TextureAtlasSprite MIASMA_SPRITE;
    public static TextureAtlasSprite SUPERSONIC_BLUE_SPRITE;
    public static TextureAtlasSprite SUPERSONIC_RED_SPRITE;
    public static TextureAtlasSprite EXPLOSION_RED_SPRITE;
    public static TextureAtlasSprite EXPLOSION_ORANGE_SPRITE;
    public static TextureAtlasSprite GRASP_SPRITE;
    public static TextureAtlasSprite BAD_MAGIC_SPRITE;
    public static TextureAtlasSprite CLAY_BUBBLE_SPRITE;
    public static TextureAtlasSprite CLAY_BLOCK_SPRITE;
    public static TextureAtlasSprite WATCHING_EYE_SPRITE;
    public static TextureAtlasSprite TESLA_RING_YELLOW_SPRITE;
    public static TextureAtlasSprite TESLA_RING_BLUE_SPRITE;
    public static TextureAtlasSprite ION_FUEL_SPRITE;
    public static TextureAtlasSprite EXPLOSION_YELLOW_SPRITE;
    public static TextureAtlasSprite DRAGON_FIRE_SPRITE;
    public static TextureAtlasSprite EXPLOSION_FEAR_SPRITE;
    public static TextureAtlasSprite STATIONARY_BUBBLE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_WHITE_SPRITE;
    public static TextureAtlasSprite GENERIC_DOT_BLACK_SPRITE;
    public static TextureAtlasSprite MURKY_MIST_SPRITE;
    public static TextureAtlasSprite LIGHT_FIZZLE_SPRITE;
    public static TextureAtlasSprite RED_SKULL_SPRITE;
    public static TextureAtlasSprite CLOUD_GREEN_SPRITE;
    public static TextureAtlasSprite CLOUD_PURPLE_SPRITE;
    public static TextureAtlasSprite LIGHTNING_INDICATOR_SPRITE;
    public static TextureAtlasSprite FIREGOO_SPRITE;
    public static TextureAtlasSprite ACID_SPRITE;
    public static TextureAtlasSprite BASIC_SPRITE;
    public static TextureAtlasSprite COMET_BLUE_SPRITE;
    public static TextureAtlasSprite COMET_WHITE_SPRITE;
    public static TextureAtlasSprite VENOM_CHAIN_SPRITE;
    public static TextureAtlasSprite VENOM_SPRITE;
    public static TextureAtlasSprite VENOM_RING_SPRITE;
    public static TextureAtlasSprite PLASMA_EXPLOSION_SPRITE;
    public static TextureAtlasSprite QUANTUM_MARK_SPRITE;
    public static TextureAtlasSprite GRAVITY_RING_SPRITE;
    public static TextureAtlasSprite POWER_PULSE_SPRITE;
    public static TextureAtlasSprite WITHER_RINGS_SPRITE;
    public static TextureAtlasSprite ATTRACT_FIELD_SPRITE;
    public static TextureAtlasSprite REPEL_FIELD_SPRITE;
    public static TextureAtlasSprite LASER_FIZZLE_SPRITE;
    public static TextureAtlasSprite SLAM_SPRITE;
    public static TextureAtlasSprite WARP_SPRITE;
    public static TextureAtlasSprite ION_BLAST_SPRITE;
    public static TextureAtlasSprite NUCLEAR_BLAST_SPRITE;
    public static TextureAtlasSprite GLOOM_SPELL_SPRITE;
    public static TextureAtlasSprite WEB_MAGIC_SPRITE;
    public static TextureAtlasSprite DARK_FLASH_SPRITE;
    public static TextureAtlasSprite LIGHT_FLASH_SPRITE;
    public static TextureAtlasSprite GLOOM_BURST_SPRITE;
    public static TextureAtlasSprite GOO_RING_SPRITE;
    public static TextureAtlasSprite CRESCENT_MOON_SPRITE;
    public static TextureAtlasSprite EXPLOSION_SPRITE;
    public static TextureAtlasSprite DARK_MAGIC_SPRITE;
    public static TextureAtlasSprite EXPLOSION_RING_SPRITE;
    public static TextureAtlasSprite ZAP_SPRITE;
    public static TextureAtlasSprite POISON_RINGS_SPRITE;
    public static TextureAtlasSprite PLAGUE_SPRITE;
    public static TextureAtlasSprite FLAME_SMALL_SPRITE;
    public static TextureAtlasSprite FLAME_MEDIUM_SPRITE;
    public static TextureAtlasSprite FLAME_LARGE_SPRITE;
    public static TextureAtlasSprite BOMBER_EXPLOSION_SPRITE;
    public static TextureAtlasSprite GLOMITE_WARP_SPRITE;
    public static TextureAtlasSprite LASER_FIZZLE_LARGE_SPRITE;
    public static TextureAtlasSprite SPACE_MAGIC_SPRITE;
    public static TextureAtlasSprite POWER_FIELD_SPRITE;
    public static final EnumParticleTypes GALAXY_YELLOW;
    public static final EnumParticleTypes GALAXY_BLUE;
    public static final EnumParticleTypes GALAXY_GREEN;
    public static final EnumParticleTypes GALAXY_PURPLE;
    public static final EnumParticleTypes HONEY_BUBBLE;
    public static final EnumParticleTypes POWER_LOSS;
    public static final EnumParticleTypes ANCIENT_SPELL;
    public static final EnumParticleTypes CLAW_MARKS;
    public static final EnumParticleTypes ELECTRIC_EXPLOSION_YELLOW;
    public static final EnumParticleTypes ELECTRIC_EXPLOSION_BLUE;
    public static final EnumParticleTypes CORRUPTION_MAGIC;
    public static final EnumParticleTypes NATURE_RING;
    public static final EnumParticleTypes NATURE_MAGIC;
    public static final EnumParticleTypes CRYSTAL_MAGIC;
    public static final EnumParticleTypes VENOM_CHAIN;
    public static final EnumParticleTypes SHADOW_BLAST;
    public static final EnumParticleTypes GOLD_STAR;
    public static final EnumParticleTypes DARK_FIZZLE;
    public static final EnumParticleTypes POISON_BUBBLE;
    public static final EnumParticleTypes PURPLE_SKULL;
    public static final EnumParticleTypes BLIGHT_SPELL_PINK;
    public static final EnumParticleTypes BLIGHT_SPELL_GREEN;
    public static final EnumParticleTypes SNOW_BUBBLE;
    public static final EnumParticleTypes BLUE_SKULL;
    public static final EnumParticleTypes MURK;
    public static final EnumParticleTypes NIGHTMARE_MAGIC;
    public static final EnumParticleTypes PLASMA_RIFT;
    public static final EnumParticleTypes PLASMA;
    public static final EnumParticleTypes SPECTRAL;
    public static final EnumParticleTypes PRISMATIC_EXPLOSION_TYPE1;
    public static final EnumParticleTypes PRISMATIC_EXPLOSION_TYPE2;
    public static final EnumParticleTypes PRISMATIC_EXPLOSION_TYPE3;
    public static final EnumParticleTypes GENERIC_DOT_YELLOW;
    public static final EnumParticleTypes GENERIC_DOT_ORANGE;
    public static final EnumParticleTypes GENERIC_DOT_TANGERINE;
    public static final EnumParticleTypes GENERIC_DOT_RED;
    public static final EnumParticleTypes GENERIC_DOT_PINK;
    public static final EnumParticleTypes GENERIC_DOT_PURPLE;
    public static final EnumParticleTypes GENERIC_DOT_BLUE;
    public static final EnumParticleTypes GENERIC_DOT_AQUA;
    public static final EnumParticleTypes GENERIC_DOT_GREEN;
    public static final EnumParticleTypes GENERIC_DOT_ACID;
    public static final EnumParticleTypes EXPLOSION_RING_DARK;
    public static final EnumParticleTypes EXPLOSION_BLUE;
    public static final EnumParticleTypes EXPLOSION_TEAL;
    public static final EnumParticleTypes EXPLOSION_LAVENDER;
    public static final EnumParticleTypes GOLDEN_MAGIC;
    public static final EnumParticleTypes BLOOD_DROP;
    public static final EnumParticleTypes NATURE_DOT;
    public static final EnumParticleTypes SMALL_SPARK;
    public static final EnumParticleTypes ACID_YELLOW;
    public static final EnumParticleTypes POISON_EXPLOSION;
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE1;
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE2;
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE3;
    public static final EnumParticleTypes COSMIC_EXPLOSION_TYPE4;
    public static final EnumParticleTypes BASIC_STAR_TYPE1;
    public static final EnumParticleTypes BASIC_STAR_TYPE2;
    public static final EnumParticleTypes BASIC_STAR_TYPE3;
    public static final EnumParticleTypes BASIC_STAR_TYPE4;
    public static final EnumParticleTypes LARGE_BUBBLE;
    public static final EnumParticleTypes LARGE_BUBBLE_PURPLE;
    public static final EnumParticleTypes MIASMA;
    public static final EnumParticleTypes SUPERSONIC_BLUE;
    public static final EnumParticleTypes SUPERSONIC_RED;
    public static final EnumParticleTypes EXPLOSION_RED;
    public static final EnumParticleTypes EXPLOSION_ORANGE;
    public static final EnumParticleTypes GRASP;
    public static final EnumParticleTypes BAD_MAGIC;
    public static final EnumParticleTypes CLAY_BUBBLE;
    public static final EnumParticleTypes CLAY_BLOCK;
    public static final EnumParticleTypes WATCHING_EYE;
    public static final EnumParticleTypes TESLA_RING_YELLOW;
    public static final EnumParticleTypes TESLA_RING_BLUE;
    public static final EnumParticleTypes ION_FUEL;
    public static final EnumParticleTypes EXPLOSION_YELLOW;
    public static final EnumParticleTypes DRAGON_FIRE;
    public static final EnumParticleTypes EXPLOSION_FEAR;
    public static final EnumParticleTypes STATIONARY_BUBBLE;
    public static final EnumParticleTypes GENERIC_DOT_WHITE;
    public static final EnumParticleTypes GENERIC_DOT_BLACK;
    public static final EnumParticleTypes MURKY_MIST;
    public static final EnumParticleTypes LIGHT_FIZZLE;
    public static final EnumParticleTypes RED_SKULL;
    public static final EnumParticleTypes CLOUD_GREEN;
    public static final EnumParticleTypes CLOUD_PURPLE;
    public static final EnumParticleTypes LIGHTNING_INDICATOR;
    public static final EnumParticleTypes VENOM;
    public static final EnumParticleTypes VENOM_RING;
    public static final EnumParticleTypes GRAVITY_RING;
    public static final EnumParticleTypes COMET_BLUE;
    public static final EnumParticleTypes COMET_WHITE;
    public static final EnumParticleTypes FIREGOO;
    public static final EnumParticleTypes ACID;
    public static final EnumParticleTypes PLASMA_EXPLOSION;
    public static final EnumParticleTypes QUANTUM_MARK;
    public static final EnumParticleTypes POWER_PULSE;
    public static final EnumParticleTypes WITHER_RINGS;
    public static final EnumParticleTypes ATTRACT_FIELD;
    public static final EnumParticleTypes REPEL_FIELD;
    public static final EnumParticleTypes LASER_FIZZLE;
    public static final EnumParticleTypes SLAM;
    public static final EnumParticleTypes WARP;
    public static final EnumParticleTypes ION_BLAST;
    public static final EnumParticleTypes NUCLEAR_BLAST;
    public static final EnumParticleTypes GOO_RING;
    public static final EnumParticleTypes CRESCENT_MOON;
    public static final EnumParticleTypes EXPLOSION;
    public static final EnumParticleTypes DARK_MAGIC;
    public static final EnumParticleTypes EXPLOSION_RING;
    public static final EnumParticleTypes ZAP;
    public static final EnumParticleTypes POISON_RINGS;
    public static final EnumParticleTypes PLAGUE;
    public static final EnumParticleTypes GLOOM_SPELL;
    public static final EnumParticleTypes WEB_MAGIC;
    public static final EnumParticleTypes DARK_FLASH;
    public static final EnumParticleTypes LIGHT_FLASH;
    public static final EnumParticleTypes GLOOM_BURST;
    public static final EnumParticleTypes FLAME_SMALL;
    public static final EnumParticleTypes FLAME_MEDIUM;
    public static final EnumParticleTypes FLAME_LARGE;
    public static final EnumParticleTypes BOMBER_EXPLOSION;
    public static final EnumParticleTypes GLOMITE_WARP;
    public static final EnumParticleTypes POWER_FIELD;
    public static final EnumParticleTypes SPACE_MAGIC;
    public static final EnumParticleTypes LASER_FIZZLE_LARGE;

    @SubscribeEvent
    @SideOnly(value=Side.CLIENT)
    public void stitchEvent(TextureStitchEvent.Pre ev) {
        GALAXY_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/galaxy_yellow"));
        GALAXY_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/galaxy_blue"));
        GALAXY_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/galaxy_green"));
        GALAXY_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/galaxy_purple"));
        HONEY_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/honey_bubble"));
        POWER_LOSS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/power_loss"));
        ANCIENT_SPELL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/ancient_spell"));
        CLAW_MARKS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/claw_marks"));
        ELECTRIC_EXPLOSION_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/electric_explosion_yellow"));
        ELECTRIC_EXPLOSION_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/electric_explosion_blue"));
        CORRUPTION_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/corruption_magic"));
        NATURE_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/nature_ring"));
        NATURE_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/nature_magic"));
        CRYSTAL_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/crystal_magic"));
        SHADOW_BLAST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/shadow_blast"));
        GOLD_STAR_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/gold_star"));
        DARK_FIZZLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/dark_fizzle"));
        POISON_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/poison_bubble"));
        PURPLE_SKULL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/purple_skull"));
        BLIGHT_SPELL_PINK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/blight_spell_pink"));
        BLIGHT_SPELL_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/blight_spell_green"));
        SNOW_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/snow_bubble"));
        BLUE_SKULL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/blue_skull"));
        MURK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/murk"));
        NIGHTMARE_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/nightmare_magic"));
        PLASMA_RIFT_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/plasma_rift"));
        PLASMA_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/plasma"));
        SPECTRAL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/spectral"));
        PRISMATIC_EXPLOSION_TYPE1_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/prismatic_explosion_type1"));
        PRISMATIC_EXPLOSION_TYPE2_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/prismatic_explosion_type2"));
        PRISMATIC_EXPLOSION_TYPE3_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/prismatic_explosion_type3"));
        GENERIC_DOT_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_yellow"));
        GENERIC_DOT_ORANGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_orange"));
        GENERIC_DOT_TANGERINE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_tangerine"));
        GENERIC_DOT_RED_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_red"));
        GENERIC_DOT_PINK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_pink"));
        GENERIC_DOT_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_purple"));
        GENERIC_DOT_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_blue"));
        GENERIC_DOT_AQUA_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_aqua"));
        GENERIC_DOT_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_green"));
        GENERIC_DOT_ACID_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_acid"));
        EXPLOSION_RING_DARK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_ring_dark"));
        EXPLOSION_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_blue"));
        EXPLOSION_TEAL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_teal"));
        EXPLOSION_LAVENDER_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_lavender"));
        GOLDEN_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/golden_magic"));
        BLOOD_DROP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/blood_drop"));
        NATURE_DOT_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/nature_dot"));
        SMALL_SPARK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/small_spark"));
        ACID_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/acid_yellow"));
        POISON_EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/poison_explosion"));
        COSMIC_EXPLOSION_TYPE1_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/cosmic_explosion_type1"));
        COSMIC_EXPLOSION_TYPE2_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/cosmic_explosion_type2"));
        COSMIC_EXPLOSION_TYPE3_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/cosmic_explosion_type3"));
        COSMIC_EXPLOSION_TYPE4_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/cosmic_explosion_type4"));
        BASIC_STAR_TYPE1_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/basic_star_type1"));
        BASIC_STAR_TYPE2_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/basic_star_type2"));
        BASIC_STAR_TYPE3_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/basic_star_type3"));
        BASIC_STAR_TYPE4_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/basic_star_type4"));
        LARGE_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/large_bubble"));
        LARGE_BUBBLE_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/large_bubble_purple"));
        MIASMA_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/miasma"));
        SUPERSONIC_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/supersonic_blue"));
        SUPERSONIC_RED_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/supersonic_red"));
        EXPLOSION_RED_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_red"));
        EXPLOSION_ORANGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_orange"));
        GRASP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/grasp"));
        BAD_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/bad_magic"));
        CLAY_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/clay_bubble"));
        CLAY_BLOCK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/clay_block"));
        WATCHING_EYE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/watching_eye"));
        TESLA_RING_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/tesla_ring_yellow"));
        TESLA_RING_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/tesla_ring_blue"));
        ION_FUEL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/ion_fuel"));
        EXPLOSION_YELLOW_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_yellow"));
        DRAGON_FIRE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/dragon_fire"));
        EXPLOSION_FEAR_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_fear"));
        STATIONARY_BUBBLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/large_bubble"));
        GENERIC_DOT_WHITE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_white"));
        GENERIC_DOT_BLACK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/generic_dot_black"));
        MURKY_MIST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/murky_mist"));
        LIGHT_FIZZLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/light_fizzle"));
        RED_SKULL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/red_skull"));
        CLOUD_GREEN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/cloud_green"));
        CLOUD_PURPLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/cloud_purple"));
        LIGHTNING_INDICATOR_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/lightning_indicator"));
        FIREGOO_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/firegoo"));
        ACID_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/acid"));
        COMET_BLUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/comet_blue"));
        COMET_WHITE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/comet_white"));
        VENOM_CHAIN_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/venom_chain"));
        VENOM_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/venom"));
        VENOM_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/venom_ring"));
        GRAVITY_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/gravity_ring"));
        QUANTUM_MARK_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/quantum_mark"));
        PLASMA_EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/plasma_explosion"));
        POWER_PULSE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/power_pulse"));
        WITHER_RINGS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/wither_rings"));
        ATTRACT_FIELD_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/attract_field"));
        REPEL_FIELD_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/repel_field"));
        LASER_FIZZLE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/laser_fizzle"));
        SLAM_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/slam"));
        WARP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/warp"));
        ION_BLAST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/ion_blast"));
        NUCLEAR_BLAST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/nuclear_blast"));
        GOO_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/goo_ring"));
        CRESCENT_MOON_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/crescent_moon"));
        EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion"));
        DARK_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/dark_magic"));
        EXPLOSION_RING_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/explosion_ring"));
        ZAP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/zap"));
        POISON_RINGS_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/poison_rings"));
        PLAGUE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/plague"));
        GLOOM_SPELL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/gloom_spell"));
        WEB_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/web_magic"));
        DARK_FLASH_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/dark_flash"));
        LIGHT_FLASH_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/light_flash"));
        GLOOM_BURST_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/gloom_burst"));
        FLAME_SMALL_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/flame_small"));
        FLAME_MEDIUM_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/flame_medium"));
        FLAME_LARGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/flame_large"));
        BOMBER_EXPLOSION_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/bomber_explosion"));
        GLOMITE_WARP_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/glomite_warp"));
        LASER_FIZZLE_LARGE_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/laser_fizzle_large"));
        SPACE_MAGIC_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/space_magic"));
        POWER_FIELD_SPRITE = ev.getMap().func_174942_a(new ResourceLocation("lostinfinity", "particles/power_field"));
    }

    @SideOnly(value=Side.CLIENT)
    public static void init() {
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_YELLOW.func_179348_c(), (IParticleFactory)new ParticleGalaxyYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_BLUE.func_179348_c(), (IParticleFactory)new ParticleGalaxyBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_GREEN.func_179348_c(), (IParticleFactory)new ParticleGalaxyGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GALAXY_PURPLE.func_179348_c(), (IParticleFactory)new ParticleGalaxyPurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(HONEY_BUBBLE.func_179348_c(), (IParticleFactory)new ParticleHoneyBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POWER_LOSS.func_179348_c(), (IParticleFactory)new ParticlePowerLoss.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ANCIENT_SPELL.func_179348_c(), (IParticleFactory)new ParticleAncientSpell.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLAW_MARKS.func_179348_c(), (IParticleFactory)new ParticleClawMarks.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ELECTRIC_EXPLOSION_YELLOW.func_179348_c(), (IParticleFactory)new ParticleElectricExplosionYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ELECTRIC_EXPLOSION_BLUE.func_179348_c(), (IParticleFactory)new ParticleElectricExplosionBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CORRUPTION_MAGIC.func_179348_c(), (IParticleFactory)new ParticleCorruptionMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NATURE_RING.func_179348_c(), (IParticleFactory)new ParticleNatureRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NATURE_MAGIC.func_179348_c(), (IParticleFactory)new ParticleNatureMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CRYSTAL_MAGIC.func_179348_c(), (IParticleFactory)new ParticleCrystalMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(VENOM_CHAIN.func_179348_c(), (IParticleFactory)new ParticleVenomChain.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SHADOW_BLAST.func_179348_c(), (IParticleFactory)new ParticleShadowBlast.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GOLD_STAR.func_179348_c(), (IParticleFactory)new ParticleGoldStar.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DARK_FIZZLE.func_179348_c(), (IParticleFactory)new ParticleDarkFizzle.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POISON_BUBBLE.func_179348_c(), (IParticleFactory)new ParticlePoisonBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PURPLE_SKULL.func_179348_c(), (IParticleFactory)new ParticlePurpleSkull.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLIGHT_SPELL_PINK.func_179348_c(), (IParticleFactory)new ParticleBlightSpellPink.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLIGHT_SPELL_GREEN.func_179348_c(), (IParticleFactory)new ParticleBlightSpellGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SNOW_BUBBLE.func_179348_c(), (IParticleFactory)new ParticleSnowBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLUE_SKULL.func_179348_c(), (IParticleFactory)new ParticleBlueSkull.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(MURK.func_179348_c(), (IParticleFactory)new ParticleMurk.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NIGHTMARE_MAGIC.func_179348_c(), (IParticleFactory)new ParticleNightmareMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLASMA_RIFT.func_179348_c(), (IParticleFactory)new ParticlePlasmaRift.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLASMA.func_179348_c(), (IParticleFactory)new ParticlePlasma.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SPECTRAL.func_179348_c(), (IParticleFactory)new ParticleSpectral.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PRISMATIC_EXPLOSION_TYPE1.func_179348_c(), (IParticleFactory)new ParticlePrismaticExplosionType1.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PRISMATIC_EXPLOSION_TYPE2.func_179348_c(), (IParticleFactory)new ParticlePrismaticExplosionType2.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PRISMATIC_EXPLOSION_TYPE3.func_179348_c(), (IParticleFactory)new ParticlePrismaticExplosionType3.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_YELLOW.func_179348_c(), (IParticleFactory)new ParticleGenericDotYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_ORANGE.func_179348_c(), (IParticleFactory)new ParticleGenericDotOrange.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_TANGERINE.func_179348_c(), (IParticleFactory)new ParticleGenericDotTangerine.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_RED.func_179348_c(), (IParticleFactory)new ParticleGenericDotRed.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_PINK.func_179348_c(), (IParticleFactory)new ParticleGenericDotPink.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_PURPLE.func_179348_c(), (IParticleFactory)new ParticleGenericDotPurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_BLUE.func_179348_c(), (IParticleFactory)new ParticleGenericDotBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_AQUA.func_179348_c(), (IParticleFactory)new ParticleGenericDotAqua.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_GREEN.func_179348_c(), (IParticleFactory)new ParticleGenericDotGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_ACID.func_179348_c(), (IParticleFactory)new ParticleGenericDotAcid.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_RING_DARK.func_179348_c(), (IParticleFactory)new ParticleExplosionRingDark.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_BLUE.func_179348_c(), (IParticleFactory)new ParticleExplosionBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_TEAL.func_179348_c(), (IParticleFactory)new ParticleExplosionTeal.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_LAVENDER.func_179348_c(), (IParticleFactory)new ParticleExplosionLavender.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GOLDEN_MAGIC.func_179348_c(), (IParticleFactory)new ParticleGoldenMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BLOOD_DROP.func_179348_c(), (IParticleFactory)new ParticleBloodDrop.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NATURE_DOT.func_179348_c(), (IParticleFactory)new ParticleNatureDot.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SMALL_SPARK.func_179348_c(), (IParticleFactory)new ParticleSmallSpark.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ACID_YELLOW.func_179348_c(), (IParticleFactory)new ParticleAcidYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POISON_EXPLOSION.func_179348_c(), (IParticleFactory)new ParticlePoisonExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE1.func_179348_c(), (IParticleFactory)new ParticleCosmicExplosionType1.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE2.func_179348_c(), (IParticleFactory)new ParticleCosmicExplosionType2.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE3.func_179348_c(), (IParticleFactory)new ParticleCosmicExplosionType3.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COSMIC_EXPLOSION_TYPE4.func_179348_c(), (IParticleFactory)new ParticleCosmicExplosionType4.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE1.func_179348_c(), (IParticleFactory)new ParticleBasicStarType1.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE2.func_179348_c(), (IParticleFactory)new ParticleBasicStarType2.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE3.func_179348_c(), (IParticleFactory)new ParticleBasicStarType3.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BASIC_STAR_TYPE4.func_179348_c(), (IParticleFactory)new ParticleBasicStarType4.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LARGE_BUBBLE.func_179348_c(), (IParticleFactory)new ParticleLargeBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LARGE_BUBBLE_PURPLE.func_179348_c(), (IParticleFactory)new ParticleLargeBubblePurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(MIASMA.func_179348_c(), (IParticleFactory)new ParticleMiasma.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SUPERSONIC_BLUE.func_179348_c(), (IParticleFactory)new ParticleSupersonicBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SUPERSONIC_RED.func_179348_c(), (IParticleFactory)new ParticleSupersonicRed.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_RED.func_179348_c(), (IParticleFactory)new ParticleExplosionRed.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_ORANGE.func_179348_c(), (IParticleFactory)new ParticleExplosionOrange.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GRASP.func_179348_c(), (IParticleFactory)new ParticleGrasp.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BAD_MAGIC.func_179348_c(), (IParticleFactory)new ParticleBadMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLAY_BUBBLE.func_179348_c(), (IParticleFactory)new ParticleClayBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLAY_BLOCK.func_179348_c(), (IParticleFactory)new ParticleClayBlock.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WATCHING_EYE.func_179348_c(), (IParticleFactory)new ParticleWatchingEye.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(TESLA_RING_YELLOW.func_179348_c(), (IParticleFactory)new ParticleTeslaRingYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(TESLA_RING_BLUE.func_179348_c(), (IParticleFactory)new ParticleTeslaRingBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ION_FUEL.func_179348_c(), (IParticleFactory)new ParticleIonFuel.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_YELLOW.func_179348_c(), (IParticleFactory)new ParticleExplosionYellow.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DRAGON_FIRE.func_179348_c(), (IParticleFactory)new ParticleDragonFire.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_FEAR.func_179348_c(), (IParticleFactory)new ParticleExplosionFear.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(STATIONARY_BUBBLE.func_179348_c(), (IParticleFactory)new ParticleStationaryBubble.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_WHITE.func_179348_c(), (IParticleFactory)new ParticleGenericDotWhite.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GENERIC_DOT_BLACK.func_179348_c(), (IParticleFactory)new ParticleGenericDotBlack.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(MURKY_MIST.func_179348_c(), (IParticleFactory)new ParticleMurkyMist.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LIGHT_FIZZLE.func_179348_c(), (IParticleFactory)new ParticleLightFizzle.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(RED_SKULL.func_179348_c(), (IParticleFactory)new ParticleRedSkull.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLOUD_GREEN.func_179348_c(), (IParticleFactory)new ParticleCloudGreen.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CLOUD_PURPLE.func_179348_c(), (IParticleFactory)new ParticleCloudPurple.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LIGHTNING_INDICATOR.func_179348_c(), (IParticleFactory)new ParticleLightningIndicator.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FIREGOO.func_179348_c(), (IParticleFactory)new ParticleFiregoo.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ACID.func_179348_c(), (IParticleFactory)new ParticleAcid.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COMET_WHITE.func_179348_c(), (IParticleFactory)new ParticleCometWhite.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(COMET_BLUE.func_179348_c(), (IParticleFactory)new ParticleCometBlue.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(VENOM.func_179348_c(), (IParticleFactory)new ParticleVenom.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(VENOM_RING.func_179348_c(), (IParticleFactory)new ParticleVenomRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GRAVITY_RING.func_179348_c(), (IParticleFactory)new ParticleGravityRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POWER_PULSE.func_179348_c(), (IParticleFactory)new ParticlePowerPulse.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLASMA_EXPLOSION.func_179348_c(), (IParticleFactory)new ParticlePlasmaExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(QUANTUM_MARK.func_179348_c(), (IParticleFactory)new ParticleQuantumMark.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WITHER_RINGS.func_179348_c(), (IParticleFactory)new ParticleWitherRings.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ATTRACT_FIELD.func_179348_c(), (IParticleFactory)new ParticleAttractField.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(REPEL_FIELD.func_179348_c(), (IParticleFactory)new ParticleRepelField.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LASER_FIZZLE.func_179348_c(), (IParticleFactory)new ParticleLaserFizzle.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SLAM.func_179348_c(), (IParticleFactory)new ParticleSlam.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WARP.func_179348_c(), (IParticleFactory)new ParticleWarp.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ION_BLAST.func_179348_c(), (IParticleFactory)new ParticleIonBlast.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(NUCLEAR_BLAST.func_179348_c(), (IParticleFactory)new ParticleNuclearBlast.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GOO_RING.func_179348_c(), (IParticleFactory)new ParticleGooRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(CRESCENT_MOON.func_179348_c(), (IParticleFactory)new ParticleCrescentMoon.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION.func_179348_c(), (IParticleFactory)new ParticleExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DARK_MAGIC.func_179348_c(), (IParticleFactory)new ParticleDarkMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(EXPLOSION_RING.func_179348_c(), (IParticleFactory)new ParticleExplosionRing.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(ZAP.func_179348_c(), (IParticleFactory)new ParticleZap.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POISON_RINGS.func_179348_c(), (IParticleFactory)new ParticlePoisonRings.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(PLAGUE.func_179348_c(), (IParticleFactory)new ParticlePlague.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GLOOM_SPELL.func_179348_c(), (IParticleFactory)new ParticleGloomSpell.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(WEB_MAGIC.func_179348_c(), (IParticleFactory)new ParticleWebMagic.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(DARK_FLASH.func_179348_c(), (IParticleFactory)new ParticleDarkFlash.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LIGHT_FLASH.func_179348_c(), (IParticleFactory)new ParticleLightFlash.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GLOOM_BURST.func_179348_c(), (IParticleFactory)new ParticleGloomBurst.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FLAME_SMALL.func_179348_c(), (IParticleFactory)new ParticleFlameSmall.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FLAME_MEDIUM.func_179348_c(), (IParticleFactory)new ParticleFlameMedium.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(FLAME_LARGE.func_179348_c(), (IParticleFactory)new ParticleFlameLarge.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(BOMBER_EXPLOSION.func_179348_c(), (IParticleFactory)new ParticleBomberExplosion.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(GLOMITE_WARP.func_179348_c(), (IParticleFactory)new ParticleGlomiteWarp.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(POWER_FIELD.func_179348_c(), (IParticleFactory)new ParticlePowerField.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(LASER_FIZZLE_LARGE.func_179348_c(), (IParticleFactory)new ParticleLaserFizzleLarge.Factory());
        Minecraft.func_71410_x().field_71452_i.func_178929_a(SPACE_MAGIC.func_179348_c(), (IParticleFactory)new ParticleSpaceMagic.Factory());
    }

    private static EnumParticleTypes particleRegistry(String name) {
        return ParticleInit.particleRegistry(name, true, 0);
    }

    private static EnumParticleTypes particleRegistry(String name, boolean displayAnyRange) {
        return ParticleInit.particleRegistry(name, displayAnyRange, 0);
    }

    private static EnumParticleTypes particleRegistry(String name, boolean displayAnyRange, int args) {
        return (EnumParticleTypes)EnumHelper.addEnum(EnumParticleTypes.class, (String)("LI_" + name.toUpperCase()), (Class[])new Class[]{String.class, Integer.TYPE, Boolean.TYPE, Integer.TYPE}, (Object[])new Object[]{"li_" + name, EnumParticleTypes.values().length, displayAnyRange, args});
    }

    static {
        GALAXY_YELLOW = ParticleInit.particleRegistry("galaxy_yellow");
        GALAXY_BLUE = ParticleInit.particleRegistry("galaxy_blue");
        GALAXY_GREEN = ParticleInit.particleRegistry("galaxy_green");
        GALAXY_PURPLE = ParticleInit.particleRegistry("galaxy_purple");
        HONEY_BUBBLE = ParticleInit.particleRegistry("honey_bubble");
        POWER_LOSS = ParticleInit.particleRegistry("power_loss");
        ANCIENT_SPELL = ParticleInit.particleRegistry("ancient_spell");
        CLAW_MARKS = ParticleInit.particleRegistry("claw_marks");
        ELECTRIC_EXPLOSION_YELLOW = ParticleInit.particleRegistry("electric_explosion_yellow");
        ELECTRIC_EXPLOSION_BLUE = ParticleInit.particleRegistry("electric_explosion_blue");
        CORRUPTION_MAGIC = ParticleInit.particleRegistry("corruption_magic");
        NATURE_RING = ParticleInit.particleRegistry("nature_ring");
        NATURE_MAGIC = ParticleInit.particleRegistry("nature_magic");
        CRYSTAL_MAGIC = ParticleInit.particleRegistry("crystal_magic");
        VENOM_CHAIN = ParticleInit.particleRegistry("venom_chain");
        SHADOW_BLAST = ParticleInit.particleRegistry("shadow_blast");
        GOLD_STAR = ParticleInit.particleRegistry("gold_star");
        DARK_FIZZLE = ParticleInit.particleRegistry("dark_fizzle");
        POISON_BUBBLE = ParticleInit.particleRegistry("poison_bubble");
        PURPLE_SKULL = ParticleInit.particleRegistry("purple_skull");
        BLIGHT_SPELL_PINK = ParticleInit.particleRegistry("blight_spell_pink");
        BLIGHT_SPELL_GREEN = ParticleInit.particleRegistry("blight_spell_green");
        SNOW_BUBBLE = ParticleInit.particleRegistry("snow_bubble");
        BLUE_SKULL = ParticleInit.particleRegistry("blue_skull");
        MURK = ParticleInit.particleRegistry("murk");
        NIGHTMARE_MAGIC = ParticleInit.particleRegistry("nightmare_magic");
        PLASMA_RIFT = ParticleInit.particleRegistry("plasma_rift");
        PLASMA = ParticleInit.particleRegistry("plasma");
        SPECTRAL = ParticleInit.particleRegistry("spectral");
        PRISMATIC_EXPLOSION_TYPE1 = ParticleInit.particleRegistry("prismatic_explosion_type1");
        PRISMATIC_EXPLOSION_TYPE2 = ParticleInit.particleRegistry("prismatic_explosion_type2");
        PRISMATIC_EXPLOSION_TYPE3 = ParticleInit.particleRegistry("prismatic_explosion_type3");
        GENERIC_DOT_YELLOW = ParticleInit.particleRegistry("generic_dot_yellow");
        GENERIC_DOT_ORANGE = ParticleInit.particleRegistry("generic_dot_orange");
        GENERIC_DOT_TANGERINE = ParticleInit.particleRegistry("generic_dot_tangerine");
        GENERIC_DOT_RED = ParticleInit.particleRegistry("generic_dot_red");
        GENERIC_DOT_PINK = ParticleInit.particleRegistry("generic_dot_pink");
        GENERIC_DOT_PURPLE = ParticleInit.particleRegistry("generic_dot_purple");
        GENERIC_DOT_BLUE = ParticleInit.particleRegistry("generic_dot_blue");
        GENERIC_DOT_AQUA = ParticleInit.particleRegistry("generic_dot_aqua");
        GENERIC_DOT_GREEN = ParticleInit.particleRegistry("generic_dot_green");
        GENERIC_DOT_ACID = ParticleInit.particleRegistry("generic_dot_acid");
        EXPLOSION_RING_DARK = ParticleInit.particleRegistry("explosion_ring_dark");
        EXPLOSION_BLUE = ParticleInit.particleRegistry("explosion_blue");
        EXPLOSION_TEAL = ParticleInit.particleRegistry("explosion_teal");
        EXPLOSION_LAVENDER = ParticleInit.particleRegistry("explosion_lavender");
        GOLDEN_MAGIC = ParticleInit.particleRegistry("golden_magic");
        BLOOD_DROP = ParticleInit.particleRegistry("blood_drop");
        NATURE_DOT = ParticleInit.particleRegistry("nature_dot");
        SMALL_SPARK = ParticleInit.particleRegistry("small_spark");
        ACID_YELLOW = ParticleInit.particleRegistry("acid_yellow");
        POISON_EXPLOSION = ParticleInit.particleRegistry("poison_explosion");
        COSMIC_EXPLOSION_TYPE1 = ParticleInit.particleRegistry("cosmic_explosion_type1");
        COSMIC_EXPLOSION_TYPE2 = ParticleInit.particleRegistry("cosmic_explosion_type2");
        COSMIC_EXPLOSION_TYPE3 = ParticleInit.particleRegistry("cosmic_explosion_type3");
        COSMIC_EXPLOSION_TYPE4 = ParticleInit.particleRegistry("cosmic_explosion_type4");
        BASIC_STAR_TYPE1 = ParticleInit.particleRegistry("basic_star_type1");
        BASIC_STAR_TYPE2 = ParticleInit.particleRegistry("basic_star_type2");
        BASIC_STAR_TYPE3 = ParticleInit.particleRegistry("basic_star_type3");
        BASIC_STAR_TYPE4 = ParticleInit.particleRegistry("basic_star_type4");
        LARGE_BUBBLE = ParticleInit.particleRegistry("large_bubble");
        LARGE_BUBBLE_PURPLE = ParticleInit.particleRegistry("large_bubble_purple");
        MIASMA = ParticleInit.particleRegistry("miasma");
        SUPERSONIC_BLUE = ParticleInit.particleRegistry("supersonic_blue");
        SUPERSONIC_RED = ParticleInit.particleRegistry("supersonic_red");
        EXPLOSION_RED = ParticleInit.particleRegistry("explosion_red");
        EXPLOSION_ORANGE = ParticleInit.particleRegistry("explosion_orange");
        GRASP = ParticleInit.particleRegistry("grasp");
        BAD_MAGIC = ParticleInit.particleRegistry("bad_magic");
        CLAY_BUBBLE = ParticleInit.particleRegistry("clay_bubble");
        CLAY_BLOCK = ParticleInit.particleRegistry("clay_block");
        WATCHING_EYE = ParticleInit.particleRegistry("watching_eye");
        TESLA_RING_YELLOW = ParticleInit.particleRegistry("tesla_ring_yellow");
        TESLA_RING_BLUE = ParticleInit.particleRegistry("tesla_ring_blue");
        ION_FUEL = ParticleInit.particleRegistry("ion_fuel");
        EXPLOSION_YELLOW = ParticleInit.particleRegistry("explosion_yellow");
        DRAGON_FIRE = ParticleInit.particleRegistry("dragon_fire");
        EXPLOSION_FEAR = ParticleInit.particleRegistry("explosion_fear");
        STATIONARY_BUBBLE = ParticleInit.particleRegistry("stationary_bubble");
        GENERIC_DOT_WHITE = ParticleInit.particleRegistry("generic_dot_white");
        GENERIC_DOT_BLACK = ParticleInit.particleRegistry("generic_dot_black");
        MURKY_MIST = ParticleInit.particleRegistry("murky_mist");
        LIGHT_FIZZLE = ParticleInit.particleRegistry("light_fizzle");
        RED_SKULL = ParticleInit.particleRegistry("red_skull");
        CLOUD_GREEN = ParticleInit.particleRegistry("cloud_green");
        CLOUD_PURPLE = ParticleInit.particleRegistry("cloud_purple");
        LIGHTNING_INDICATOR = ParticleInit.particleRegistry("lightning_indicator");
        VENOM = ParticleInit.particleRegistry("venom");
        VENOM_RING = ParticleInit.particleRegistry("venom_ring");
        GRAVITY_RING = ParticleInit.particleRegistry("gravity_ring");
        COMET_BLUE = ParticleInit.particleRegistry("comet_blue");
        COMET_WHITE = ParticleInit.particleRegistry("comet_white");
        FIREGOO = ParticleInit.particleRegistry("firegoo");
        ACID = ParticleInit.particleRegistry("acid");
        PLASMA_EXPLOSION = ParticleInit.particleRegistry("plasma_explosion");
        QUANTUM_MARK = ParticleInit.particleRegistry("quantum_mark");
        POWER_PULSE = ParticleInit.particleRegistry("power_pulse");
        WITHER_RINGS = ParticleInit.particleRegistry("wither_rings");
        ATTRACT_FIELD = ParticleInit.particleRegistry("attract_field");
        REPEL_FIELD = ParticleInit.particleRegistry("repel_field");
        LASER_FIZZLE = ParticleInit.particleRegistry("laser_fizzle");
        SLAM = ParticleInit.particleRegistry("slam");
        WARP = ParticleInit.particleRegistry("warp");
        ION_BLAST = ParticleInit.particleRegistry("ion_blast");
        NUCLEAR_BLAST = ParticleInit.particleRegistry("nuclear_blast");
        GOO_RING = ParticleInit.particleRegistry("goo_ring");
        CRESCENT_MOON = ParticleInit.particleRegistry("crescent_moon");
        EXPLOSION = ParticleInit.particleRegistry("explosion");
        DARK_MAGIC = ParticleInit.particleRegistry("dark_magic");
        EXPLOSION_RING = ParticleInit.particleRegistry("explosion_ring");
        ZAP = ParticleInit.particleRegistry("zap");
        POISON_RINGS = ParticleInit.particleRegistry("poison_rings");
        PLAGUE = ParticleInit.particleRegistry("plague");
        GLOOM_SPELL = ParticleInit.particleRegistry("gloom_spell");
        WEB_MAGIC = ParticleInit.particleRegistry("web_magic");
        DARK_FLASH = ParticleInit.particleRegistry("dark_flash");
        LIGHT_FLASH = ParticleInit.particleRegistry("light_flash");
        GLOOM_BURST = ParticleInit.particleRegistry("gloom_burst");
        FLAME_SMALL = ParticleInit.particleRegistry("flame_small");
        FLAME_MEDIUM = ParticleInit.particleRegistry("flame_medium");
        FLAME_LARGE = ParticleInit.particleRegistry("flame_large");
        BOMBER_EXPLOSION = ParticleInit.particleRegistry("bomber_explosion");
        GLOMITE_WARP = ParticleInit.particleRegistry("glomite_warp");
        POWER_FIELD = ParticleInit.particleRegistry("power_field");
        SPACE_MAGIC = ParticleInit.particleRegistry("space_magic");
        LASER_FIZZLE_LARGE = ParticleInit.particleRegistry("laze_fizzle_large");
    }
}

