package xol.lostinfinity.registry;

import net.minecraft.world.item.Item;
import net.minecraft.world.entity.EntityType;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.RegistryObject;
import xol.lostinfinity.entity.LostPlaceholderMob;

public final class ModSpawnEggs {
    private ModSpawnEggs() {
    }

    private static RegistryObject<Item> registerSpawnEgg(String entityName, RegistryObject<EntityType<LostPlaceholderMob>> entityType, int primary, int secondary) {
        RegistryObject<Item> item = ModItems.ITEMS.register(entityName + "_spawn_egg", () -> new ForgeSpawnEggItem(entityType, primary, secondary, new Item.Properties()));
        ModItems.ALL_ITEMS.add(item);
        return item;
    }

    public static void touch() {
    }

    public static final RegistryObject<Item> SPAWN_EGG_DIMENSIONALMERCHANT = registerSpawnEgg("dimensionalmerchant", ModEntities.DIMENSIONALMERCHANT, 7614683, 443842);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTBEAR = registerSpawnEgg("deviantbear", ModEntities.DEVIANTBEAR, 0x808AA8, 3104159);
    public static final RegistryObject<Item> SPAWN_EGG_TREADMILLOBSTACLE = registerSpawnEgg("treadmillobstacle", ModEntities.TREADMILLOBSTACLE, 0x808AA8, 3104159);
    public static final RegistryObject<Item> SPAWN_EGG_TREADMILLOBSTACLEJUMPABLE = registerSpawnEgg("treadmillobstaclejumpable", ModEntities.TREADMILLOBSTACLEJUMPABLE, 0x808AA8, 3104159);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTGHAST = registerSpawnEgg("deviantghast", ModEntities.DEVIANTGHAST, 0x444444, 0xB00900);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTCOW = registerSpawnEgg("deviantcow", ModEntities.DEVIANTCOW, 2766650, 43263);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSHEEP = registerSpawnEgg("deviantsheep", ModEntities.DEVIANTSHEEP, 2766650, 43263);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTHORSE = registerSpawnEgg("devianthorse", ModEntities.DEVIANTHORSE, 2766650, 43263);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTPIG = registerSpawnEgg("deviantpig", ModEntities.DEVIANTPIG, 2766650, 43263);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTEVOKER = registerSpawnEgg("deviantevoker", ModEntities.DEVIANTEVOKER, 2766650, 43263);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTEVOKERVEX = registerSpawnEgg("deviantevokervex", ModEntities.DEVIANTEVOKERVEX, 2766650, 43263);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTENDERMAN = registerSpawnEgg("deviantenderman", ModEntities.DEVIANTENDERMAN, 0, 9579469);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTCHICKEN = registerSpawnEgg("deviantchicken", ModEntities.DEVIANTCHICKEN, 0x888888, 5964804);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSHULKER = registerSpawnEgg("deviantshulker", ModEntities.DEVIANTSHULKER, 4216413, 12247777);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSKYWORM = registerSpawnEgg("deviantskyworm", ModEntities.DEVIANTSKYWORM, 1585203, 7783599);
    public static final RegistryObject<Item> SPAWN_EGG_ELARA = registerSpawnEgg("elara", ModEntities.ELARA, 11072475, 1780577);
    public static final RegistryObject<Item> SPAWN_EGG_INFINITYSTONE = registerSpawnEgg("infinitystone", ModEntities.INFINITYSTONE, 0, 0);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTCREEPER = registerSpawnEgg("deviantcreeper", ModEntities.DEVIANTCREEPER, 4874085, 25830);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSKELETON = registerSpawnEgg("deviantskeleton", ModEntities.DEVIANTSKELETON, 3623000, 0xF2F2F3);
    public static final RegistryObject<Item> SPAWN_EGG_UROGO = registerSpawnEgg("urogo", ModEntities.UROGO, 6488834, 12538624);
    public static final RegistryObject<Item> SPAWN_EGG_DROID = registerSpawnEgg("droid", ModEntities.DROID, 0x737373, 12779777);
    public static final RegistryObject<Item> SPAWN_EGG_DROIDBOSS = registerSpawnEgg("droidboss", ModEntities.DROIDBOSS, 3624277, 12779777);
    public static final RegistryObject<Item> SPAWN_EGG_LOSTDEVIANT = registerSpawnEgg("lostdeviant", ModEntities.LOSTDEVIANT, 2571854, 474615);
    public static final RegistryObject<Item> SPAWN_EGG_ARENAEVENT = registerSpawnEgg("arenaevent", ModEntities.ARENAEVENT, 7857, 13303812);
    public static final RegistryObject<Item> SPAWN_EGG_LABWARRIOR = registerSpawnEgg("labwarrior", ModEntities.LABWARRIOR, 5139306, 9448480);
    public static final RegistryObject<Item> SPAWN_EGG_LABWIZARD = registerSpawnEgg("labwizard", ModEntities.LABWIZARD, 419797, 9448480);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSPIDER = registerSpawnEgg("deviantspider", ModEntities.DEVIANTSPIDER, 2306367, 46518);
    public static final RegistryObject<Item> SPAWN_EGG_ASPECT = registerSpawnEgg("aspect", ModEntities.ASPECT, 0xA00100, 14471093);
    public static final RegistryObject<Item> SPAWN_EGG_SLIMESTRIDER = registerSpawnEgg("slimestrider", ModEntities.SLIMESTRIDER, 6072961, 6983758);
    public static final RegistryObject<Item> SPAWN_EGG_VELO = registerSpawnEgg("velo", ModEntities.VELO, 1192507, 1055801);
    public static final RegistryObject<Item> SPAWN_EGG_GALAXYBEAST = registerSpawnEgg("galaxybeast", ModEntities.GALAXYBEAST, 921102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GALAXYSORCERER = registerSpawnEgg("galaxysorcerer", ModEntities.GALAXYSORCERER, 921102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GALAXYGLADIATOR = registerSpawnEgg("galaxygladiator", ModEntities.GALAXYGLADIATOR, 921102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GALAXYSPIRE = registerSpawnEgg("galaxyspire", ModEntities.GALAXYSPIRE, 921102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTAMALGAM = registerSpawnEgg("deviantamalgam", ModEntities.DEVIANTAMALGAM, 921102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_STARFIEND = registerSpawnEgg("starfiend", ModEntities.STARFIEND, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_BLOODHUNTER = registerSpawnEgg("bloodhunter", ModEntities.BLOODHUNTER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FUNGFLY = registerSpawnEgg("fungfly", ModEntities.FUNGFLY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RIKARUS = registerSpawnEgg("rikarus", ModEntities.RIKARUS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RESTORATIONCRYSTAL = registerSpawnEgg("restorationcrystal", ModEntities.RESTORATIONCRYSTAL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTWITCH = registerSpawnEgg("deviantwitch", ModEntities.DEVIANTWITCH, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MIRRORZOMBIE = registerSpawnEgg("mirrorzombie", ModEntities.MIRRORZOMBIE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSLIMESTRIDER = registerSpawnEgg("deviantslimestrider", ModEntities.DEVIANTSLIMESTRIDER, 6072961, 6983758);
    public static final RegistryObject<Item> SPAWN_EGG_CHEMIST = registerSpawnEgg("chemist", ModEntities.CHEMIST, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SANDATTACK = registerSpawnEgg("sandattack", ModEntities.SANDATTACK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTBLAZE = registerSpawnEgg("deviantblaze", ModEntities.DEVIANTBLAZE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANBLAZE = registerSpawnEgg("titanblaze", ModEntities.TITANBLAZE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANSHULKER = registerSpawnEgg("titanshulker", ModEntities.TITANSHULKER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANSPIDER = registerSpawnEgg("titanspider", ModEntities.TITANSPIDER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANSKELETON = registerSpawnEgg("titanskeleton", ModEntities.TITANSKELETON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TRIALOBSERVER = registerSpawnEgg("trialobserver", ModEntities.TRIALOBSERVER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_REFLECTAL = registerSpawnEgg("reflectal", ModEntities.REFLECTAL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LUMINOUSGUARDIAN = registerSpawnEgg("luminousguardian", ModEntities.LUMINOUSGUARDIAN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_HANGER = registerSpawnEgg("hanger", ModEntities.HANGER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ACIDBACK = registerSpawnEgg("acidback", ModEntities.ACIDBACK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GRAVHEAD = registerSpawnEgg("gravhead", ModEntities.GRAVHEAD, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ROCKPEST = registerSpawnEgg("rockpest", ModEntities.ROCKPEST, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SPINOVERN = registerSpawnEgg("spinovern", ModEntities.SPINOVERN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_HYPNOSAUR = registerSpawnEgg("hypnosaur", ModEntities.HYPNOSAUR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CHOMPER = registerSpawnEgg("chomper", ModEntities.CHOMPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RIBREX = registerSpawnEgg("ribrex", ModEntities.RIBREX, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GNAWER = registerSpawnEgg("gnawer", ModEntities.GNAWER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SCREACHER = registerSpawnEgg("screacher", ModEntities.SCREACHER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_EYESLUG = registerSpawnEgg("eyeslug", ModEntities.EYESLUG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FLUTTERFYRE = registerSpawnEgg("flutterfyre", ModEntities.FLUTTERFYRE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSNOWMAN = registerSpawnEgg("deviantsnowman", ModEntities.DEVIANTSNOWMAN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NUXURO = registerSpawnEgg("nuxuro", ModEntities.NUXURO, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CLYSTER = registerSpawnEgg("clyster", ModEntities.CLYSTER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CRAWKER = registerSpawnEgg("crawker", ModEntities.CRAWKER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DUSKER = registerSpawnEgg("dusker", ModEntities.DUSKER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_EXPLOSECT = registerSpawnEgg("explosect", ModEntities.EXPLOSECT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FLAPPER = registerSpawnEgg("flapper", ModEntities.FLAPPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FLURKY = registerSpawnEgg("flurky", ModEntities.FLURKY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FYREWEED = registerSpawnEgg("fyreweed", ModEntities.FYREWEED, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GRAPPLER = registerSpawnEgg("grappler", ModEntities.GRAPPLER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_HURLER = registerSpawnEgg("hurler", ModEntities.HURLER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PHASER = registerSpawnEgg("phaser", ModEntities.PHASER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SHIMMER = registerSpawnEgg("shimmer", ModEntities.SHIMMER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SPYKER = registerSpawnEgg("spyker", ModEntities.SPYKER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTMOOSHROOM = registerSpawnEgg("deviantmooshroom", ModEntities.DEVIANTMOOSHROOM, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTZOMBIE = registerSpawnEgg("deviantzombie", ModEntities.DEVIANTZOMBIE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSLIME = registerSpawnEgg("deviantslime", ModEntities.DEVIANTSLIME, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ARASH = registerSpawnEgg("arash", ModEntities.ARASH, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ALESTRIA = registerSpawnEgg("alestria", ModEntities.ALESTRIA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ATLASSPIRE = registerSpawnEgg("atlasspire", ModEntities.ATLASSPIRE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DARRIO = registerSpawnEgg("darrio", ModEntities.DARRIO, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_BARUL = registerSpawnEgg("barul", ModEntities.BARUL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SENTRYCRYSTAL = registerSpawnEgg("sentrycrystal", ModEntities.SENTRYCRYSTAL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ATLASCRYSTAL = registerSpawnEgg("atlascrystal", ModEntities.ATLASCRYSTAL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTCRYSTAL = registerSpawnEgg("deviantcrystal", ModEntities.DEVIANTCRYSTAL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTLLAMA = registerSpawnEgg("deviantllama", ModEntities.DEVIANTLLAMA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTMAGMACUBE = registerSpawnEgg("deviantmagmacube", ModEntities.DEVIANTMAGMACUBE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTVEX = registerSpawnEgg("deviantvex", ModEntities.DEVIANTVEX, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSTRAY = registerSpawnEgg("deviantstray", ModEntities.DEVIANTSTRAY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTPIGLIN = registerSpawnEgg("deviantpiglin", ModEntities.DEVIANTPIGLIN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANCREEPER = registerSpawnEgg("titancreeper", ModEntities.TITANCREEPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANENDERMAN = registerSpawnEgg("titanenderman", ModEntities.TITANENDERMAN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANLLAMA = registerSpawnEgg("titanllama", ModEntities.TITANLLAMA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANMAGMACUBE = registerSpawnEgg("titanmagmacube", ModEntities.TITANMAGMACUBE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANPIGLIN = registerSpawnEgg("titanpiglin", ModEntities.TITANPIGLIN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANSTRAY = registerSpawnEgg("titanstray", ModEntities.TITANSTRAY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_COURSERING = registerSpawnEgg("coursering", ModEntities.COURSERING, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANVEX = registerSpawnEgg("titanvex", ModEntities.TITANVEX, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANZOMBIE = registerSpawnEgg("titanzombie", ModEntities.TITANZOMBIE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLOOP = registerSpawnEgg("gloop", ModEntities.GLOOP, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLOOPMOTHER = registerSpawnEgg("gloopmother", ModEntities.GLOOPMOTHER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CYCLOS = registerSpawnEgg("cyclos", ModEntities.CYCLOS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CLINGER = registerSpawnEgg("clinger", ModEntities.CLINGER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTDIMTRADER = registerSpawnEgg("deviantdimtrader", ModEntities.DEVIANTDIMTRADER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MEMPUZZLEMERCHANT = registerSpawnEgg("mempuzzlemerchant", ModEntities.MEMPUZZLEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SKYBOOSTER = registerSpawnEgg("skybooster", ModEntities.SKYBOOSTER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ROCKET_STRAPPED_EXPLOSIVE = registerSpawnEgg("rocket_strapped_explosive", ModEntities.ROCKET_STRAPPED_EXPLOSIVE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MARK_OF_DESPAIR = registerSpawnEgg("mark_of_despair", ModEntities.MARK_OF_DESPAIR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SPECTRE = registerSpawnEgg("spectre", ModEntities.SPECTRE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTEST_HOLOGRAM = registerSpawnEgg("contest_hologram", ModEntities.CONTEST_HOLOGRAM, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_MARKET = registerSpawnEgg("contrader_market", ModEntities.CONTRADER_MARKET, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_HOLODECK = registerSpawnEgg("contrader_holodeck", ModEntities.CONTRADER_HOLODECK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_HUNTERS = registerSpawnEgg("contrader_hunters", ModEntities.CONTRADER_HUNTERS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_LIGHTBRIDGE = registerSpawnEgg("contrader_lightbridge", ModEntities.CONTRADER_LIGHTBRIDGE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_TARGETS = registerSpawnEgg("contrader_targets", ModEntities.CONTRADER_TARGETS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_PARKOUR = registerSpawnEgg("contrader_parkour", ModEntities.CONTRADER_PARKOUR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_TRAMPOLINE_DODGEBALL = registerSpawnEgg("contrader_trampoline_dodgeball", ModEntities.CONTRADER_TRAMPOLINE_DODGEBALL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_HOLODECK = registerSpawnEgg("operator_holodeck", ModEntities.OPERATOR_HOLODECK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_HUNTERS = registerSpawnEgg("operator_hunters", ModEntities.OPERATOR_HUNTERS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_LIGHTBRIDGE = registerSpawnEgg("operator_lightbridge", ModEntities.OPERATOR_LIGHTBRIDGE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_DUELARENA = registerSpawnEgg("operator_duelarena", ModEntities.OPERATOR_DUELARENA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_TARGETS = registerSpawnEgg("operator_targets", ModEntities.OPERATOR_TARGETS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_PARKOUR = registerSpawnEgg("operator_parkour", ModEntities.OPERATOR_PARKOUR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_TRAMPOLINE_DODGEBALL = registerSpawnEgg("operator_trampoline_dodgeball", ModEntities.OPERATOR_TRAMPOLINE_DODGEBALL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_HOLODECK = registerSpawnEgg("controller_holodeck", ModEntities.CONTROLLER_HOLODECK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_HUNTERS = registerSpawnEgg("controller_hunters", ModEntities.CONTROLLER_HUNTERS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_TARGETS = registerSpawnEgg("controller_targets", ModEntities.CONTROLLER_TARGETS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_LIGHTBRIDGE = registerSpawnEgg("controller_lightbridge", ModEntities.CONTROLLER_LIGHTBRIDGE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_DUEL_ARENA = registerSpawnEgg("controller_duel_arena", ModEntities.CONTROLLER_DUEL_ARENA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_PARKOUR = registerSpawnEgg("controller_parkour", ModEntities.CONTROLLER_PARKOUR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_TRAMPOLINE_DODGEBALL = registerSpawnEgg("controller_trampoline_dodgeball", ModEntities.CONTROLLER_TRAMPOLINE_DODGEBALL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PARTICLETROJAN = registerSpawnEgg("particletrojan", ModEntities.PARTICLETROJAN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PLASMAEXPLOSION = registerSpawnEgg("plasmaexplosion", ModEntities.PLASMAEXPLOSION, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_AZROSS = registerSpawnEgg("azross", ModEntities.AZROSS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DUSKERQUEEN = registerSpawnEgg("duskerqueen", ModEntities.DUSKERQUEEN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_REDLIGHT = registerSpawnEgg("contrader_redlight", ModEntities.CONTRADER_REDLIGHT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_REDLIGHT = registerSpawnEgg("operator_redlight", ModEntities.OPERATOR_REDLIGHT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_REDLIGHT = registerSpawnEgg("controller_redlight", ModEntities.CONTROLLER_REDLIGHT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANT_WITHER = registerSpawnEgg("deviant_wither", ModEntities.DEVIANT_WITHER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_WITHER_SKULLLING = registerSpawnEgg("wither_skullling", ModEntities.WITHER_SKULLLING, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLANGLER = registerSpawnEgg("glangler", ModEntities.GLANGLER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLOCHIPPER = registerSpawnEgg("glochipper", ModEntities.GLOCHIPPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLOBOON = registerSpawnEgg("globoon", ModEntities.GLOBOON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ESSENCEDWELLER = registerSpawnEgg("essencedweller", ModEntities.ESSENCEDWELLER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ESSENCEIDOL = registerSpawnEgg("essenceidol", ModEntities.ESSENCEIDOL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLOBRO = registerSpawnEgg("globro", ModEntities.GLOBRO, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_AUGMENTICON = registerSpawnEgg("augmenticon", ModEntities.AUGMENTICON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GALAXYGULPER = registerSpawnEgg("galaxygulper", ModEntities.GALAXYGULPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LASERSPIRE = registerSpawnEgg("laserspire", ModEntities.LASERSPIRE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GIANTFLAPPER = registerSpawnEgg("giantflapper", ModEntities.GIANTFLAPPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_IONEXPLOSION = registerSpawnEgg("ionexplosion", ModEntities.IONEXPLOSION, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NITROEXPLOSION = registerSpawnEgg("nitroexplosion", ModEntities.NITROEXPLOSION, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTGOLEM = registerSpawnEgg("deviantgolem", ModEntities.DEVIANTGOLEM, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_STICKYBOMB = registerSpawnEgg("stickybomb", ModEntities.STICKYBOMB, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_VECTOSECT = registerSpawnEgg("vectosect", ModEntities.VECTOSECT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_STICKLER = registerSpawnEgg("stickler", ModEntities.STICKLER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_UNSTABLEMERCHANT = registerSpawnEgg("unstablemerchant", ModEntities.UNSTABLEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FERALMERCHANT = registerSpawnEgg("feralmerchant", ModEntities.FERALMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTCAVESPIDER = registerSpawnEgg("deviantcavespider", ModEntities.DEVIANTCAVESPIDER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TORNINDIVIDUAL = registerSpawnEgg("tornindividual", ModEntities.TORNINDIVIDUAL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RAVAGER = registerSpawnEgg("ravager", ModEntities.RAVAGER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_VYCELLIA = registerSpawnEgg("vycellia", ModEntities.VYCELLIA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PUZZLEMASTER = registerSpawnEgg("puzzlemaster", ModEntities.PUZZLEMASTER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NIGHTSHYRE = registerSpawnEgg("nightshyre", ModEntities.NIGHTSHYRE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GIANTFYREWEED = registerSpawnEgg("giantfyreweed", ModEntities.GIANTFYREWEED, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_BOMBERBOMB = registerSpawnEgg("bomberbomb", ModEntities.BOMBERBOMB, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SKYCRAB = registerSpawnEgg("skycrab", ModEntities.SKYCRAB, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLOMITE = registerSpawnEgg("glomite", ModEntities.GLOMITE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TNTZOMBIE = registerSpawnEgg("tntzombie", ModEntities.TNTZOMBIE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTBAT = registerSpawnEgg("deviantbat", ModEntities.DEVIANTBAT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_BOMBERS = registerSpawnEgg("operator_bombers", ModEntities.OPERATOR_BOMBERS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_BOMBERS = registerSpawnEgg("controller_bombers", ModEntities.CONTROLLER_BOMBERS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_BOMBERS = registerSpawnEgg("contrader_bombers", ModEntities.CONTRADER_BOMBERS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_BATTLE_SNAKES = registerSpawnEgg("operator_battle_snakes", ModEntities.OPERATOR_BATTLE_SNAKES, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_BATTLE_SNAKES = registerSpawnEgg("controller_battle_snakes", ModEntities.CONTROLLER_BATTLE_SNAKES, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_BATTLE_SNAKES = registerSpawnEgg("contrader_battle_snakes", ModEntities.CONTRADER_BATTLE_SNAKES, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_LASER_TAG = registerSpawnEgg("operator_laser_tag", ModEntities.OPERATOR_LASER_TAG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_LASER_TAG = registerSpawnEgg("controller_laser_tag", ModEntities.CONTROLLER_LASER_TAG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_LASER_TAG = registerSpawnEgg("contrader_laser_tag", ModEntities.CONTRADER_LASER_TAG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_INK_BATTLE = registerSpawnEgg("operator_ink_battle", ModEntities.OPERATOR_INK_BATTLE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_INK_BATTLE = registerSpawnEgg("controller_ink_battle", ModEntities.CONTROLLER_INK_BATTLE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_INK_BATTLE = registerSpawnEgg("contrader_ink_battle", ModEntities.CONTRADER_INK_BATTLE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OPERATOR_TREADMILL = registerSpawnEgg("operator_treadmill", ModEntities.OPERATOR_TREADMILL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTROLLER_TREADMILL = registerSpawnEgg("controller_treadmill", ModEntities.CONTROLLER_TREADMILL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONTRADER_TREADMILL = registerSpawnEgg("contrader_treadmill", ModEntities.CONTRADER_TREADMILL, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LIGHTPUZZLEMERCHANT = registerSpawnEgg("lightpuzzlemerchant", ModEntities.LIGHTPUZZLEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ROCKSLUG = registerSpawnEgg("rockslug", ModEntities.ROCKSLUG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GIANT_ROCKSLUG = registerSpawnEgg("giant_rockslug", ModEntities.GIANT_ROCKSLUG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_WHACKGAMEMERCHANT = registerSpawnEgg("whackgamemerchant", ModEntities.WHACKGAMEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FLUTTERBEE = registerSpawnEgg("flutterbee", ModEntities.FLUTTERBEE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CONNECTGAMEMERCHANT = registerSpawnEgg("connectgamemerchant", ModEntities.CONNECTGAMEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RHYTHMGAMEMERCHANT = registerSpawnEgg("rhythmgamemerchant", ModEntities.RHYTHMGAMEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PEARLCOLLECTOR = registerSpawnEgg("pearlcollector", ModEntities.PEARLCOLLECTOR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OZOR = registerSpawnEgg("ozor", ModEntities.OZOR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OZORDECOY = registerSpawnEgg("ozordecoy", ModEntities.OZORDECOY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TOTEMMOON = registerSpawnEgg("totemmoon", ModEntities.TOTEMMOON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TOTEMPYLON = registerSpawnEgg("totempylon", ModEntities.TOTEMPYLON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_THUNDYRON = registerSpawnEgg("thundyron", ModEntities.THUNDYRON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CRYONUS = registerSpawnEgg("cryonus", ModEntities.CRYONUS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_THUNDERBOMB = registerSpawnEgg("thunderbomb", ModEntities.THUNDERBOMB, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_STORMBOMB = registerSpawnEgg("stormbomb", ModEntities.STORMBOMB, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PIPEGAMEMERCHANT = registerSpawnEgg("pipegamemerchant", ModEntities.PIPEGAMEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ZENON = registerSpawnEgg("zenon", ModEntities.ZENON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CRUSHER = registerSpawnEgg("crusher", ModEntities.CRUSHER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DRIPPLER = registerSpawnEgg("drippler", ModEntities.DRIPPLER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GORGER = registerSpawnEgg("gorger", ModEntities.GORGER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DOUBLEJAW = registerSpawnEgg("doublejaw", ModEntities.DOUBLEJAW, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MINIMITE = registerSpawnEgg("minimite", ModEntities.MINIMITE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CLUSTERWEED = registerSpawnEgg("clusterweed", ModEntities.CLUSTERWEED, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_WISP = registerSpawnEgg("wisp", ModEntities.WISP, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TETHERBUG = registerSpawnEgg("tetherbug", ModEntities.TETHERBUG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CELLGAMEMERCHANT = registerSpawnEgg("cellgamemerchant", ModEntities.CELLGAMEMERCHANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_VILEBULB = registerSpawnEgg("vilebulb", ModEntities.VILEBULB, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SIGHTWALKER = registerSpawnEgg("sightwalker", ModEntities.SIGHTWALKER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_WEAVER = registerSpawnEgg("weaver", ModEntities.WEAVER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DOOMDOG = registerSpawnEgg("doomdog", ModEntities.DOOMDOG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_BLISTERWEED = registerSpawnEgg("blisterweed", ModEntities.BLISTERWEED, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GRUBBER = registerSpawnEgg("grubber", ModEntities.GRUBBER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TITANOPOD = registerSpawnEgg("titanopod", ModEntities.TITANOPOD, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SNAPPER = registerSpawnEgg("snapper", ModEntities.SNAPPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FLASHFLY = registerSpawnEgg("flashfly", ModEntities.FLASHFLY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTWITHERSKELETON = registerSpawnEgg("deviantwitherskeleton", ModEntities.DEVIANTWITHERSKELETON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TERRORFLY = registerSpawnEgg("terrorfly", ModEntities.TERRORFLY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TENTACLON = registerSpawnEgg("tentaclon", ModEntities.TENTACLON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GALACTICTERROR = registerSpawnEgg("galacticterror", ModEntities.GALACTICTERROR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTGUARDIAN = registerSpawnEgg("deviantguardian", ModEntities.DEVIANTGUARDIAN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_FORBIDDENBRAND = registerSpawnEgg("forbiddenbrand", ModEntities.FORBIDDENBRAND, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PICKLEMAN = registerSpawnEgg("pickleman", ModEntities.PICKLEMAN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MORTARCANNON = registerSpawnEgg("mortarcannon", ModEntities.MORTARCANNON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CLUSTERCANNON = registerSpawnEgg("clustercannon", ModEntities.CLUSTERCANNON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTOCELOTE = registerSpawnEgg("deviantocelote", ModEntities.DEVIANTOCELOTE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LIVORAX = registerSpawnEgg("livorax", ModEntities.LIVORAX, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LURCHER = registerSpawnEgg("lurcher", ModEntities.LURCHER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NAT = registerSpawnEgg("nat", ModEntities.NAT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SENTRY = registerSpawnEgg("sentry", ModEntities.SENTRY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CAVETERROR = registerSpawnEgg("caveterror", ModEntities.CAVETERROR, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_WHISPER = registerSpawnEgg("whisper", ModEntities.WHISPER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TORPEDON = registerSpawnEgg("torpedon", ModEntities.TORPEDON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RIFT = registerSpawnEgg("rift", ModEntities.RIFT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ORBITER = registerSpawnEgg("orbiter", ModEntities.ORBITER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TOTEMSPLITTER = registerSpawnEgg("totemsplitter", ModEntities.TOTEMSPLITTER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TENTACLETRAP = registerSpawnEgg("tentacletrap", ModEntities.TENTACLETRAP, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SCORPWING = registerSpawnEgg("scorpwing", ModEntities.SCORPWING, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DOOMSDAY = registerSpawnEgg("doomsday", ModEntities.DOOMSDAY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SKYRE = registerSpawnEgg("skyre", ModEntities.SKYRE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ROCKWORM = registerSpawnEgg("rockworm", ModEntities.ROCKWORM, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_KALIKOS = registerSpawnEgg("kalikos", ModEntities.KALIKOS, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GHOSTCOPY = registerSpawnEgg("ghostcopy", ModEntities.GHOSTCOPY, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LEER = registerSpawnEgg("leer", ModEntities.LEER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DOUBLERANG = registerSpawnEgg("doublerang", ModEntities.DOUBLERANG, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LONGFIN = registerSpawnEgg("longfin", ModEntities.LONGFIN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_OCTOBRELLA = registerSpawnEgg("octobrella", ModEntities.OCTOBRELLA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RAYFISH = registerSpawnEgg("rayfish", ModEntities.RAYFISH, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GLOWFISH = registerSpawnEgg("glowfish", ModEntities.GLOWFISH, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANTSQUID = registerSpawnEgg("deviantsquid", ModEntities.DEVIANTSQUID, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_UNDERFIN = registerSpawnEgg("underfin", ModEntities.UNDERFIN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_EELSHARK = registerSpawnEgg("eelshark", ModEntities.EELSHARK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CRABULON = registerSpawnEgg("crabulon", ModEntities.CRABULON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RIBSHARK = registerSpawnEgg("ribshark", ModEntities.RIBSHARK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SCREAMER = registerSpawnEgg("screamer", ModEntities.SCREAMER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NEBULA_GRUNT = registerSpawnEgg("nebula_grunt", ModEntities.NEBULA_GRUNT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NEBULA_WIZARD = registerSpawnEgg("nebula_wizard", ModEntities.NEBULA_WIZARD, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NEBULA_GIANT = registerSpawnEgg("nebula_giant", ModEntities.NEBULA_GIANT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ARCHEOLOGIST = registerSpawnEgg("archeologist", ModEntities.ARCHEOLOGIST, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MULTIVERSEGHOST = registerSpawnEgg("multiverseghost", ModEntities.MULTIVERSEGHOST, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_RISINGPHANTOM = registerSpawnEgg("risingphantom", ModEntities.RISINGPHANTOM, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_TENTACLELANTERN = registerSpawnEgg("tentaclelantern", ModEntities.TENTACLELANTERN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LEVIATHAN = registerSpawnEgg("leviathan", ModEntities.LEVIATHAN, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SEA_SERPENT = registerSpawnEgg("sea_serpent", ModEntities.SEA_SERPENT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_GALAXY_DRAGON = registerSpawnEgg("galaxy_dragon", ModEntities.GALAXY_DRAGON, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_X_SCREACHER = registerSpawnEgg("x_screacher", ModEntities.X_SCREACHER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_LOST_BLADE = registerSpawnEgg("lost_blade", ModEntities.LOST_BLADE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_NUCLEAR_EXPLOSION = registerSpawnEgg("nuclear_explosion", ModEntities.NUCLEAR_EXPLOSION, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MUSHMERRA = registerSpawnEgg("mushmerra", ModEntities.MUSHMERRA, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_MUSHMERRA_CLONE = registerSpawnEgg("mushmerra_clone", ModEntities.MUSHMERRA_CLONE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SHROOMITE = registerSpawnEgg("shroomite", ModEntities.SHROOMITE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_AURA_OF_ALLEGIANCE = registerSpawnEgg("aura_of_allegiance", ModEntities.AURA_OF_ALLEGIANCE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_SUPPLY_TRADER = registerSpawnEgg("supply_trader", ModEntities.SUPPLY_TRADER, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_JET_MOUNT = registerSpawnEgg("jet_mount", ModEntities.JET_MOUNT, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANT_WOLF = registerSpawnEgg("deviant_wolf", ModEntities.DEVIANT_WOLF, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_DEVIANT_HUSK = registerSpawnEgg("deviant_husk", ModEntities.DEVIANT_HUSK, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_BOMB_DRONE = registerSpawnEgg("bomb_drone", ModEntities.BOMB_DRONE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_PLAYER_LIMB = registerSpawnEgg("player_limb", ModEntities.PLAYER_LIMB, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CTHULHU = registerSpawnEgg("cthulhu", ModEntities.CTHULHU, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CTHULHU_TURRET = registerSpawnEgg("cthulhu_turret", ModEntities.CTHULHU_TURRET, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CTHULHU_CLOUD = registerSpawnEgg("cthulhu_cloud", ModEntities.CTHULHU_CLOUD, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CTHULHU_TENTACLE = registerSpawnEgg("cthulhu_tentacle", ModEntities.CTHULHU_TENTACLE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CTHULHU_TENTACLE_PERSIST = registerSpawnEgg("cthulhu_tentacle_persist", ModEntities.CTHULHU_TENTACLE_PERSIST, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CTHULHU_BEAM = registerSpawnEgg("cthulhu_beam", ModEntities.CTHULHU_BEAM, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_CELESTIAL_STATUE = registerSpawnEgg("celestial_statue", ModEntities.CELESTIAL_STATUE, 91102, 0x4B4B4B);
    public static final RegistryObject<Item> SPAWN_EGG_ANDROMEDA = registerSpawnEgg("andromeda", ModEntities.ANDROMEDA, 91102, 0x4B4B4B);

    public static void addToCreativeTab(net.minecraft.world.item.CreativeModeTab.Output output) {
        output.accept(SPAWN_EGG_DIMENSIONALMERCHANT.get());
        output.accept(SPAWN_EGG_DEVIANTBEAR.get());
        output.accept(SPAWN_EGG_TREADMILLOBSTACLE.get());
        output.accept(SPAWN_EGG_TREADMILLOBSTACLEJUMPABLE.get());
        output.accept(SPAWN_EGG_DEVIANTGHAST.get());
        output.accept(SPAWN_EGG_DEVIANTCOW.get());
        output.accept(SPAWN_EGG_DEVIANTSHEEP.get());
        output.accept(SPAWN_EGG_DEVIANTHORSE.get());
        output.accept(SPAWN_EGG_DEVIANTPIG.get());
        output.accept(SPAWN_EGG_DEVIANTEVOKER.get());
        output.accept(SPAWN_EGG_DEVIANTEVOKERVEX.get());
        output.accept(SPAWN_EGG_DEVIANTENDERMAN.get());
        output.accept(SPAWN_EGG_DEVIANTCHICKEN.get());
        output.accept(SPAWN_EGG_DEVIANTSHULKER.get());
        output.accept(SPAWN_EGG_DEVIANTSKYWORM.get());
        output.accept(SPAWN_EGG_ELARA.get());
        output.accept(SPAWN_EGG_INFINITYSTONE.get());
        output.accept(SPAWN_EGG_DEVIANTCREEPER.get());
        output.accept(SPAWN_EGG_DEVIANTSKELETON.get());
        output.accept(SPAWN_EGG_UROGO.get());
        output.accept(SPAWN_EGG_DROID.get());
        output.accept(SPAWN_EGG_DROIDBOSS.get());
        output.accept(SPAWN_EGG_LOSTDEVIANT.get());
        output.accept(SPAWN_EGG_ARENAEVENT.get());
        output.accept(SPAWN_EGG_LABWARRIOR.get());
        output.accept(SPAWN_EGG_LABWIZARD.get());
        output.accept(SPAWN_EGG_DEVIANTSPIDER.get());
        output.accept(SPAWN_EGG_ASPECT.get());
        output.accept(SPAWN_EGG_SLIMESTRIDER.get());
        output.accept(SPAWN_EGG_VELO.get());
        output.accept(SPAWN_EGG_GALAXYBEAST.get());
        output.accept(SPAWN_EGG_GALAXYSORCERER.get());
        output.accept(SPAWN_EGG_GALAXYGLADIATOR.get());
        output.accept(SPAWN_EGG_GALAXYSPIRE.get());
        output.accept(SPAWN_EGG_DEVIANTAMALGAM.get());
        output.accept(SPAWN_EGG_STARFIEND.get());
        output.accept(SPAWN_EGG_BLOODHUNTER.get());
        output.accept(SPAWN_EGG_FUNGFLY.get());
        output.accept(SPAWN_EGG_RIKARUS.get());
        output.accept(SPAWN_EGG_RESTORATIONCRYSTAL.get());
        output.accept(SPAWN_EGG_DEVIANTWITCH.get());
        output.accept(SPAWN_EGG_MIRRORZOMBIE.get());
        output.accept(SPAWN_EGG_DEVIANTSLIMESTRIDER.get());
        output.accept(SPAWN_EGG_CHEMIST.get());
        output.accept(SPAWN_EGG_SANDATTACK.get());
        output.accept(SPAWN_EGG_DEVIANTBLAZE.get());
        output.accept(SPAWN_EGG_TITANBLAZE.get());
        output.accept(SPAWN_EGG_TITANSHULKER.get());
        output.accept(SPAWN_EGG_TITANSPIDER.get());
        output.accept(SPAWN_EGG_TITANSKELETON.get());
        output.accept(SPAWN_EGG_TRIALOBSERVER.get());
        output.accept(SPAWN_EGG_REFLECTAL.get());
        output.accept(SPAWN_EGG_LUMINOUSGUARDIAN.get());
        output.accept(SPAWN_EGG_HANGER.get());
        output.accept(SPAWN_EGG_ACIDBACK.get());
        output.accept(SPAWN_EGG_GRAVHEAD.get());
        output.accept(SPAWN_EGG_ROCKPEST.get());
        output.accept(SPAWN_EGG_SPINOVERN.get());
        output.accept(SPAWN_EGG_HYPNOSAUR.get());
        output.accept(SPAWN_EGG_CHOMPER.get());
        output.accept(SPAWN_EGG_RIBREX.get());
        output.accept(SPAWN_EGG_GNAWER.get());
        output.accept(SPAWN_EGG_SCREACHER.get());
        output.accept(SPAWN_EGG_EYESLUG.get());
        output.accept(SPAWN_EGG_FLUTTERFYRE.get());
        output.accept(SPAWN_EGG_DEVIANTSNOWMAN.get());
        output.accept(SPAWN_EGG_NUXURO.get());
        output.accept(SPAWN_EGG_CLYSTER.get());
        output.accept(SPAWN_EGG_CRAWKER.get());
        output.accept(SPAWN_EGG_DUSKER.get());
        output.accept(SPAWN_EGG_EXPLOSECT.get());
        output.accept(SPAWN_EGG_FLAPPER.get());
        output.accept(SPAWN_EGG_FLURKY.get());
        output.accept(SPAWN_EGG_FYREWEED.get());
        output.accept(SPAWN_EGG_GRAPPLER.get());
        output.accept(SPAWN_EGG_HURLER.get());
        output.accept(SPAWN_EGG_PHASER.get());
        output.accept(SPAWN_EGG_SHIMMER.get());
        output.accept(SPAWN_EGG_SPYKER.get());
        output.accept(SPAWN_EGG_DEVIANTMOOSHROOM.get());
        output.accept(SPAWN_EGG_DEVIANTZOMBIE.get());
        output.accept(SPAWN_EGG_DEVIANTSLIME.get());
        output.accept(SPAWN_EGG_ARASH.get());
        output.accept(SPAWN_EGG_ALESTRIA.get());
        output.accept(SPAWN_EGG_ATLASSPIRE.get());
        output.accept(SPAWN_EGG_DARRIO.get());
        output.accept(SPAWN_EGG_BARUL.get());
        output.accept(SPAWN_EGG_SENTRYCRYSTAL.get());
        output.accept(SPAWN_EGG_ATLASCRYSTAL.get());
        output.accept(SPAWN_EGG_DEVIANTCRYSTAL.get());
        output.accept(SPAWN_EGG_DEVIANTLLAMA.get());
        output.accept(SPAWN_EGG_DEVIANTMAGMACUBE.get());
        output.accept(SPAWN_EGG_DEVIANTVEX.get());
        output.accept(SPAWN_EGG_DEVIANTSTRAY.get());
        output.accept(SPAWN_EGG_DEVIANTPIGLIN.get());
        output.accept(SPAWN_EGG_TITANCREEPER.get());
        output.accept(SPAWN_EGG_TITANENDERMAN.get());
        output.accept(SPAWN_EGG_TITANLLAMA.get());
        output.accept(SPAWN_EGG_TITANMAGMACUBE.get());
        output.accept(SPAWN_EGG_TITANPIGLIN.get());
        output.accept(SPAWN_EGG_TITANSTRAY.get());
        output.accept(SPAWN_EGG_COURSERING.get());
        output.accept(SPAWN_EGG_TITANVEX.get());
        output.accept(SPAWN_EGG_TITANZOMBIE.get());
        output.accept(SPAWN_EGG_GLOOP.get());
        output.accept(SPAWN_EGG_GLOOPMOTHER.get());
        output.accept(SPAWN_EGG_CYCLOS.get());
        output.accept(SPAWN_EGG_CLINGER.get());
        output.accept(SPAWN_EGG_DEVIANTDIMTRADER.get());
        output.accept(SPAWN_EGG_MEMPUZZLEMERCHANT.get());
        output.accept(SPAWN_EGG_SKYBOOSTER.get());
        output.accept(SPAWN_EGG_ROCKET_STRAPPED_EXPLOSIVE.get());
        output.accept(SPAWN_EGG_MARK_OF_DESPAIR.get());
        output.accept(SPAWN_EGG_SPECTRE.get());
        output.accept(SPAWN_EGG_CONTEST_HOLOGRAM.get());
        output.accept(SPAWN_EGG_CONTRADER_MARKET.get());
        output.accept(SPAWN_EGG_CONTRADER_HOLODECK.get());
        output.accept(SPAWN_EGG_CONTRADER_HUNTERS.get());
        output.accept(SPAWN_EGG_CONTRADER_LIGHTBRIDGE.get());
        output.accept(SPAWN_EGG_CONTRADER_TARGETS.get());
        output.accept(SPAWN_EGG_CONTRADER_PARKOUR.get());
        output.accept(SPAWN_EGG_CONTRADER_TRAMPOLINE_DODGEBALL.get());
        output.accept(SPAWN_EGG_OPERATOR_HOLODECK.get());
        output.accept(SPAWN_EGG_OPERATOR_HUNTERS.get());
        output.accept(SPAWN_EGG_OPERATOR_LIGHTBRIDGE.get());
        output.accept(SPAWN_EGG_OPERATOR_DUELARENA.get());
        output.accept(SPAWN_EGG_OPERATOR_TARGETS.get());
        output.accept(SPAWN_EGG_OPERATOR_PARKOUR.get());
        output.accept(SPAWN_EGG_OPERATOR_TRAMPOLINE_DODGEBALL.get());
        output.accept(SPAWN_EGG_CONTROLLER_HOLODECK.get());
        output.accept(SPAWN_EGG_CONTROLLER_HUNTERS.get());
        output.accept(SPAWN_EGG_CONTROLLER_TARGETS.get());
        output.accept(SPAWN_EGG_CONTROLLER_LIGHTBRIDGE.get());
        output.accept(SPAWN_EGG_CONTROLLER_DUEL_ARENA.get());
        output.accept(SPAWN_EGG_CONTROLLER_PARKOUR.get());
        output.accept(SPAWN_EGG_CONTROLLER_TRAMPOLINE_DODGEBALL.get());
        output.accept(SPAWN_EGG_PARTICLETROJAN.get());
        output.accept(SPAWN_EGG_PLASMAEXPLOSION.get());
        output.accept(SPAWN_EGG_AZROSS.get());
        output.accept(SPAWN_EGG_DUSKERQUEEN.get());
        output.accept(SPAWN_EGG_CONTRADER_REDLIGHT.get());
        output.accept(SPAWN_EGG_OPERATOR_REDLIGHT.get());
        output.accept(SPAWN_EGG_CONTROLLER_REDLIGHT.get());
        output.accept(SPAWN_EGG_DEVIANT_WITHER.get());
        output.accept(SPAWN_EGG_WITHER_SKULLLING.get());
        output.accept(SPAWN_EGG_GLANGLER.get());
        output.accept(SPAWN_EGG_GLOCHIPPER.get());
        output.accept(SPAWN_EGG_GLOBOON.get());
        output.accept(SPAWN_EGG_ESSENCEDWELLER.get());
        output.accept(SPAWN_EGG_ESSENCEIDOL.get());
        output.accept(SPAWN_EGG_GLOBRO.get());
        output.accept(SPAWN_EGG_AUGMENTICON.get());
        output.accept(SPAWN_EGG_GALAXYGULPER.get());
        output.accept(SPAWN_EGG_LASERSPIRE.get());
        output.accept(SPAWN_EGG_GIANTFLAPPER.get());
        output.accept(SPAWN_EGG_IONEXPLOSION.get());
        output.accept(SPAWN_EGG_NITROEXPLOSION.get());
        output.accept(SPAWN_EGG_DEVIANTGOLEM.get());
        output.accept(SPAWN_EGG_STICKYBOMB.get());
        output.accept(SPAWN_EGG_VECTOSECT.get());
        output.accept(SPAWN_EGG_STICKLER.get());
        output.accept(SPAWN_EGG_UNSTABLEMERCHANT.get());
        output.accept(SPAWN_EGG_FERALMERCHANT.get());
        output.accept(SPAWN_EGG_DEVIANTCAVESPIDER.get());
        output.accept(SPAWN_EGG_TORNINDIVIDUAL.get());
        output.accept(SPAWN_EGG_RAVAGER.get());
        output.accept(SPAWN_EGG_VYCELLIA.get());
        output.accept(SPAWN_EGG_PUZZLEMASTER.get());
        output.accept(SPAWN_EGG_NIGHTSHYRE.get());
        output.accept(SPAWN_EGG_GIANTFYREWEED.get());
        output.accept(SPAWN_EGG_BOMBERBOMB.get());
        output.accept(SPAWN_EGG_SKYCRAB.get());
        output.accept(SPAWN_EGG_GLOMITE.get());
        output.accept(SPAWN_EGG_TNTZOMBIE.get());
        output.accept(SPAWN_EGG_DEVIANTBAT.get());
        output.accept(SPAWN_EGG_OPERATOR_BOMBERS.get());
        output.accept(SPAWN_EGG_CONTROLLER_BOMBERS.get());
        output.accept(SPAWN_EGG_CONTRADER_BOMBERS.get());
        output.accept(SPAWN_EGG_OPERATOR_BATTLE_SNAKES.get());
        output.accept(SPAWN_EGG_CONTROLLER_BATTLE_SNAKES.get());
        output.accept(SPAWN_EGG_CONTRADER_BATTLE_SNAKES.get());
        output.accept(SPAWN_EGG_OPERATOR_LASER_TAG.get());
        output.accept(SPAWN_EGG_CONTROLLER_LASER_TAG.get());
        output.accept(SPAWN_EGG_CONTRADER_LASER_TAG.get());
        output.accept(SPAWN_EGG_OPERATOR_INK_BATTLE.get());
        output.accept(SPAWN_EGG_CONTROLLER_INK_BATTLE.get());
        output.accept(SPAWN_EGG_CONTRADER_INK_BATTLE.get());
        output.accept(SPAWN_EGG_OPERATOR_TREADMILL.get());
        output.accept(SPAWN_EGG_CONTROLLER_TREADMILL.get());
        output.accept(SPAWN_EGG_CONTRADER_TREADMILL.get());
        output.accept(SPAWN_EGG_LIGHTPUZZLEMERCHANT.get());
        output.accept(SPAWN_EGG_ROCKSLUG.get());
        output.accept(SPAWN_EGG_GIANT_ROCKSLUG.get());
        output.accept(SPAWN_EGG_WHACKGAMEMERCHANT.get());
        output.accept(SPAWN_EGG_FLUTTERBEE.get());
        output.accept(SPAWN_EGG_CONNECTGAMEMERCHANT.get());
        output.accept(SPAWN_EGG_RHYTHMGAMEMERCHANT.get());
        output.accept(SPAWN_EGG_PEARLCOLLECTOR.get());
        output.accept(SPAWN_EGG_OZOR.get());
        output.accept(SPAWN_EGG_OZORDECOY.get());
        output.accept(SPAWN_EGG_TOTEMMOON.get());
        output.accept(SPAWN_EGG_TOTEMPYLON.get());
        output.accept(SPAWN_EGG_THUNDYRON.get());
        output.accept(SPAWN_EGG_CRYONUS.get());
        output.accept(SPAWN_EGG_THUNDERBOMB.get());
        output.accept(SPAWN_EGG_STORMBOMB.get());
        output.accept(SPAWN_EGG_PIPEGAMEMERCHANT.get());
        output.accept(SPAWN_EGG_ZENON.get());
        output.accept(SPAWN_EGG_CRUSHER.get());
        output.accept(SPAWN_EGG_DRIPPLER.get());
        output.accept(SPAWN_EGG_GORGER.get());
        output.accept(SPAWN_EGG_DOUBLEJAW.get());
        output.accept(SPAWN_EGG_MINIMITE.get());
        output.accept(SPAWN_EGG_CLUSTERWEED.get());
        output.accept(SPAWN_EGG_WISP.get());
        output.accept(SPAWN_EGG_TETHERBUG.get());
        output.accept(SPAWN_EGG_CELLGAMEMERCHANT.get());
        output.accept(SPAWN_EGG_VILEBULB.get());
        output.accept(SPAWN_EGG_SIGHTWALKER.get());
        output.accept(SPAWN_EGG_WEAVER.get());
        output.accept(SPAWN_EGG_DOOMDOG.get());
        output.accept(SPAWN_EGG_BLISTERWEED.get());
        output.accept(SPAWN_EGG_GRUBBER.get());
        output.accept(SPAWN_EGG_TITANOPOD.get());
        output.accept(SPAWN_EGG_SNAPPER.get());
        output.accept(SPAWN_EGG_FLASHFLY.get());
        output.accept(SPAWN_EGG_DEVIANTWITHERSKELETON.get());
        output.accept(SPAWN_EGG_TERRORFLY.get());
        output.accept(SPAWN_EGG_TENTACLON.get());
        output.accept(SPAWN_EGG_GALACTICTERROR.get());
        output.accept(SPAWN_EGG_DEVIANTGUARDIAN.get());
        output.accept(SPAWN_EGG_FORBIDDENBRAND.get());
        output.accept(SPAWN_EGG_PICKLEMAN.get());
        output.accept(SPAWN_EGG_MORTARCANNON.get());
        output.accept(SPAWN_EGG_CLUSTERCANNON.get());
        output.accept(SPAWN_EGG_DEVIANTOCELOTE.get());
        output.accept(SPAWN_EGG_LIVORAX.get());
        output.accept(SPAWN_EGG_LURCHER.get());
        output.accept(SPAWN_EGG_NAT.get());
        output.accept(SPAWN_EGG_SENTRY.get());
        output.accept(SPAWN_EGG_CAVETERROR.get());
        output.accept(SPAWN_EGG_WHISPER.get());
        output.accept(SPAWN_EGG_TORPEDON.get());
        output.accept(SPAWN_EGG_RIFT.get());
        output.accept(SPAWN_EGG_ORBITER.get());
        output.accept(SPAWN_EGG_TOTEMSPLITTER.get());
        output.accept(SPAWN_EGG_TENTACLETRAP.get());
        output.accept(SPAWN_EGG_SCORPWING.get());
        output.accept(SPAWN_EGG_DOOMSDAY.get());
        output.accept(SPAWN_EGG_SKYRE.get());
        output.accept(SPAWN_EGG_ROCKWORM.get());
        output.accept(SPAWN_EGG_KALIKOS.get());
        output.accept(SPAWN_EGG_GHOSTCOPY.get());
        output.accept(SPAWN_EGG_LEER.get());
        output.accept(SPAWN_EGG_DOUBLERANG.get());
        output.accept(SPAWN_EGG_LONGFIN.get());
        output.accept(SPAWN_EGG_OCTOBRELLA.get());
        output.accept(SPAWN_EGG_RAYFISH.get());
        output.accept(SPAWN_EGG_GLOWFISH.get());
        output.accept(SPAWN_EGG_DEVIANTSQUID.get());
        output.accept(SPAWN_EGG_UNDERFIN.get());
        output.accept(SPAWN_EGG_EELSHARK.get());
        output.accept(SPAWN_EGG_CRABULON.get());
        output.accept(SPAWN_EGG_RIBSHARK.get());
        output.accept(SPAWN_EGG_SCREAMER.get());
        output.accept(SPAWN_EGG_NEBULA_GRUNT.get());
        output.accept(SPAWN_EGG_NEBULA_WIZARD.get());
        output.accept(SPAWN_EGG_NEBULA_GIANT.get());
        output.accept(SPAWN_EGG_ARCHEOLOGIST.get());
        output.accept(SPAWN_EGG_MULTIVERSEGHOST.get());
        output.accept(SPAWN_EGG_RISINGPHANTOM.get());
        output.accept(SPAWN_EGG_TENTACLELANTERN.get());
        output.accept(SPAWN_EGG_LEVIATHAN.get());
        output.accept(SPAWN_EGG_SEA_SERPENT.get());
        output.accept(SPAWN_EGG_GALAXY_DRAGON.get());
        output.accept(SPAWN_EGG_X_SCREACHER.get());
        output.accept(SPAWN_EGG_LOST_BLADE.get());
        output.accept(SPAWN_EGG_NUCLEAR_EXPLOSION.get());
        output.accept(SPAWN_EGG_MUSHMERRA.get());
        output.accept(SPAWN_EGG_MUSHMERRA_CLONE.get());
        output.accept(SPAWN_EGG_SHROOMITE.get());
        output.accept(SPAWN_EGG_AURA_OF_ALLEGIANCE.get());
        output.accept(SPAWN_EGG_SUPPLY_TRADER.get());
        output.accept(SPAWN_EGG_JET_MOUNT.get());
        output.accept(SPAWN_EGG_DEVIANT_WOLF.get());
        output.accept(SPAWN_EGG_DEVIANT_HUSK.get());
        output.accept(SPAWN_EGG_BOMB_DRONE.get());
        output.accept(SPAWN_EGG_PLAYER_LIMB.get());
        output.accept(SPAWN_EGG_CTHULHU.get());
        output.accept(SPAWN_EGG_CTHULHU_TURRET.get());
        output.accept(SPAWN_EGG_CTHULHU_CLOUD.get());
        output.accept(SPAWN_EGG_CTHULHU_TENTACLE.get());
        output.accept(SPAWN_EGG_CTHULHU_TENTACLE_PERSIST.get());
        output.accept(SPAWN_EGG_CTHULHU_BEAM.get());
        output.accept(SPAWN_EGG_CELESTIAL_STATUE.get());
        output.accept(SPAWN_EGG_ANDROMEDA.get());
    }
}
