/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  jeresources.api.IDungeonRegistry
 *  jeresources.api.IJERAPI
 *  jeresources.api.IMobRegistry
 *  jeresources.api.IPlantRegistry
 *  jeresources.api.IWorldGenRegistry
 *  jeresources.api.JERPlugin
 *  jeresources.api.conditionals.Conditional
 *  jeresources.api.distributions.DistributionBase
 *  jeresources.api.distributions.DistributionSquare
 *  jeresources.api.drop.LootDrop
 *  jeresources.api.drop.PlantDrop
 *  jeresources.api.render.TextModifier
 *  jeresources.api.restrictions.DimensionRestriction
 *  jeresources.api.restrictions.Restriction
 *  net.minecraft.block.state.BlockState
 *  net.minecraft.entity.LivingEntity
 *  net.minecraft.init.Blocks
 *  net.minecraft.item.Item
 *  net.minecraft.item.ItemStack
 *  net.minecraft.world.World
 *  net.minecraftforge.fml.common.Loader
 */
package xol.lostinfinity.util.compatibility.jer;

import jeresources.api.IDungeonRegistry;
import jeresources.api.IJERAPI;
import jeresources.api.IMobRegistry;
import jeresources.api.IPlantRegistry;
import jeresources.api.IWorldGenRegistry;
import jeresources.api.JERPlugin;
import jeresources.api.conditionals.Conditional;
import jeresources.api.distributions.DistributionBase;
import jeresources.api.distributions.DistributionSquare;
import jeresources.api.drop.LootDrop;
import jeresources.api.drop.PlantDrop;
import jeresources.api.render.TextModifier;
import jeresources.api.restrictions.DimensionRestriction;
import jeresources.api.restrictions.Restriction;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraftforge.fml.common.Loader;
import xol.lostinfinity.init.BlockInit;
import xol.lostinfinity.init.DimensionInit;
import xol.lostinfinity.init.ItemInit;
import xol.lostinfinity.item.basics.ItemBasicSeeds;
import xol.lostinfinity.mob.entity.boss.EntityAlestria;
import xol.lostinfinity.mob.entity.boss.EntityArash;
import xol.lostinfinity.mob.entity.boss.EntityAtlasSpire;
import xol.lostinfinity.mob.entity.boss.EntityBarul;
import xol.lostinfinity.mob.entity.boss.EntityCryonus;
import xol.lostinfinity.mob.entity.boss.EntityDarrio;
import xol.lostinfinity.mob.entity.boss.EntityDeviantWither;
import xol.lostinfinity.mob.entity.boss.EntityDuskerQueen;
import xol.lostinfinity.mob.entity.boss.EntityElara;
import xol.lostinfinity.mob.entity.boss.EntityNuxuro;
import xol.lostinfinity.mob.entity.boss.EntityOzor;
import xol.lostinfinity.mob.entity.boss.EntityRikarus;
import xol.lostinfinity.mob.entity.boss.EntityThundyron;
import xol.lostinfinity.mob.entity.boss.EntityUrogo;
import xol.lostinfinity.mob.entity.boss.EntityVelo;
import xol.lostinfinity.mob.entity.boss.EntityVycellia;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBat;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBear;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantBlaze;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCaveSpider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantChicken;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCow;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantCreeper;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantDimTrader;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEnderman;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantEvoker;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGhast;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGolem;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantGuardian;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantHorse;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantHusk;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantLlama;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantMagmacube;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantMooshroom;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantOcelote;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantPig;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantPiglin;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSheep;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantShulker;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSkeleton;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSkyworm;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSlime;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSlimeStrider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSnowman;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSpider;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantSquid;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantStray;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantVex;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWitch;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWitherSkeleton;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantWolf;
import xol.lostinfinity.mob.entity.deviant.EntityDeviantZombie;
import xol.lostinfinity.mob.entity.deviant.prime.EntityAzross;
import xol.lostinfinity.mob.entity.deviant.prime.EntityKalikos;
import xol.lostinfinity.mob.entity.deviant.prime.EntityLivorax;
import xol.lostinfinity.mob.entity.deviant.prime.EntityZenon;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanBlaze;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanCreeper;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanEnderman;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanLlama;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanMagmacube;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanPiglin;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanShulker;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanSkeleton;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanSpider;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanStray;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanVex;
import xol.lostinfinity.mob.entity.deviant.titan.EntityTitanZombie;
import xol.lostinfinity.mob.entity.fungal.EntityMushmerra;
import xol.lostinfinity.mob.entity.fungal.EntityShroomite;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyBeast;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyGladiator;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxyGulper;
import xol.lostinfinity.mob.entity.galaxy.EntityGalaxySorcerer;
import xol.lostinfinity.mob.entity.labyrinth.EntityClinger;
import xol.lostinfinity.mob.entity.labyrinth.EntityGloopMother;
import xol.lostinfinity.mob.entity.misc.EntityMirrorZombie;
import xol.lostinfinity.mob.entity.misc.EntitySlimeStrider;
import xol.lostinfinity.mob.entity.misc.EntityStarfiend;
import xol.lostinfinity.mob.entity.murk.EntityCaveTerror;
import xol.lostinfinity.mob.entity.murk.EntityDoomsday;
import xol.lostinfinity.mob.entity.murk.EntityScorpwing;
import xol.lostinfinity.mob.entity.murk.EntitySkyre;
import xol.lostinfinity.mob.entity.murk.EntityTorpedon;
import xol.lostinfinity.mob.entity.sea.EntityCrabulon;
import xol.lostinfinity.mob.entity.sea.EntityEelShark;
import xol.lostinfinity.mob.entity.sea.seaserpent.EntitySeaSerpentController;
import xol.lostinfinity.mob.entity.starforge.EntityAugmenticon;
import xol.lostinfinity.mob.entity.starforge.EntityBlisterweed;
import xol.lostinfinity.mob.entity.starforge.EntityChomper;
import xol.lostinfinity.mob.entity.starforge.EntityClusterweed;
import xol.lostinfinity.mob.entity.starforge.EntityClyster;
import xol.lostinfinity.mob.entity.starforge.EntityCrawker;
import xol.lostinfinity.mob.entity.starforge.EntityCrusher;
import xol.lostinfinity.mob.entity.starforge.EntityDoomDog;
import xol.lostinfinity.mob.entity.starforge.EntityDoublejaw;
import xol.lostinfinity.mob.entity.starforge.EntityDrippler;
import xol.lostinfinity.mob.entity.starforge.EntityDusker;
import xol.lostinfinity.mob.entity.starforge.EntityExplosect;
import xol.lostinfinity.mob.entity.starforge.EntityEyeSlug;
import xol.lostinfinity.mob.entity.starforge.EntityFlapper;
import xol.lostinfinity.mob.entity.starforge.EntityFlurky;
import xol.lostinfinity.mob.entity.starforge.EntityFlutterbee;
import xol.lostinfinity.mob.entity.starforge.EntityFyreweed;
import xol.lostinfinity.mob.entity.starforge.EntityGalacticTerror;
import xol.lostinfinity.mob.entity.starforge.EntityGiantFlapper;
import xol.lostinfinity.mob.entity.starforge.EntityGiantFyreweed;
import xol.lostinfinity.mob.entity.starforge.EntityGlangler;
import xol.lostinfinity.mob.entity.starforge.EntityGloboon;
import xol.lostinfinity.mob.entity.starforge.EntityGlobro;
import xol.lostinfinity.mob.entity.starforge.EntityGlochipper;
import xol.lostinfinity.mob.entity.starforge.EntityGlomite;
import xol.lostinfinity.mob.entity.starforge.EntityGnawer;
import xol.lostinfinity.mob.entity.starforge.EntityGorger;
import xol.lostinfinity.mob.entity.starforge.EntityGrappler;
import xol.lostinfinity.mob.entity.starforge.EntityGravhead;
import xol.lostinfinity.mob.entity.starforge.EntityGrubber;
import xol.lostinfinity.mob.entity.starforge.EntityHurler;
import xol.lostinfinity.mob.entity.starforge.EntityHypnosaur;
import xol.lostinfinity.mob.entity.starforge.EntityLeer;
import xol.lostinfinity.mob.entity.starforge.EntityLurcher;
import xol.lostinfinity.mob.entity.starforge.EntityMinimite;
import xol.lostinfinity.mob.entity.starforge.EntityOrbiter;
import xol.lostinfinity.mob.entity.starforge.EntityPhaser;
import xol.lostinfinity.mob.entity.starforge.EntityRavager;
import xol.lostinfinity.mob.entity.starforge.EntityReflectal;
import xol.lostinfinity.mob.entity.starforge.EntityRibrex;
import xol.lostinfinity.mob.entity.starforge.EntityRockpest;
import xol.lostinfinity.mob.entity.starforge.EntityRockslug;
import xol.lostinfinity.mob.entity.starforge.EntityScreacher;
import xol.lostinfinity.mob.entity.starforge.EntityShimmer;
import xol.lostinfinity.mob.entity.starforge.EntitySightwalker;
import xol.lostinfinity.mob.entity.starforge.EntitySnapper;
import xol.lostinfinity.mob.entity.starforge.EntitySpinovern;
import xol.lostinfinity.mob.entity.starforge.EntitySpyker;
import xol.lostinfinity.mob.entity.starforge.EntityTentaclon;
import xol.lostinfinity.mob.entity.starforge.EntityTerrorFly;
import xol.lostinfinity.mob.entity.starforge.EntityTetherbug;
import xol.lostinfinity.mob.entity.starforge.EntityTitanopod;
import xol.lostinfinity.mob.entity.starforge.EntityVilebulb;
import xol.lostinfinity.mob.entity.starforge.EntityWeaver;
import xol.lostinfinity.util.load.LootTableRegistry;

public class JERCompatibility {
    @JERPlugin
    public static IJERAPI jerAPI;

    public static void init() {
        if (!Loader.isModLoaded((String)"jeresources")) {
            return;
        }
        IPlantRegistry plantRegistry = jerAPI.getPlantRegistry();
        IWorldGenRegistry worldGenRegistry = jerAPI.getWorldGenRegistry();
        IDungeonRegistry dungeonRegistry = jerAPI.getDungeonRegistry();
        Conditional celestialPickaxe = new Conditional("Requires Celestial Pickaxe", new TextModifier[0]);
        Level world = jerAPI.getWorld();
        worldGenRegistry.registerDrops(new ItemStack(Blocks.field_150482_ag), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.celestialDiamond), 0, 1, new Conditional[]{celestialPickaxe})});
        worldGenRegistry.registerDrops(new ItemStack(Blocks.field_150412_bA), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.celestialEmerald), 0, 1, new Conditional[]{celestialPickaxe})});
        worldGenRegistry.registerDrops(new ItemStack(Blocks.field_150450_ax), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.celestialRedstone), 0, 1, new Conditional[]{celestialPickaxe})});
        worldGenRegistry.registerDrops(new ItemStack(Blocks.field_150449_bY), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.celestialQuartz), 0, 1, new Conditional[]{celestialPickaxe})});
        worldGenRegistry.registerDrops(new ItemStack(Blocks.field_150366_p), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.celestialIron), 0, 1, new Conditional[]{celestialPickaxe})});
        worldGenRegistry.register(new ItemStack(BlockInit.oreEmberium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.emberium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreHextorium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.hextorium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreCrystonium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.crystonium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreAstrallium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.astrallium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreKylaxium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.kylaxium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreVellorium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.vellorium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreIncadium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.incadium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreNoxerium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.noxerium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreolysium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.olysium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreDetherium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.detherium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.oreXerovium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.xerovium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.orePhytrosium), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.phytrosium), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.exothermiteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.impureExothermite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.lumioOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.luminessence), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.cloviniteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.clovinite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.myriteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.myrite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.prismosisOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.prismosisShards), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.cellularOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.cellularCrystal), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.serpentineOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.serpentineCrystal), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.gloominessenceOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.gloominessence), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.auradineOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.auradine), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.phototenzyteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.phototenzyte), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.incandesciteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.incandescite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.catatoniteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.catatoniteShard), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.ioniteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.ionite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.hivenite), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.hivenite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.logsMurk), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.murkyLog), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.leavesCelestialPurple), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.inverseMagnecronite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.sunderwoodSap), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.burningSap), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.sunderwood), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.sunderLog), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.logsCelestial), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.positiveMagnecronite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.logsCelestialRed), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.negativeMagnecronite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.logsMetalloid), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.metalBranch), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.darksteelOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.infiniteMurk)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.darksteelShards), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.sunstoneOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.sunstone), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.synchroniteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.nonexistence)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.synchroniteTypeA), 1.0f), new LootDrop(new ItemStack(ItemInit.synchroniteTypeB), 1.0f), new LootDrop(new ItemStack(ItemInit.synchroniteTypeC), 1.0f), new LootDrop(new ItemStack(ItemInit.synchroniteTypeD), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.multiversiteOverworld), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.infiniteMurk)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.fracturedMultiversite), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.lucientOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.infiniteMurk)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.lucient), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.atomiteOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.infiniteMurk)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.atomiteFragments), 1.0f)});
        worldGenRegistry.register(new ItemStack(BlockInit.igneousPearlOre), (DistributionBase)new DistributionSquare(1, 1, 80, 146), new Restriction(new DimensionRestriction(DimensionInit.shadowSea)), new LootDrop[]{new LootDrop(new ItemStack(ItemInit.pearlIgneous), 1.0f)});
        IMobRegistry mobRegistry = jerAPI.getMobRegistry();
        EntityAugmenticon augmenticonZero = new EntityAugmenticon(world);
        augmenticonZero.func_96094_a("Augmenticon Zero");
        mobRegistry.register((LivingEntity)augmenticonZero, LootTableRegistry.ENTITIES_AUGMENTICON_0);
        EntityAugmenticon augmenticonOne = new EntityAugmenticon(world);
        augmenticonOne.func_96094_a("Augmenticon One");
        mobRegistry.register((LivingEntity)augmenticonOne, LootTableRegistry.ENTITIES_AUGMENTICON_1);
        EntityAugmenticon augmenticonTwo = new EntityAugmenticon(world);
        augmenticonTwo.func_96094_a("Augmenticon Two");
        mobRegistry.register((LivingEntity)augmenticonTwo, LootTableRegistry.ENTITIES_AUGMENTICON_2);
        EntityAugmenticon augmenticonThree = new EntityAugmenticon(world);
        augmenticonThree.func_96094_a("Augmenticon Three");
        mobRegistry.register((LivingEntity)augmenticonThree, LootTableRegistry.ENTITIES_AUGMENTICON_3);
        EntityAugmenticon augmenticonFour = new EntityAugmenticon(world);
        augmenticonFour.func_96094_a("Augmenticon Four");
        mobRegistry.register((LivingEntity)augmenticonFour, LootTableRegistry.ENTITIES_AUGMENTICON_4);
        EntityAugmenticon augmenticonFive = new EntityAugmenticon(world);
        augmenticonFive.func_96094_a("Augmenticon Five");
        mobRegistry.register((LivingEntity)augmenticonFive, LootTableRegistry.ENTITIES_AUGMENTICON_5);
        EntityAzross azross = new EntityAzross(world);
        mobRegistry.register((LivingEntity)azross, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.deviantFragmentTR))});
        EntityClyster clyster = new EntityClyster(world);
        mobRegistry.register((LivingEntity)clyster, LootTableRegistry.ENTITIES_STARFORGE_CLYSTER);
        EntityClyster blueClyster = new EntityClyster(world);
        blueClyster.setEnlarged(true);
        blueClyster.func_96094_a("Blue Clyster");
        mobRegistry.register((LivingEntity)blueClyster, LootTableRegistry.ENTITIES_STARFORGE_BLUE_CLYSTER);
        EntityReflectal reflectal = new EntityReflectal(world);
        mobRegistry.register((LivingEntity)reflectal, LootTableRegistry.ENTITIES_STARFORGE_REFLECTAL);
        EntityReflectal blueReflectal = new EntityReflectal(world);
        blueReflectal.setEnlarged(true);
        blueReflectal.func_96094_a("Blue Reflectal");
        mobRegistry.register((LivingEntity)blueReflectal, LootTableRegistry.ENTITIES_STARFORGE_BLUE_REFLECTAL);
        EntitySpyker spyker = new EntitySpyker(world);
        mobRegistry.register((LivingEntity)spyker, LootTableRegistry.ENTITIES_STARFORGE_SPYKER);
        EntitySpyker blueSpyker = new EntitySpyker(world);
        blueSpyker.setEnlarged(true);
        blueSpyker.func_96094_a("Blue Spyker");
        mobRegistry.register((LivingEntity)blueSpyker, LootTableRegistry.ENTITIES_STARFORGE_BLUE_SPYKER);
        EntityBlisterweed blisterweed = new EntityBlisterweed(world);
        mobRegistry.register((LivingEntity)blisterweed, LootTableRegistry.ENTITIES_BLISTERWEED);
        EntityCaveTerror caveTerror = new EntityCaveTerror(world);
        mobRegistry.register((LivingEntity)caveTerror, LootTableRegistry.ENTITIES_CAVETERROR);
        EntityChomper chomper = new EntityChomper(world);
        mobRegistry.register((LivingEntity)chomper, LootTableRegistry.ENTITIES_STARFORGE_CHOMPER);
        EntityClinger clinger = new EntityClinger(world);
        mobRegistry.register((LivingEntity)clinger, LootTableRegistry.ENTITIES_CLINGER);
        EntityClusterweed clusterweed = new EntityClusterweed(world);
        mobRegistry.register((LivingEntity)clusterweed, LootTableRegistry.ENTITIES_CLUSTERWEED);
        EntityCrabulon crabulon = new EntityCrabulon(world);
        mobRegistry.register((LivingEntity)crabulon, LootTableRegistry.ENTITIES_CRABULON);
        EntityCrawker crawker = new EntityCrawker(world);
        mobRegistry.register((LivingEntity)crawker, LootTableRegistry.ENTITIES_STARFORGE_CRAWKER);
        EntityCrusher crusher = new EntityCrusher(world);
        mobRegistry.register((LivingEntity)crusher, LootTableRegistry.ENTITIES_CRUSHER);
        EntityDeviantBat deviantBat = new EntityDeviantBat(world);
        mobRegistry.register((LivingEntity)deviantBat, LootTableRegistry.ENTITIES_DEVIANTBAT);
        EntityDeviantBat superMutatedBat = new EntityDeviantBat(world);
        superMutatedBat.setMutation(3);
        superMutatedBat.func_96094_a("Super-Mutated Bat");
        mobRegistry.register((LivingEntity)superMutatedBat, LootTableRegistry.ENTITIES_SUPERMUTANT_BAT);
        EntityDeviantBear deviantBear = new EntityDeviantBear(world);
        mobRegistry.register((LivingEntity)deviantBear, LootTableRegistry.ENTITIES_DEVIANTBEAR);
        EntityDeviantBear superMutatedBear = new EntityDeviantBear(world);
        superMutatedBear.setMutation(3);
        superMutatedBear.func_96094_a("Super-Mutated Bear");
        mobRegistry.register((LivingEntity)superMutatedBear, LootTableRegistry.ENTITIES_SUPERMUTANT_BEAR);
        EntityDeviantBlaze deviantBlaze = new EntityDeviantBlaze(world);
        mobRegistry.register((LivingEntity)deviantBlaze, LootTableRegistry.ENTITIES_DEVIANTBLAZE);
        EntityDeviantBlaze superMutatedBlaze = new EntityDeviantBlaze(world);
        superMutatedBlaze.setMutation(3);
        superMutatedBlaze.func_96094_a("Super-Mutated Blaze");
        mobRegistry.register((LivingEntity)superMutatedBlaze, LootTableRegistry.ENTITIES_SUPERMUTANT_BLAZE);
        EntityDeviantCaveSpider deviantCaveSpider = new EntityDeviantCaveSpider(world);
        mobRegistry.register((LivingEntity)deviantCaveSpider, LootTableRegistry.ENTITIES_DEVIANTCAVESPIDER);
        EntityDeviantCaveSpider superMutatedCaveSpider = new EntityDeviantCaveSpider(world);
        superMutatedCaveSpider.setMutation(3);
        superMutatedCaveSpider.func_96094_a("Super-Mutated CaveSpider");
        mobRegistry.register((LivingEntity)superMutatedCaveSpider, LootTableRegistry.ENTITIES_SUPERMUTANT_CAVESPIDER);
        EntityDeviantChicken deviantChicken = new EntityDeviantChicken(world);
        mobRegistry.register((LivingEntity)deviantChicken, LootTableRegistry.ENTITIES_DEVIANTCHICKEN);
        EntityDeviantChicken superMutatedChicken = new EntityDeviantChicken(world);
        superMutatedChicken.setMutation(3);
        superMutatedChicken.func_96094_a("Super-Mutated Chicken");
        mobRegistry.register((LivingEntity)superMutatedChicken, LootTableRegistry.ENTITIES_SUPERMUTANT_CHICKEN);
        EntityDeviantCow deviantCow = new EntityDeviantCow(world);
        mobRegistry.register((LivingEntity)deviantCow, LootTableRegistry.ENTITIES_DEVIANTCOW);
        EntityDeviantCow superMutatedCow = new EntityDeviantCow(world);
        superMutatedCow.setMutation(3);
        superMutatedCow.func_96094_a("Super-Mutated Cow");
        mobRegistry.register((LivingEntity)superMutatedCow, LootTableRegistry.ENTITIES_SUPERMUTANT_COW);
        EntityDeviantCreeper deviantCreeper = new EntityDeviantCreeper(world);
        mobRegistry.register((LivingEntity)deviantCreeper, LootTableRegistry.ENTITIES_DEVIANTCREEPER);
        EntityDeviantCreeper superMutatedCreeper = new EntityDeviantCreeper(world);
        superMutatedCreeper.setMutation(3);
        superMutatedCreeper.func_96094_a("Super-Mutated Creeper");
        mobRegistry.register((LivingEntity)superMutatedCreeper, LootTableRegistry.ENTITIES_SUPERMUTANT_CREEPER);
        EntityDeviantDimTrader deviantDimTrader = new EntityDeviantDimTrader(world);
        mobRegistry.register((LivingEntity)deviantDimTrader, LootTableRegistry.ENTITIES_DEVIANTDIMTRADER);
        EntityDeviantDimTrader superMutatedDimTrader = new EntityDeviantDimTrader(world);
        superMutatedDimTrader.setMutation(3);
        superMutatedDimTrader.func_96094_a("Super-Mutated DimTrader");
        mobRegistry.register((LivingEntity)superMutatedDimTrader, LootTableRegistry.ENTITIES_SUPERMUTANT_DIMTRADER);
        EntityDeviantEnderman deviantEnderman = new EntityDeviantEnderman(world);
        mobRegistry.register((LivingEntity)deviantEnderman, LootTableRegistry.ENTITIES_DEVIANTENDERMAN);
        EntityDeviantEnderman superMutatedEnderman = new EntityDeviantEnderman(world);
        superMutatedEnderman.setMutation(3);
        superMutatedEnderman.func_96094_a("Super-Mutated Enderman");
        mobRegistry.register((LivingEntity)superMutatedEnderman, LootTableRegistry.ENTITIES_SUPERMUTANT_ENDERMAN);
        EntityDeviantEvoker deviantEvoker = new EntityDeviantEvoker(world);
        mobRegistry.register((LivingEntity)deviantEvoker, LootTableRegistry.ENTITIES_DEVIANTEVOKER);
        EntityDeviantGhast deviantGhast = new EntityDeviantGhast(world);
        mobRegistry.register((LivingEntity)deviantGhast, LootTableRegistry.ENTITIES_DEVIANTGHAST);
        EntityDeviantGhast superMutatedGhast = new EntityDeviantGhast(world);
        superMutatedGhast.setMutation(3);
        superMutatedGhast.func_96094_a("Super-Mutated Ghast");
        mobRegistry.register((LivingEntity)superMutatedGhast, LootTableRegistry.ENTITIES_SUPERMUTANT_GHAST);
        EntityDeviantGolem deviantGolem = new EntityDeviantGolem(world);
        mobRegistry.register((LivingEntity)deviantGolem, LootTableRegistry.ENTITIES_DEVIANTGOLEM);
        EntityDeviantGolem superMutatedGolem = new EntityDeviantGolem(world);
        superMutatedGolem.setMutation(3);
        superMutatedGolem.func_96094_a("Super-Mutated Golem");
        mobRegistry.register((LivingEntity)superMutatedGolem, LootTableRegistry.ENTITIES_SUPERMUTANT_GOLEM);
        EntityDeviantGuardian deviantGuardian = new EntityDeviantGuardian(world);
        mobRegistry.register((LivingEntity)deviantGuardian, LootTableRegistry.ENTITIES_DEVIANTGUARDIAN);
        EntityDeviantGuardian superMutatedGuardian = new EntityDeviantGuardian(world);
        superMutatedGuardian.setMutation(3);
        superMutatedGuardian.func_96094_a("Super-Mutated Guardian");
        mobRegistry.register((LivingEntity)superMutatedGuardian, LootTableRegistry.ENTITIES_SUPERMUTANT_GUARDIAN);
        EntityDeviantHorse deviantHorse = new EntityDeviantHorse(world);
        mobRegistry.register((LivingEntity)deviantHorse, LootTableRegistry.ENTITIES_DEVIANTHORSE);
        EntityDeviantHorse superMutatedHorse = new EntityDeviantHorse(world);
        superMutatedHorse.setMutation(3);
        superMutatedHorse.func_96094_a("Super-Mutated Horse");
        mobRegistry.register((LivingEntity)superMutatedHorse, LootTableRegistry.ENTITIES_SUPERMUTANT_HORSE);
        EntityDeviantHusk deviantHusk = new EntityDeviantHusk(world);
        mobRegistry.register((LivingEntity)deviantHusk, LootTableRegistry.ENTITIES_DEVIANTHUSK);
        EntityDeviantHusk superMutatedHusk = new EntityDeviantHusk(world);
        superMutatedHusk.setMutation(3);
        superMutatedHusk.func_96094_a("Super-Mutated Husk");
        mobRegistry.register((LivingEntity)superMutatedHusk, LootTableRegistry.ENTITIES_SUPERMUTANT_HUSK);
        EntityDeviantLlama deviantLlama = new EntityDeviantLlama(world);
        mobRegistry.register((LivingEntity)deviantLlama, LootTableRegistry.ENTITIES_DEVIANTLLAMA);
        EntityDeviantLlama superMutatedLlama = new EntityDeviantLlama(world);
        superMutatedLlama.setMutation(3);
        superMutatedLlama.func_96094_a("Super-Mutated Llama");
        mobRegistry.register((LivingEntity)superMutatedLlama, LootTableRegistry.ENTITIES_SUPERMUTANT_LLAMA);
        EntityDeviantMagmacube deviantMagmacube = new EntityDeviantMagmacube(world);
        mobRegistry.register((LivingEntity)deviantMagmacube, LootTableRegistry.ENTITIES_DEVIANTMAGMACUBE);
        EntityDeviantMagmacube superMutatedMagmacube = new EntityDeviantMagmacube(world);
        superMutatedMagmacube.setMutation(3);
        superMutatedMagmacube.func_96094_a("Super-Mutated Magmacube");
        mobRegistry.register((LivingEntity)superMutatedMagmacube, LootTableRegistry.ENTITIES_SUPERMUTANT_MAGMACUBE);
        EntityDeviantMooshroom deviantMooshroom = new EntityDeviantMooshroom(world);
        mobRegistry.register((LivingEntity)deviantMooshroom, LootTableRegistry.ENTITIES_DEVIANTMOOSHROOM);
        EntityDeviantMooshroom superMutatedMooshroom = new EntityDeviantMooshroom(world);
        superMutatedMooshroom.setMutation(3);
        superMutatedMooshroom.func_96094_a("Super-Mutated Mooshroom");
        mobRegistry.register((LivingEntity)superMutatedMooshroom, LootTableRegistry.ENTITIES_SUPERMUTANT_MOOSHROOM);
        EntityDeviantOcelote deviantOcelote = new EntityDeviantOcelote(world);
        mobRegistry.register((LivingEntity)deviantOcelote, LootTableRegistry.ENTITIES_DEVIANTOCELOTE);
        EntityDeviantOcelote superMutatedOcelote = new EntityDeviantOcelote(world);
        superMutatedOcelote.setMutation(3);
        superMutatedOcelote.func_96094_a("Super-Mutated Ocelot");
        mobRegistry.register((LivingEntity)superMutatedOcelote, LootTableRegistry.ENTITIES_SUPERMUTANT_OCELOTE);
        EntityDeviantPig deviantPig = new EntityDeviantPig(world);
        mobRegistry.register((LivingEntity)deviantPig, LootTableRegistry.ENTITIES_DEVIANTPIG);
        EntityDeviantPig superMutantPig = new EntityDeviantPig(world);
        superMutantPig.setMutation(3);
        superMutantPig.func_96094_a("Super-Mutated Pig");
        mobRegistry.register((LivingEntity)superMutantPig, LootTableRegistry.ENTITIES_SUPERMUTANT_PIG);
        EntityDeviantPiglin deviantPiglin = new EntityDeviantPiglin(world);
        mobRegistry.register((LivingEntity)deviantPiglin, LootTableRegistry.ENTITIES_DEVIANTPIGLIN);
        EntityDeviantPiglin superMutatedPiglin = new EntityDeviantPiglin(world);
        superMutatedPiglin.setMutation(3);
        superMutatedPiglin.func_96094_a("Super-Mutated Piglin");
        mobRegistry.register((LivingEntity)superMutatedPiglin, LootTableRegistry.ENTITIES_SUPERMUTANT_PIGLIN);
        EntityDeviantSheep deviantSheep = new EntityDeviantSheep(world);
        mobRegistry.register((LivingEntity)deviantSheep, LootTableRegistry.ENTITIES_DEVIANTSHEEP);
        EntityDeviantSheep superMutatedSheep = new EntityDeviantSheep(world);
        superMutatedSheep.setMutation(3);
        superMutatedSheep.func_96094_a("Super-Mutated Sheep");
        mobRegistry.register((LivingEntity)superMutatedSheep, LootTableRegistry.ENTITIES_SUPERMUTANT_SHEEP);
        EntityDeviantShulker deviantShulker = new EntityDeviantShulker(world);
        mobRegistry.register((LivingEntity)deviantShulker, LootTableRegistry.ENTITIES_DEVIANTSHULKER);
        EntityDeviantShulker superMutatedShulker = new EntityDeviantShulker(world);
        superMutatedShulker.setMutation(3);
        superMutatedShulker.func_96094_a("Super-Mutated Shulker");
        mobRegistry.register((LivingEntity)superMutatedShulker, LootTableRegistry.ENTITIES_SUPERMUTANT_SHULKER);
        EntityDeviantSkeleton deviantSkeleton = new EntityDeviantSkeleton(world);
        mobRegistry.register((LivingEntity)deviantSkeleton, LootTableRegistry.ENTITIES_DEVIANTSKELETON);
        EntityDeviantSkeleton superMutatedSkeleton = new EntityDeviantSkeleton(world);
        superMutatedSkeleton.setMutation(3);
        superMutatedSkeleton.func_96094_a("Super-Mutated Skeleton");
        mobRegistry.register((LivingEntity)superMutatedSkeleton, LootTableRegistry.ENTITIES_SUPERMUTANT_SKELETON);
        EntityDeviantSkyworm deviantSkyworm = new EntityDeviantSkyworm(world);
        mobRegistry.register((LivingEntity)deviantSkyworm, LootTableRegistry.ENTITIES_DEVIANTSKYWORM);
        EntityDeviantSkyworm superMutatedSkyworm = new EntityDeviantSkyworm(world);
        superMutatedSkyworm.setMutation(3);
        superMutatedSkyworm.func_96094_a("Super-Mutated Skyworm");
        mobRegistry.register((LivingEntity)superMutatedSkyworm, LootTableRegistry.ENTITIES_SUPERMUTANT_SKYWORM);
        EntityDeviantSlime deviantSlime = new EntityDeviantSlime(world);
        mobRegistry.register((LivingEntity)deviantSlime, LootTableRegistry.ENTITIES_DEVIANTSLIME);
        EntityDeviantSlime superMutatedSlime = new EntityDeviantSlime(world);
        superMutatedSlime.setMutation(3);
        superMutatedSlime.func_96094_a("Super-Mutated Slime");
        mobRegistry.register((LivingEntity)superMutatedSlime, LootTableRegistry.ENTITIES_SUPERMUTANT_SLIME);
        EntityDeviantSlimeStrider deviantSlimeStrider = new EntityDeviantSlimeStrider(world);
        mobRegistry.register((LivingEntity)deviantSlimeStrider, LootTableRegistry.ENTITIES_DEVIANTSLIMESTRIDER);
        EntityDeviantSlimeStrider superMutatedSlimeStrider = new EntityDeviantSlimeStrider(world);
        superMutatedSlimeStrider.setMutation(3);
        superMutatedSlimeStrider.func_96094_a("Super-Mutated SlimeStrider");
        mobRegistry.register((LivingEntity)superMutatedSlimeStrider, LootTableRegistry.ENTITIES_SUPERMUTANT_SLIMESTRIDER);
        EntityDeviantSnowman deviantSnowman = new EntityDeviantSnowman(world);
        mobRegistry.register((LivingEntity)deviantSnowman, LootTableRegistry.ENTITIES_DEVIANTSNOWMAN);
        EntityDeviantSnowman superMutatedSnowman = new EntityDeviantSnowman(world);
        superMutatedSnowman.setMutation(3);
        superMutatedSnowman.func_96094_a("Super-Mutated Snowman");
        mobRegistry.register((LivingEntity)superMutatedSnowman, LootTableRegistry.ENTITIES_SUPERMUTANT_SNOWMAN);
        EntityDeviantSpider deviantSpider = new EntityDeviantSpider(world);
        mobRegistry.register((LivingEntity)deviantSpider, LootTableRegistry.ENTITIES_DEVIANTSPIDER);
        EntityDeviantSpider superMutatedSpider = new EntityDeviantSpider(world);
        superMutatedSpider.setMutation(3);
        superMutatedSpider.func_96094_a("Super-Mutated Spider");
        mobRegistry.register((LivingEntity)superMutatedSpider, LootTableRegistry.ENTITIES_SUPERMUTANT_SPIDER);
        EntityDeviantSquid deviantSquid = new EntityDeviantSquid(world);
        mobRegistry.register((LivingEntity)deviantSquid, LootTableRegistry.ENTITIES_DEVIANTSQUID);
        EntityDeviantSquid superMutatedSquid = new EntityDeviantSquid(world);
        superMutatedSquid.setMutation(3);
        superMutatedSquid.func_96094_a("Super-Mutated Squid");
        mobRegistry.register((LivingEntity)superMutatedSquid, LootTableRegistry.ENTITIES_SUPERMUTANT_SQUID);
        EntityDeviantStray deviantStray = new EntityDeviantStray(world);
        mobRegistry.register((LivingEntity)deviantStray, LootTableRegistry.ENTITIES_DEVIANTSTRAY);
        EntityDeviantStray superMutatedStray = new EntityDeviantStray(world);
        superMutatedStray.setMutation(3);
        superMutatedStray.func_96094_a("Super-Mutated Stray");
        mobRegistry.register((LivingEntity)superMutatedStray, LootTableRegistry.ENTITIES_SUPERMUTANT_STRAY);
        EntityDeviantVex deviantVex = new EntityDeviantVex(world);
        mobRegistry.register((LivingEntity)deviantVex, LootTableRegistry.ENTITIES_DEVIANTVEX);
        EntityDeviantVex superMutatedVex = new EntityDeviantVex(world);
        superMutatedVex.setMutation(3);
        superMutatedVex.func_96094_a("Super-Mutated Vex");
        mobRegistry.register((LivingEntity)superMutatedVex, LootTableRegistry.ENTITIES_SUPERMUTANT_VEX);
        EntityDeviantWitch deviantWitch = new EntityDeviantWitch(world);
        mobRegistry.register((LivingEntity)deviantWitch, LootTableRegistry.ENTITIES_DEVIANTWITCH);
        EntityDeviantWitch superMutatedWitch = new EntityDeviantWitch(world);
        superMutatedWitch.setMutation(3);
        superMutatedWitch.func_96094_a("Super-Mutated Witch");
        mobRegistry.register((LivingEntity)superMutatedWitch, LootTableRegistry.ENTITIES_SUPERMUTANT_WITCH);
        EntityDeviantWither deviantWither = new EntityDeviantWither(world);
        mobRegistry.register((LivingEntity)deviantWither, LootTableRegistry.ENTITIES_DEVIANT_WITHER);
        EntityDeviantWitherSkeleton deviantWitherSkeleton = new EntityDeviantWitherSkeleton(world);
        mobRegistry.register((LivingEntity)deviantWitherSkeleton, LootTableRegistry.ENTITIES_DEVIANTWITHERSKELETON);
        EntityDeviantWitherSkeleton superMutatedWitherSkeleton = new EntityDeviantWitherSkeleton(world);
        superMutatedWitherSkeleton.setMutation(3);
        superMutatedWitherSkeleton.func_96094_a("Super-Mutated WitherSkeleton");
        mobRegistry.register((LivingEntity)superMutatedWitherSkeleton, LootTableRegistry.ENTITIES_SUPERMUTANT_WITHERSKELETON);
        EntityDeviantWolf deviantWolf = new EntityDeviantWolf(world);
        mobRegistry.register((LivingEntity)deviantWolf, LootTableRegistry.ENTITIES_DEVIANTWOLF);
        EntityDeviantWolf superMutatedWolf = new EntityDeviantWolf(world);
        superMutatedWolf.setMutation(3);
        superMutatedWolf.func_96094_a("Super-Mutated Wolf");
        mobRegistry.register((LivingEntity)superMutatedWolf, LootTableRegistry.ENTITIES_SUPERMUTANT_WOLF);
        EntityDeviantZombie deviantZombie = new EntityDeviantZombie(world);
        deviantZombie.setNotSummoner();
        mobRegistry.register((LivingEntity)deviantZombie, LootTableRegistry.ENTITIES_DEVIANTZOMBIE);
        EntityDeviantZombie superMutatedZombie = new EntityDeviantZombie(world);
        superMutatedZombie.setMutation(3);
        superMutatedZombie.setNotSummoner();
        superMutatedZombie.func_96094_a("Super-Mutated Zombie");
        mobRegistry.register((LivingEntity)superMutatedZombie, LootTableRegistry.ENTITIES_SUPERMUTANT_ZOMBIE);
        EntityDoomDog doomDog = new EntityDoomDog(world);
        mobRegistry.register((LivingEntity)doomDog, LootTableRegistry.ENTITIES_DOOMDOG);
        EntityDoomsday doomsday = new EntityDoomsday(world);
        mobRegistry.register((LivingEntity)doomsday, LootTableRegistry.ENTITIES_DOOMSDAY);
        EntityDoublejaw doublejaw = new EntityDoublejaw(world);
        mobRegistry.register((LivingEntity)doublejaw, LootTableRegistry.ENTITIES_DOUBLEJAW);
        EntityDrippler drippler = new EntityDrippler(world);
        mobRegistry.register((LivingEntity)drippler, LootTableRegistry.ENTITIES_DRIPPLER);
        EntityDusker dusker = new EntityDusker(world);
        mobRegistry.register((LivingEntity)dusker, LootTableRegistry.ENTITIES_STARFORGE_DUSKER);
        EntityDuskerQueen duskerQueen = new EntityDuskerQueen(world);
        mobRegistry.register((LivingEntity)duskerQueen, LootTableRegistry.ENTITIES_DUSKERQUEEN);
        EntityEelShark eelShark = new EntityEelShark(world);
        mobRegistry.register((LivingEntity)eelShark, LootTableRegistry.ENTITIES_EELSHARK);
        EntityExplosect explosect = new EntityExplosect(world);
        mobRegistry.register((LivingEntity)explosect, LootTableRegistry.ENTITIES_STARFORGE_EXPLOSECT);
        EntityEyeSlug eyeSlug = new EntityEyeSlug(world);
        mobRegistry.register((LivingEntity)eyeSlug, LootTableRegistry.ENTITIES_STARFORGE_EYE_SLUG);
        EntityFlapper flapper = new EntityFlapper(world);
        mobRegistry.register((LivingEntity)flapper, LootTableRegistry.ENTITIES_STARFORGE_FLAPPER);
        EntityFlurky flurky = new EntityFlurky(world);
        mobRegistry.register((LivingEntity)flurky, LootTableRegistry.ENTITIES_STARFORGE_FLURKY);
        EntityFlutterbee flutterbee = new EntityFlutterbee(world);
        mobRegistry.register((LivingEntity)flutterbee, LootTableRegistry.ENTITIES_FLUTTERBEE);
        EntityFyreweed fyreweed = new EntityFyreweed(world);
        mobRegistry.register((LivingEntity)fyreweed, LootTableRegistry.ENTITIES_STARFORGE_FYREWEED);
        EntityGalaxyBeast blueGalaxyBeast = new EntityGalaxyBeast(world);
        blueGalaxyBeast.setColor((byte)1);
        blueGalaxyBeast.func_96094_a("Blue Galaxy Beast");
        mobRegistry.register((LivingEntity)blueGalaxyBeast, LootTableRegistry.ENTITIES_GALAXYBEAST_BLUE);
        EntityGalaxyBeast greenGalaxyBeast = new EntityGalaxyBeast(world);
        greenGalaxyBeast.setColor((byte)2);
        greenGalaxyBeast.func_96094_a("Green Galaxy Beast");
        mobRegistry.register((LivingEntity)greenGalaxyBeast, LootTableRegistry.ENTITIES_GALAXYBEAST_GREEN);
        EntityGalaxyBeast purpleGalaxyBeast = new EntityGalaxyBeast(world);
        purpleGalaxyBeast.setColor((byte)4);
        purpleGalaxyBeast.func_96094_a("Purple Galaxy Beast");
        mobRegistry.register((LivingEntity)purpleGalaxyBeast, LootTableRegistry.ENTITIES_GALAXYBEAST_PURPLE);
        EntityGalaxyBeast yellowGalaxyBeast = new EntityGalaxyBeast(world);
        yellowGalaxyBeast.setColor((byte)3);
        yellowGalaxyBeast.func_96094_a("Yellow Galaxy Beast");
        mobRegistry.register((LivingEntity)yellowGalaxyBeast, LootTableRegistry.ENTITIES_GALAXYBEAST_YELLOW);
        EntityGalaxyGladiator blueGalaxyGladiator = new EntityGalaxyGladiator(world);
        blueGalaxyGladiator.setColor((byte)1);
        blueGalaxyGladiator.func_96094_a("Blue Galaxy Gladiator");
        mobRegistry.register((LivingEntity)blueGalaxyGladiator, LootTableRegistry.ENTITIES_GALAXYGLADIATOR_BLUE);
        EntityGalaxyGladiator greenGalaxyGladiator = new EntityGalaxyGladiator(world);
        greenGalaxyGladiator.setColor((byte)2);
        greenGalaxyGladiator.func_96094_a("Green Galaxy Gladiator");
        mobRegistry.register((LivingEntity)greenGalaxyGladiator, LootTableRegistry.ENTITIES_GALAXYGLADIATOR_GREEN);
        EntityGalaxyGladiator purpleGalaxyGladiator = new EntityGalaxyGladiator(world);
        purpleGalaxyGladiator.setColor((byte)4);
        purpleGalaxyGladiator.func_96094_a("Purple Galaxy Gladiator");
        mobRegistry.register((LivingEntity)purpleGalaxyGladiator, LootTableRegistry.ENTITIES_GALAXYGLADIATOR_PURPLE);
        EntityGalaxyGladiator yellowGalaxyGladiator = new EntityGalaxyGladiator(world);
        yellowGalaxyGladiator.setColor((byte)3);
        yellowGalaxyGladiator.func_96094_a("Yellow Galaxy Gladiator");
        mobRegistry.register((LivingEntity)yellowGalaxyGladiator, LootTableRegistry.ENTITIES_GALAXYGLADIATOR_YELLOW);
        EntityGalaxyGulper galaxyGulper = new EntityGalaxyGulper(world);
        mobRegistry.register((LivingEntity)galaxyGulper, LootTableRegistry.ENTITIES_GALAXYGULPER);
        EntityGalaxySorcerer blueGalaxySorcerer = new EntityGalaxySorcerer(world);
        blueGalaxySorcerer.setColor((byte)1);
        blueGalaxySorcerer.func_96094_a("Blue Galaxy Sorcerer");
        mobRegistry.register((LivingEntity)blueGalaxySorcerer, LootTableRegistry.ENTITIES_GALAXYSORCERER_BLUE);
        EntityGalaxySorcerer greenGalaxySorcerer = new EntityGalaxySorcerer(world);
        greenGalaxySorcerer.setColor((byte)2);
        greenGalaxySorcerer.func_96094_a("Green Galaxy Sorcerer");
        mobRegistry.register((LivingEntity)greenGalaxySorcerer, LootTableRegistry.ENTITIES_GALAXYSORCERER_GREEN);
        EntityGalaxySorcerer purpleGalaxySorcerer = new EntityGalaxySorcerer(world);
        purpleGalaxySorcerer.setColor((byte)4);
        purpleGalaxySorcerer.func_96094_a("Purple Galaxy Sorcerer");
        mobRegistry.register((LivingEntity)purpleGalaxySorcerer, LootTableRegistry.ENTITIES_GALAXYSORCERER_PURPLE);
        EntityGalaxySorcerer yellowGalaxySorcerer = new EntityGalaxySorcerer(world);
        yellowGalaxySorcerer.setColor((byte)3);
        yellowGalaxySorcerer.func_96094_a("Yellow Galaxy Sorcerer");
        mobRegistry.register((LivingEntity)yellowGalaxySorcerer, LootTableRegistry.ENTITIES_GALAXYSORCERER_YELLOW);
        EntityGiantFlapper giantFlapper = new EntityGiantFlapper(world);
        mobRegistry.register((LivingEntity)giantFlapper, LootTableRegistry.ENTITIES_GIANTFLAPPER);
        EntityGiantFyreweed giantFyreweed = new EntityGiantFyreweed(world);
        mobRegistry.register((LivingEntity)giantFyreweed, LootTableRegistry.ENTITIES_GIANTFYREWEED);
        EntityGlangler glangler = new EntityGlangler(world);
        mobRegistry.register((LivingEntity)glangler, LootTableRegistry.ENTITIES_GLANGLER);
        EntityGloboon globoon = new EntityGloboon(world);
        mobRegistry.register((LivingEntity)globoon, LootTableRegistry.ENTITIES_GLOBOON);
        EntityGlobro globro = new EntityGlobro(world);
        mobRegistry.register((LivingEntity)globro, LootTableRegistry.ENTITIES_GLOBRO);
        EntityGlochipper glochipper = new EntityGlochipper(world);
        mobRegistry.register((LivingEntity)glochipper, LootTableRegistry.ENTITIES_GLOCHIPPER);
        EntityGlomite glomite = new EntityGlomite(world);
        mobRegistry.register((LivingEntity)glomite, LootTableRegistry.ENTITIES_GLOMITE);
        EntityGloopMother gloopMother = new EntityGloopMother(world);
        mobRegistry.register((LivingEntity)gloopMother, LootTableRegistry.ENTITIES_GLOOPMOTHER);
        EntityGnawer gnawer = new EntityGnawer(world);
        mobRegistry.register((LivingEntity)gnawer, LootTableRegistry.ENTITIES_STARFORGE_GNAWER);
        EntityGorger gorger = new EntityGorger(world);
        mobRegistry.register((LivingEntity)gorger, LootTableRegistry.ENTITIES_GORGER);
        EntityGrappler grappler = new EntityGrappler(world);
        mobRegistry.register((LivingEntity)grappler, LootTableRegistry.ENTITIES_STARFORGE_GRAPPLER);
        EntityGravhead gravhead = new EntityGravhead(world);
        mobRegistry.register((LivingEntity)gravhead, LootTableRegistry.ENTITIES_STARFORGE_GRAVHEAD);
        EntityGrubber grubber = new EntityGrubber(world);
        mobRegistry.register((LivingEntity)grubber, LootTableRegistry.ENTITIES_GRUBBER);
        EntityHurler hurler = new EntityHurler(world);
        mobRegistry.register((LivingEntity)hurler, LootTableRegistry.ENTITIES_STARFORGE_HURLER);
        EntityHypnosaur hypnosaur = new EntityHypnosaur(world);
        mobRegistry.register((LivingEntity)hypnosaur, LootTableRegistry.ENTITIES_STARFORGE_HYPNOSAUR);
        EntityKalikos kalikos = new EntityKalikos(world);
        mobRegistry.register((LivingEntity)kalikos, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.deviantFragmentTL))});
        EntityLeer leer = new EntityLeer(world);
        mobRegistry.register((LivingEntity)leer, LootTableRegistry.ENTITIES_LEER);
        EntityLivorax livorax = new EntityLivorax(world);
        mobRegistry.register((LivingEntity)livorax, LootTableRegistry.ENTITIES_LIVORAX);
        EntityLurcher lurcher = new EntityLurcher(world);
        mobRegistry.register((LivingEntity)lurcher, LootTableRegistry.ENTITIES_LURCHER);
        EntityMinimite minimite = new EntityMinimite(world);
        mobRegistry.register((LivingEntity)minimite, LootTableRegistry.ENTITIES_MINIMITE);
        EntityMirrorZombie mirrorZombie = new EntityMirrorZombie(world);
        mobRegistry.register((LivingEntity)mirrorZombie, LootTableRegistry.ENTITIES_MIRRORZOMBIE);
        EntityMushmerra mushmerra = new EntityMushmerra(world);
        mobRegistry.register((LivingEntity)mushmerra, LootTableRegistry.ENTITIES_MUSHMERRA);
        EntityOrbiter orbiter = new EntityOrbiter(world);
        mobRegistry.register((LivingEntity)orbiter, LootTableRegistry.ENTITIES_ORBITER);
        EntityPhaser phaser = new EntityPhaser(world);
        mobRegistry.register((LivingEntity)phaser, LootTableRegistry.ENTITIES_STARFORGE_PHASER);
        EntityRavager ravager = new EntityRavager(world);
        mobRegistry.register((LivingEntity)ravager, LootTableRegistry.ENTITIES_RAVAGER);
        EntityRibrex ribrex = new EntityRibrex(world);
        mobRegistry.register((LivingEntity)ribrex, LootTableRegistry.ENTITIES_STARFORGE_RIBREX);
        EntityRockslug rockslug = new EntityRockslug(world);
        mobRegistry.register((LivingEntity)rockslug, LootTableRegistry.ENTITIES_ROCKSLUG);
        EntityRockpest rockpest = new EntityRockpest(world);
        mobRegistry.register((LivingEntity)rockpest, LootTableRegistry.ENTITIES_STARFORGE_ROCKPEST);
        EntityScorpwing scorpwing = new EntityScorpwing(world);
        mobRegistry.register((LivingEntity)scorpwing, LootTableRegistry.ENTITIES_SCORPWING);
        EntityScreacher screacher = new EntityScreacher(world);
        mobRegistry.register((LivingEntity)screacher, LootTableRegistry.ENTITIES_STARFORGE_SCREACHER);
        EntitySeaSerpentController seaCreature = new EntitySeaSerpentController(world);
        mobRegistry.register((LivingEntity)seaCreature, LootTableRegistry.ENTITIES_SEASERPENT);
        EntityShimmer shimmer = new EntityShimmer(world);
        mobRegistry.register((LivingEntity)shimmer, LootTableRegistry.ENTITIES_STARFORGE_SHIMMER);
        EntityShroomite shroomite = new EntityShroomite(world);
        mobRegistry.register((LivingEntity)shroomite, LootTableRegistry.ENTITIES_SHROOMITE);
        EntitySightwalker sightwalker = new EntitySightwalker(world);
        mobRegistry.register((LivingEntity)sightwalker, LootTableRegistry.ENTITIES_SIGHTWALKER);
        EntitySkyre skyre = new EntitySkyre(world);
        mobRegistry.register((LivingEntity)skyre, LootTableRegistry.ENTITIES_SKYRE);
        EntitySlimeStrider slimeStrider = new EntitySlimeStrider(world);
        mobRegistry.register((LivingEntity)slimeStrider, LootTableRegistry.ENTITIES_SLIMESTRIDER);
        EntitySnapper snapper = new EntitySnapper(world);
        mobRegistry.register((LivingEntity)snapper, LootTableRegistry.ENTITIES_SNAPPER);
        EntitySpinovern spinovern = new EntitySpinovern(world);
        mobRegistry.register((LivingEntity)spinovern, LootTableRegistry.ENTITIES_STARFORGE_SPINOVERN);
        EntityStarfiend starfiend = new EntityStarfiend(world);
        mobRegistry.register((LivingEntity)starfiend, LootTableRegistry.ENTITIES_STARFIEND);
        EntityTentaclon tentaclon = new EntityTentaclon(world);
        mobRegistry.register((LivingEntity)tentaclon, LootTableRegistry.ENTITIES_TENTACLON);
        EntityTerrorFly terrorFly = new EntityTerrorFly(world);
        mobRegistry.register((LivingEntity)terrorFly, LootTableRegistry.ENTITIES_TERRORFLY);
        EntityTetherbug tetherbug = new EntityTetherbug(world);
        mobRegistry.register((LivingEntity)tetherbug, LootTableRegistry.ENTITIES_TETHERBUG);
        EntityTitanBlaze titanBlaze = new EntityTitanBlaze(world);
        mobRegistry.register((LivingEntity)titanBlaze, LootTableRegistry.ENTITIES_TITAN_BLAZE);
        EntityTitanCreeper titanCreeper = new EntityTitanCreeper(world);
        mobRegistry.register((LivingEntity)titanCreeper, LootTableRegistry.ENTITIES_TITAN_CREEPER);
        EntityTitanEnderman titanEnderman = new EntityTitanEnderman(world);
        mobRegistry.register((LivingEntity)titanEnderman, LootTableRegistry.ENTITIES_TITAN_ENDERMAN);
        EntityTitanLlama titanLlama = new EntityTitanLlama(world);
        mobRegistry.register((LivingEntity)titanLlama, LootTableRegistry.ENTITIES_TITAN_LLAMA);
        EntityTitanMagmacube titanMagmaCube = new EntityTitanMagmacube(world);
        mobRegistry.register((LivingEntity)titanMagmaCube, LootTableRegistry.ENTITIES_TITAN_MAGMACUBE);
        EntityTitanPiglin titanPigman = new EntityTitanPiglin(world);
        mobRegistry.register((LivingEntity)titanPigman, LootTableRegistry.ENTITIES_TITAN_PIGMAN);
        EntityTitanShulker titanShulker = new EntityTitanShulker(world);
        mobRegistry.register((LivingEntity)titanShulker, LootTableRegistry.ENTITIES_TITAN_SHULKER);
        EntityTitanSkeleton titanSkeleton = new EntityTitanSkeleton(world);
        mobRegistry.register((LivingEntity)titanSkeleton, LootTableRegistry.ENTITIES_TITAN_SKELETON);
        EntityTitanSpider titanSpider = new EntityTitanSpider(world);
        mobRegistry.register((LivingEntity)titanSpider, LootTableRegistry.ENTITIES_TITAN_SPIDER);
        EntityTitanStray titanStray = new EntityTitanStray(world);
        mobRegistry.register((LivingEntity)titanStray, LootTableRegistry.ENTITIES_TITAN_STRAY);
        EntityTitanVex titanVex = new EntityTitanVex(world);
        mobRegistry.register((LivingEntity)titanVex, LootTableRegistry.ENTITIES_TITAN_VEX);
        EntityTitanZombie titanZombie = new EntityTitanZombie(world);
        mobRegistry.register((LivingEntity)titanZombie, LootTableRegistry.ENTITIES_TITAN_ZOMBIE);
        EntityTitanopod titanopod = new EntityTitanopod(world);
        mobRegistry.register((LivingEntity)titanopod, LootTableRegistry.ENTITIES_TITANOPOD);
        EntityTorpedon torpedon = new EntityTorpedon(world);
        mobRegistry.register((LivingEntity)torpedon, LootTableRegistry.ENTITIES_TORPEDON);
        EntityVilebulb vilebulb = new EntityVilebulb(world);
        mobRegistry.register((LivingEntity)vilebulb, LootTableRegistry.ENTITIES_VILEBULB);
        EntityWeaver weaver = new EntityWeaver(world);
        mobRegistry.register((LivingEntity)weaver, LootTableRegistry.ENTITIES_WEAVER);
        EntityZenon zenon = new EntityZenon(world);
        mobRegistry.register((LivingEntity)zenon, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.deviantFragmentBL))});
        EntityUrogo urogo = new EntityUrogo(world);
        mobRegistry.register((LivingEntity)urogo, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.corruptionCube))});
        EntityElara elaraDuality = new EntityElara(world);
        elaraDuality.setForm((byte)0);
        mobRegistry.register((LivingEntity)elaraDuality, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.dualityCube))});
        EntityElara elaraAspiration = new EntityElara(world);
        elaraAspiration.setForm((byte)1);
        mobRegistry.register((LivingEntity)elaraAspiration, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.aspirationCube))});
        EntityVelo velo = new EntityVelo(world);
        mobRegistry.register((LivingEntity)velo, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.ingenuityCube))});
        EntityRikarus rikarus = new EntityRikarus(world);
        mobRegistry.register((LivingEntity)rikarus, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.misdirectionCube))});
        EntityNuxuro nuxuro = new EntityNuxuro(world);
        mobRegistry.register((LivingEntity)nuxuro, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.vengeanceCube))});
        EntityDarrio darrio = new EntityDarrio(world);
        mobRegistry.register((LivingEntity)darrio, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.dreadCube))});
        EntityAtlasSpire atlasSpire = new EntityAtlasSpire(world);
        mobRegistry.register((LivingEntity)atlasSpire, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.impositionCube))});
        EntityArash arash = new EntityArash(world);
        mobRegistry.register((LivingEntity)arash, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.retrospectionCube))});
        EntityAlestria alestria = new EntityAlestria(world);
        mobRegistry.register((LivingEntity)alestria, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.anxietyCube))});
        EntityVycellia vycellia = new EntityVycellia(world);
        mobRegistry.register((LivingEntity)vycellia, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.ambitionCube))});
        EntityOzor ozor = new EntityOzor(world);
        mobRegistry.register((LivingEntity)ozor, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.perceptionCube))});
        EntityThundyron thundyron = new EntityThundyron(world);
        mobRegistry.register((LivingEntity)thundyron, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.anticipationCube))});
        EntityBarul barul = new EntityBarul(world);
        mobRegistry.register((LivingEntity)barul, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.crueltyCube))});
        EntityCryonus cryonus = new EntityCryonus(world);
        mobRegistry.register((LivingEntity)cryonus, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.resolveCube))});
        EntityGalacticTerror galacticTerror = new EntityGalacticTerror(world);
        mobRegistry.register((LivingEntity)galacticTerror, new LootDrop[]{new LootDrop(new ItemStack(ItemInit.multigalacticPowerCrystal))});
        BlockState soilState = BlockInit.poweredCrystallizedSoil.func_176223_P();
        plantRegistry.registerWithSoil((Item)((ItemBasicSeeds)ItemInit.glowingSeeds), soilState, new PlantDrop[]{new PlantDrop(new ItemStack(ItemInit.glowingSeeds), 0, 3), new PlantDrop(new ItemStack(ItemInit.glowingGlobes), 1, 1)});
        plantRegistry.registerWithSoil((Item)((ItemBasicSeeds)ItemInit.emberleafSeeds), soilState, new PlantDrop[]{new PlantDrop(new ItemStack(ItemInit.emberleafSeeds), 0, 3), new PlantDrop(new ItemStack(ItemInit.emberPods), 1, 1)});
        plantRegistry.registerWithSoil((Item)((ItemBasicSeeds)ItemInit.pickleSeeds), soilState, new PlantDrop[]{new PlantDrop(new ItemStack(ItemInit.pickleSeeds), 0, 3), new PlantDrop(new ItemStack(ItemInit.pickle), 1, 1)});
        plantRegistry.registerWithSoil((Item)((ItemBasicSeeds)ItemInit.moonflowerSeeds), soilState, new PlantDrop[]{new PlantDrop(new ItemStack(ItemInit.moonflowerSeeds), 0, 3), new PlantDrop(new ItemStack(ItemInit.glowingGlobes), 1, 1)});
    }
}

